package com.wjx871.population.cancellation; import com.wjx871.population.migration.*; import java.time.*; import java.util.*; import org.apache.ibatis.annotations.*;
@Mapper public interface CancellationMapper {
 int insert(CancellationRecord v);Optional<CancellationRecord> findById(Long id);Optional<CancellationRecord> findByApplication(Long id);Optional<CancellationRecord> lockByApplication(Long id);int updateDraft(@Param("v")CancellationRecord v,@Param("version")int version);int updateStatus(@Param("applicationId")Long id,@Param("from")CancellationStatus from,@Param("to")CancellationStatus to,@Param("version")int version,@Param("operatorId")Long operatorId);
 int fillSnapshot(@Param("applicationId")Long id,@Param("target")CancellationTarget target);
 long countOpenPerson(@Param("personId")Long id,@Param("excludeApplicationId")Long exclude);long countOpenHousehold(@Param("householdId")Long id,@Param("excludeApplicationId")Long exclude);
 Optional<CancellationTarget> findPersonTarget(Long id);Optional<CancellationTarget> lockPersonTarget(Long id);Optional<CancellationTarget> findHouseholdTarget(Long id);Optional<CancellationTarget> lockHouseholdTarget(Long id);
 Optional<Residence> findResidence(Long personId);Optional<Residence> lockResidence(Long personId);int deleteResidence(@Param("id")Long id,@Param("version")int version);int insertResidenceArchive(@Param("record")CancellationRecord record,@Param("residence")Residence residence,@Param("operatorId")Long operatorId,@Param("archiveType")String archiveType);Optional<ResidenceArchive> findResidenceArchive(Long applicationId);
 List<Long> activeMembers(Long householdId);int cancelMember(@Param("householdId")Long householdId,@Param("personId")Long personId,@Param("eventDate")LocalDate eventDate);int changeHead(@Param("householdId")Long householdId,@Param("oldHead")Long oldHead,@Param("newHead")Long newHead);int markPending(@Param("householdId")Long householdId,@Param("oldHead")Long oldHead);int updatePersonStatus(@Param("personId")Long personId,@Param("status")String status);long countPendingMigrationIn(Long householdId);
 int insertHouseholdArchive(@Param("record")CancellationRecord record,@Param("target")CancellationTarget target,@Param("operatorId")Long operatorId);Optional<HouseholdArchive> findHouseholdArchiveByApplication(Long applicationId);int cancelHousehold(Long householdId);
 List<CancellationRecord> search(@Param("no")String no,@Param("objectType")String objectType,@Param("reason")String reason,@Param("person")String person,@Param("identity")String identity,@Param("household")String household,@Param("status")String status,@Param("region")String region,@Param("from")LocalDate from,@Param("to")LocalDate to,@Param("limit")int limit,@Param("offset")long offset);long count(@Param("no")String no,@Param("objectType")String objectType,@Param("reason")String reason,@Param("person")String person,@Param("identity")String identity,@Param("household")String household,@Param("status")String status,@Param("region")String region,@Param("from")LocalDate from,@Param("to")LocalDate to);
 List<HouseholdArchive> searchHouseholdArchives(@Param("household")String household,@Param("head")String head,@Param("region")String region,@Param("reason")String reason,@Param("from")LocalDateTime from,@Param("to")LocalDateTime to,@Param("limit")int limit,@Param("offset")long offset);long countHouseholdArchives(@Param("household")String household,@Param("head")String head,@Param("region")String region,@Param("reason")String reason,@Param("from")LocalDateTime from,@Param("to")LocalDateTime to);Optional<HouseholdArchive> findHouseholdArchive(Long id);
}
