package com.wjx871.population.cancellation;import com.wjx871.population.common.ApiResponse;import com.wjx871.population.migration.ExecuteRequest;import jakarta.servlet.http.HttpServletRequest;import jakarta.validation.Valid;import java.time.LocalDate;import lombok.RequiredArgsConstructor;import org.springframework.data.domain.*;import org.springframework.format.annotation.DateTimeFormat;import org.springframework.http.HttpStatus;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/cancellations") @RequiredArgsConstructor public class CancellationController {private final CancellationService service;
@PostMapping("/person/applications")@ResponseStatus(HttpStatus.CREATED)@PreAuthorize("hasAuthority('cancellation:person:create')")public ApiResponse<CancellationCreatedView> createPerson(@Valid@RequestBody PersonCancellationRequest q,HttpServletRequest h){return ApiResponse.created(service.createPerson(q,h));}
@PutMapping("/person/applications/{id}")@PreAuthorize("hasAuthority('application:edit') and hasAuthority('cancellation:person:create')")public ApiResponse<CancellationCreatedView> updatePerson(@PathVariable Long id,@Valid@RequestBody PersonCancellationRequest q){return ApiResponse.ok(service.updatePerson(id,q));}
@PostMapping("/household/applications")@ResponseStatus(HttpStatus.CREATED)@PreAuthorize("hasAuthority('cancellation:household:create')")public ApiResponse<CancellationCreatedView> createHousehold(@Valid@RequestBody HouseholdCancellationRequest q,HttpServletRequest h){return ApiResponse.created(service.createHousehold(q,h));}
@PutMapping("/household/applications/{id}")@PreAuthorize("hasAuthority('application:edit') and hasAuthority('cancellation:household:create')")public ApiResponse<CancellationCreatedView> updateHousehold(@PathVariable Long id,@Valid@RequestBody HouseholdCancellationRequest q){return ApiResponse.ok(service.updateHousehold(id,q));}
@GetMapping("/applications/{id}")@PreAuthorize("hasAuthority('cancellation:view')")public ApiResponse<CancellationDetailView> detail(@PathVariable Long id){return ApiResponse.ok(service.detail(id));}
@PostMapping("/person/applications/{id}/execute")@PreAuthorize("hasAuthority('cancellation:execute')")public ApiResponse<Void> executePerson(@PathVariable Long id,@Valid@RequestBody ExecuteRequest q,HttpServletRequest h){service.executePerson(id,q,h);return ApiResponse.ok(null);}
@PostMapping("/household/applications/{id}/execute")@PreAuthorize("hasAuthority('cancellation:execute')")public ApiResponse<Void> executeHousehold(@PathVariable Long id,@Valid@RequestBody ExecuteRequest q,HttpServletRequest h){service.executeHousehold(id,q,h);return ApiResponse.ok(null);}
@GetMapping@PreAuthorize("hasAuthority('cancellation:view')")public ApiResponse<Page<CancellationView>> search(@RequestParam(required=false)String cancellationNo,@RequestParam(required=false)String cancelObjectType,@RequestParam(required=false)String cancelReasonCode,@RequestParam(required=false)String personName,@RequestParam(required=false)String identityNo,@RequestParam(required=false)String householdNo,@RequestParam(required=false)String businessStatus,@RequestParam(required=false)String regionCode,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate eventFrom,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate eventTo,Pageable p){return ApiResponse.ok(service.search(cancellationNo,cancelObjectType,cancelReasonCode,personName,identityNo,householdNo,businessStatus,regionCode,eventFrom,eventTo,p));}}
