package com.wjx871.population.keypopulation;import com.wjx871.population.common.ApiResponse;import jakarta.servlet.http.HttpServletRequest;import jakarta.validation.Valid;import java.time.LocalDate;import java.util.List;import lombok.RequiredArgsConstructor;import org.springframework.data.domain.*;import org.springframework.format.annotation.DateTimeFormat;import org.springframework.http.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;
@RestController@RequestMapping("/api/key-populations")@RequiredArgsConstructor public class KeyPopulationController{private final KeyPopulationService service;
@GetMapping@PreAuthorize("hasAuthority('key-population:view')")public ApiResponse<Page<KeyPopulationView>> search(@RequestParam(required=false)Long personId,@RequestParam(required=false)String personName,@RequestParam(required=false)String idCard,@RequestParam(required=false)String populationType,@RequestParam(required=false)AttentionLevel attentionLevel,@RequestParam(required=false)KeyPopulationStatus status,@RequestParam(required=false)Long responsibleDepartmentId,@RequestParam(required=false)String regionCode,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate registerDateFrom,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate registerDateTo,Pageable p){return ApiResponse.ok(service.search(personId,personName,idCard,populationType,attentionLevel,status,responsibleDepartmentId,regionCode,registerDateFrom,registerDateTo,p));}
@GetMapping("/{id}")@PreAuthorize("hasAuthority('key-population:view')")public ApiResponse<KeyPopulationView> get(@PathVariable Long id){return ApiResponse.ok(service.get(id));}
@GetMapping("/{id}/history")@PreAuthorize("hasAuthority('key-population:view')")public ApiResponse<List<KeyPopulationHistory>> history(@PathVariable Long id){return ApiResponse.ok(service.history(id));}
@PostMapping("/register-applications")@ResponseStatus(HttpStatus.CREATED)@PreAuthorize("hasAuthority('key-population:apply')")public ApiResponse<KeyApplicationView> register(@Valid@RequestBody RegisterApplicationRequest q,HttpServletRequest h){return ApiResponse.created(service.createRegister(q,h));}
@GetMapping("/register-applications/{id}")@PreAuthorize("hasAuthority('key-population:view')")public ApiResponse<KeyPopulationDetailView> registerDetail(@PathVariable Long id){return ApiResponse.ok(service.detail(id,KeyOperationType.REGISTER));}
@PostMapping("/register-applications/{id}/submit")@PreAuthorize("hasAuthority('key-population:apply') and hasAuthority('application:submit')")public ApiResponse<Void> registerSubmit(@PathVariable Long id,HttpServletRequest h){service.submit(id,h);return ApiResponse.ok(null);}
@PostMapping("/register-applications/{id}/execute")@PreAuthorize("hasAuthority('key-population:execute')")public ApiResponse<Void> registerExecute(@PathVariable Long id,@Valid@RequestBody KeyExecuteRequest q,HttpServletRequest h){service.executeRegister(id,q,h);return ApiResponse.ok(null);}
@PostMapping("/{id}/release-applications")@ResponseStatus(HttpStatus.CREATED)@PreAuthorize("hasAuthority('key-population:apply')")public ApiResponse<KeyApplicationView> release(@PathVariable Long id,@Valid@RequestBody ReleaseApplicationRequest q,HttpServletRequest h){return ApiResponse.created(service.createRelease(id,q,h));}
@GetMapping("/release-applications/{id}")@PreAuthorize("hasAuthority('key-population:view')")public ApiResponse<KeyPopulationDetailView> releaseDetail(@PathVariable Long id){return ApiResponse.ok(service.detail(id,KeyOperationType.RELEASE));}
@PostMapping("/release-applications/{id}/submit")@PreAuthorize("hasAuthority('key-population:apply') and hasAuthority('application:submit')")public ApiResponse<Void> releaseSubmit(@PathVariable Long id,HttpServletRequest h){service.submit(id,h);return ApiResponse.ok(null);}
@PostMapping("/release-applications/{id}/execute")@PreAuthorize("hasAuthority('key-population:execute')")public ApiResponse<Void> releaseExecute(@PathVariable Long id,@Valid@RequestBody KeyExecuteRequest q,HttpServletRequest h){service.executeRelease(id,q,h);return ApiResponse.ok(null);}}
