package com.wjx871.population.export;
import static org.assertj.core.api.Assertions.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;import com.fasterxml.jackson.databind.*;import com.wjx871.population.application.BusinessType;import java.io.*;import java.lang.reflect.Method;import java.nio.file.*;import java.time.*;import java.util.*;import org.apache.poi.ss.usermodel.*;import org.apache.poi.xssf.usermodel.XSSFWorkbook;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.*;import org.springframework.context.ApplicationContext;import org.springframework.context.annotation.*;import org.springframework.http.MediaType;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.test.web.servlet.*;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;
@SpringBootTest(properties={"export.dir=./target/test-exports","export.normal-max-rows=5","export.sensitive-max-rows=20","export.file-retention-days=7"})@AutoConfigureMockMvc@Import(Phase06ExportAuditIntegrationTest.ClockConfig.class)class Phase06ExportAuditIntegrationTest {@TestConfiguration static class ClockConfig{@Bean@Primary Clock clock(){return Clock.fixed(Instant.parse("2026-07-11T00:00:00Z"),ZoneOffset.UTC);}}
@Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired JdbcTemplate jdbc;@Autowired ExportCleanupService cleanup;@Autowired ApplicationContext context;Path root=Path.of("target/test-exports");
@BeforeEach void setup()throws Exception{if(Files.exists(root))try(var s=Files.walk(root)){s.sorted(Comparator.reverseOrder()).filter(p->!p.equals(root)).forEach(p->{try{Files.deleteIfExists(p);}catch(Exception ignored){}});}Files.createDirectories(root);jdbc.update("DELETE FROM data_export_log");jdbc.update("DELETE FROM data_export_request");jdbc.update("DELETE FROM residence_permit_log");jdbc.update("DELETE FROM residence_permit_application");jdbc.update("DELETE FROM residence_permit");jdbc.update("DELETE FROM floating_population");jdbc.update("DELETE FROM floating_registration_application");jdbc.update("DELETE FROM residence_archive");jdbc.update("DELETE FROM cancellation_record");jdbc.update("DELETE FROM migration_in");jdbc.update("DELETE FROM migration_out");jdbc.update("DELETE FROM residence");jdbc.update("DELETE FROM household_member");jdbc.update("DELETE FROM sys_approval_log");jdbc.update("DELETE FROM sys_approval_request");jdbc.update("DELETE FROM application_material");jdbc.update("DELETE FROM business_application");jdbc.update("DELETE FROM operation_log");jdbc.update("DELETE FROM household WHERE household_id>=401");jdbc.update("DELETE FROM person WHERE person_id>=401");jdbc.update("INSERT INTO person(person_id,name,gender,id_card,phone,current_address,status,current_status_code) VALUES(401,'=危险姓名','1','110101199001010011','13800138000','北京市朝阳区示例路1号','正常','REGISTERED')");jdbc.update("INSERT INTO household(household_id,household_no,address,region_code,establish_date,status,version) VALUES(401,'HX401','北京市朝阳区示例路1号','110000',DATE '2020-01-01','ACTIVE',0)");jdbc.update("INSERT INTO residence(person_id,household_id,registered_address,region_code,register_type_code,register_date,start_date,status,version) VALUES(401,401,'北京市朝阳区示例路1号','110000','OTHER',DATE '2020-01-01',DATE '2020-01-01','ACTIVE',0)");jdbc.update("INSERT INTO business_application(application_no,business_type,title,applicant_user_id,applicant_department_id,applicant_region_code,target_person_id,status,reason,version) VALUES('SCOPE-401','KEY_POPULATION_RELEASE','范围授权',1,1,'110000',401,'COMPLETED','测试',0)");}
@AfterEach void clean()throws Exception{if(Files.exists(root))try(var s=Files.walk(root)){s.sorted(Comparator.reverseOrder()).filter(p->!p.equals(root)).forEach(p->{try{Files.deleteIfExists(p);}catch(Exception ignored){}});}}
@Test void allControllerMethodsHavePermissionOrPublicDeclaration(){for(String name:context.getBeanNamesForAnnotation(RestController.class)){Class<?> type=org.springframework.aop.support.AopUtils.getTargetClass(context.getBean(name));for(Method m:type.getDeclaredMethods())if(mapped(m)&&!(type.getSimpleName().equals("AuthController")&&m.getName().equals("login")))assertThat(m.getAnnotation(PreAuthorize.class)!=null||type.getAnnotation(PreAuthorize.class)!=null).as(type.getSimpleName()+"."+m.getName()).isTrue();}}
@Test void unauthenticatedBusinessAccessReturns401()throws Exception{mvc.perform(get("/api/exports")).andExpect(status().isUnauthorized());}
@Test void l1CannotSensitiveApply()throws Exception{sensitive("viewer",403);}
@Test void viewerCannotWritePerson()throws Exception{mvc.perform(post("/api/persons").header("Authorization",bearer(token("viewer"))).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"测试\",\"gender\":\"1\",\"idCard\":\"110101199001010099\"}")).andExpect(status().isForbidden());}
@Test void queryViewerPersonIsMasked()throws Exception{mvc.perform(get("/api/persons/401").header("Authorization",bearer(token("viewer")))).andExpect(status().isOk()).andExpect(jsonPath("$.data.idCard").value("1101**********0011")).andExpect(jsonPath("$.data.phone").value("138****8000"));}
@Test void fullPermissionShowsCompleteIdentity()throws Exception{mvc.perform(get("/api/persons/401").header("Authorization",bearer(token("household")))).andExpect(status().isOk()).andExpect(jsonPath("$.data.idCard").value("110101199001010011"));}
@Test void normalExportRejectsFullIdentity()throws Exception{normal("population",List.of("name","identityNo"),Map.of(),400);}
@Test void normalExportRejectsIllegalField()throws Exception{normal("population",List.of("name","passwordHash"),Map.of(),400);}
@Test void normalExportRejectsSqlFilter()throws Exception{normal("population",List.of("name"),Map.of("name","x' UNION SELECT password_hash"),400);}
@Test void normalExportCreatesXlsxAndCompletedLog()throws Exception{long id=normal("population",List.of("name","maskedIdentityNo","maskedPhone","regionCode"),Map.of(),201);assertThat(jdbc.queryForObject("SELECT status FROM data_export_log WHERE export_log_id=?",String.class,id)).isEqualTo("COMPLETED");assertThat(jdbc.queryForObject("SELECT file_sha256 FROM data_export_log WHERE export_log_id=?",String.class,id)).hasSize(64);assertThat(Files.exists(file(id))).isTrue();}
@Test void normalXlsxContainsMaskedValuesAndEscapedFormula()throws Exception{long id=normal("population",List.of("name","maskedIdentityNo","maskedPhone"),Map.of(),201);try(InputStream in=Files.newInputStream(file(id));Workbook wb=new XSSFWorkbook(in)){Row row=wb.getSheetAt(0).getRow(1);assertThat(row.getCell(0).getStringCellValue()).isEqualTo("'=危险姓名");assertThat(row.getCell(1).getStringCellValue()).isEqualTo("1101**********0011");assertThat(row.getCell(2).getStringCellValue()).isEqualTo("138****8000");assertThat(row.getCell(0).getCellType()).isEqualTo(CellType.STRING);}}
@Test void exportResponseDoesNotExposeStoragePath()throws Exception{String body=normalBody("population",List.of("name"),Map.of(),201);assertThat(body).doesNotContain("storagePath").doesNotContain(root.toAbsolutePath().toString());}
@Test void normalExportOwnerCanDownloadAndCountIncrements()throws Exception{long id=normal("population",List.of("name"),Map.of(),201);download(id,"population",200);assertThat(jdbc.queryForObject("SELECT download_count FROM data_export_log WHERE export_log_id=?",Integer.class,id)).isOne();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM operation_log WHERE operation_type='DATA_EXPORT_DOWNLOAD'",Integer.class)).isOne();}
@Test void otherNormalUserCannotDownload()throws Exception{long id=normal("population",List.of("name"),Map.of(),201);download(id,"viewer",403);}
@Test void genericApplicationRejectsSensitiveExport()throws Exception{mvc.perform(post("/api/applications").header("Authorization",bearer(token("population"))).contentType(MediaType.APPLICATION_JSON).content("{\"businessType\":\"SENSITIVE_DATA_EXPORT\",\"title\":\"非法\",\"reason\":\"测试\"}")).andExpect(status().isBadRequest());}
@Test void specializedSensitiveCreatesBothRecords()throws Exception{long id=sensitive("population",201);assertThat(count("business_application","application_id",id)).isOne();assertThat(count("data_export_request","application_id",id)).isOne();}
@Test void sensitiveWithoutReasonRejected()throws Exception{mvc.perform(post("/api/exports/sensitive/applications").header("Authorization",bearer(token("population"))).contentType(MediaType.APPLICATION_JSON).content(sensitiveJson().replace("核查需要",""))).andExpect(status().isBadRequest());}
@Test void unapprovedSensitiveCannotExecute()throws Exception{long id=sensitive("population",201);execute(id,0,409);}
@Test void approvalDoesNotGenerateFile()throws Exception{long id=approvedSensitive();assertThat(count("data_export_log","application_id",id)).isZero();assertThat(Files.list(root).count()).isZero();}
@Test void approvedSensitiveGeneratesFullData()throws Exception{long app=approvedSensitive();long log=execute(app,2,200);try(InputStream in=Files.newInputStream(file(log));Workbook wb=new XSSFWorkbook(in)){Row row=wb.getSheetAt(0).getRow(1);assertThat(row.getCell(1).getStringCellValue()).isEqualTo("110101199001010011");assertThat(row.getCell(2).getStringCellValue()).isEqualTo("13800138000");}assertThat(appStatus(app)).isEqualTo("COMPLETED");}
@Test void repeatedSensitiveExecutionOnlySucceedsOnce()throws Exception{long app=approvedSensitive();execute(app,2,200);execute(app,2,409);assertThat(count("data_export_log","application_id",app)).isOne();}
@Test void sensitiveDownloadUpdatesAudit()throws Exception{long app=approvedSensitive();long log=execute(app,2,200);download(log,"population",200);assertThat(jdbc.queryForObject("SELECT download_count FROM data_export_log WHERE export_log_id=?",Integer.class,log)).isOne();}
@Test void expiredFileCannotDownload()throws Exception{long id=normal("population",List.of("name"),Map.of(),201);jdbc.update("UPDATE data_export_log SET status='EXPIRED' WHERE export_log_id=?",id);download(id,"population",410);}
@Test void cleanupDeletesExpiredFileAndIsIdempotent()throws Exception{long id=normal("population",List.of("name"),Map.of(),201);Path p=file(id);jdbc.update("UPDATE data_export_log SET completed_at=TIMESTAMP '2026-06-01 00:00:00' WHERE export_log_id=?",id);assertThat(cleanup.runNow()).isOne();assertThat(Files.exists(p)).isFalse();assertThat(jdbc.queryForObject("SELECT status FROM data_export_log WHERE export_log_id=?",String.class,id)).isEqualTo("EXPIRED");assertThat(cleanup.runNow()).isZero();}
@Test void auditMaskingRemovesCredentialsAndSensitiveNumbers(){com.wjx871.population.security.SensitiveDataMaskingService m=context.getBean(com.wjx871.population.security.SensitiveDataMaskingService.class);String x=m.auditDetail("password=secret Bearer abc.def 110101199001010011 13800138000");assertThat(x).doesNotContain("secret","abc.def","110101199001010011","13800138000");}
@Test void lifecycleLogsRemainSeparateFromOperationLogs()throws Exception{long app=approvedSensitive();execute(app,2,200);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM sys_approval_log WHERE application_id=? AND action='EXECUTE'",Integer.class,app)).isOne();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM operation_log WHERE operation_type='DATA_EXPORT_SENSITIVE_EXECUTE'",Integer.class)).isOne();}
private boolean mapped(Method m){return m.isAnnotationPresent(GetMapping.class)||m.isAnnotationPresent(PostMapping.class)||m.isAnnotationPresent(PutMapping.class)||m.isAnnotationPresent(DeleteMapping.class)||m.isAnnotationPresent(PatchMapping.class)||m.isAnnotationPresent(RequestMapping.class);}private long normal(String user,List<String> fields,Map<String,Object> filters,int expected)throws Exception{String b=normalBody(user,fields,filters,expected);return expected==201?json.readTree(b).path("data").path("exportLogId").asLong():0;}private String normalBody(String user,List<String> fields,Map<String,Object> filters,int expected)throws Exception{return mvc.perform(post("/api/exports/normal").header("Authorization",bearer(token(user))).contentType(MediaType.APPLICATION_JSON).content(json.writeValueAsString(Map.of("module","PERSON","filters",filters,"fields",fields)))).andExpect(status().is(expected)).andReturn().getResponse().getContentAsString();}private long sensitive(String user,int expected)throws Exception{String b=mvc.perform(post("/api/exports/sensitive/applications").header("Authorization",bearer(token(user))).contentType(MediaType.APPLICATION_JSON).content(sensitiveJson())).andExpect(status().is(expected)).andReturn().getResponse().getContentAsString();return expected==201?json.readTree(b).path("data").asLong():0;}private String sensitiveJson(){return "{\"module\":\"PERSON\",\"filters\":{\"regionCode\":\"110000\"},\"fields\":[\"name\",\"identityNo\",\"phone\",\"registeredAddress\"],\"reason\":\"核查需要\",\"expectedRowLimit\":5,\"title\":\"敏感数据导出\"}";}private long approvedSensitive()throws Exception{long id=sensitive("population",201);material(id);mvc.perform(post("/api/applications/"+id+"/submit").header("Authorization",bearer(token("population")))).andExpect(status().isOk());long approval=jdbc.queryForObject("SELECT approval_id FROM sys_approval_request WHERE application_id=?",Long.class,id);mvc.perform(post("/api/approvals/"+approval+"/approve").header("Authorization",bearer(token("approver"))).contentType(MediaType.APPLICATION_JSON).content("{\"comment\":\"同意\",\"version\":0}")).andExpect(status().isOk());return id;}private long execute(long id,int version,int expected)throws Exception{String b=mvc.perform(post("/api/exports/sensitive/applications/"+id+"/execute").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"version\":"+version+"}")).andExpect(status().is(expected)).andReturn().getResponse().getContentAsString();return expected==200?json.readTree(b).path("data").path("exportLogId").asLong():0;}private void download(long id,String user,int expected)throws Exception{mvc.perform(get("/api/exports/"+id+"/download").header("Authorization",bearer(token(user)))).andExpect(status().is(expected));}
private void material(long id){String hash=UUID.randomUUID().toString().replace("-","")+UUID.randomUUID().toString().replace("-","");jdbc.update("INSERT INTO application_material(application_id,material_type,material_name,original_filename,stored_filename,storage_path,content_type,file_size,file_sha256,required_flag,verify_status,verify_user_id,uploaded_by) VALUES(?,'EXPORT_JUSTIFICATION','说明','x.pdf',?,?,'application/pdf',1,?,1,'VERIFIED',7,2)",id,UUID.randomUUID()+".pdf","test",hash);}private Path file(long id){String n=jdbc.queryForObject("SELECT stored_filename FROM data_export_log WHERE export_log_id=?",String.class,id);return root.resolve(n);}private int count(String table,String key,long id){return jdbc.queryForObject("SELECT COUNT(*) FROM "+table+" WHERE "+key+"=?",Integer.class,id);}private String appStatus(long id){return jdbc.queryForObject("SELECT status FROM business_application WHERE application_id=?",String.class,id);}private String token(String user)throws Exception{String b=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"username\":\""+user+"\",\"password\":\"123456\"}")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();return json.readTree(b).path("data").path("token").asText();}private String bearer(String t){return"Bearer "+t;}}
