package com.wjx871.population.migration;

import static org.assertj.core.api.Assertions.assertThat; import static org.mockito.Mockito.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import com.fasterxml.jackson.databind.*; import java.util.*; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.boot.test.mock.mockito.MockBean; import org.springframework.http.MediaType; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.test.web.servlet.MockMvc;

@SpringBootTest @AutoConfigureMockMvc
class Phase03MigrationIntegrationTest {
 @Autowired MockMvc mvc; @Autowired ObjectMapper json; @Autowired JdbcTemplate jdbc; @MockBean MigrationTransactionHook hook;
 @BeforeEach void setup(){reset(hook);jdbc.update("DELETE FROM residence_archive");jdbc.update("DELETE FROM migration_in");jdbc.update("DELETE FROM migration_out");jdbc.update("DELETE FROM residence");jdbc.update("DELETE FROM household_member");jdbc.update("DELETE FROM sys_approval_log");jdbc.update("DELETE FROM sys_approval_request");jdbc.update("DELETE FROM application_material");jdbc.update("DELETE FROM business_application");jdbc.update("DELETE FROM operation_log");jdbc.update("DELETE FROM household WHERE household_id>=101");jdbc.update("DELETE FROM person WHERE person_id>=101");jdbc.update("INSERT INTO person(person_id,name,gender,id_card,current_address,status,current_status_code) VALUES(101,'甲','1','110101199001010011','旧址','正常','REGISTERED'),(102,'乙','2','110101199202020022',NULL,'正常','PENDING'),(103,'丙','1','110101199303030033','旧址','正常','REGISTERED')");jdbc.update("INSERT INTO household(household_id,household_no,head_person_id,address,region_code,establish_date,status,version) VALUES(101,'H-101',101,'北京市东城区旧址','110101',DATE '2020-01-01','ACTIVE',0)");jdbc.update("INSERT INTO household_member(household_id,person_id,relationship,join_date,status,version) VALUES(101,101,'HEAD',DATE '2020-01-01','ACTIVE',0),(101,103,'CHILD',DATE '2020-01-01','ACTIVE',0)");jdbc.update("INSERT INTO residence(person_id,household_id,registered_address,region_code,register_type_code,register_date,start_date,status,created_by,version) VALUES(101,101,'北京市东城区旧址','110101','BIRTH',DATE '2020-01-01',DATE '2020-01-01','ACTIVE',6,0),(103,101,'北京市东城区旧址','110101','BIRTH',DATE '2020-01-01',DATE '2020-01-01','ACTIVE',6,0)");}

 @Test void l2CanCreateInButL1Cannot(){expectCreateIn("household",201);expectCreateIn("viewer",403);}
 @Test void createInAtomicallyCreatesGenericAndSpecializedDraft(){long id=createIn();assertThat(count("business_application","application_id",id)).isOne();assertThat(jdbc.queryForObject("SELECT business_status FROM migration_in WHERE application_id=?",String.class,id)).isEqualTo("DRAFT");}
 @Test void existingResidenceCannotMigrateIn(){expectCreateInFor(101,409);}
 @Test void outReadsCurrentResidenceAndIgnoresForgedOrigin() throws Exception {long id=createOut(101,103);assertThat(jdbc.queryForObject("SELECT from_household_id FROM migration_out WHERE application_id=?",Long.class,id)).isEqualTo(101);assertThat(jdbc.queryForObject("SELECT from_address_snapshot FROM migration_out WHERE application_id=?",String.class,id)).isEqualTo("北京市东城区旧址");}
 @Test void personWithoutResidenceCannotCreateOut(){expectCreateOut(102,null,409);}
 @Test void migrationSpecificMaterialsAreRequiredOnSubmit() throws Exception {long id=createIn();material(id,"IDENTITY_PROOF","VERIFIED");mvc.perform(post("/api/applications/"+id+"/submit").header("Authorization",bearer(token("household")))).andExpect(status().isConflict());assertThat(statusOf(id)).isEqualTo("DRAFT");}
 @Test void approvalSynchronizesStatusButDoesNotExecuteResidence() throws Exception {long id=approvedIn();assertThat(statusOf(id)).isEqualTo("APPROVED");assertThat(jdbc.queryForObject("SELECT business_status FROM migration_in WHERE application_id=?",String.class,id)).isEqualTo("APPROVED");assertThat(count("residence","person_id",102)).isZero();}
 @Test void executeInCreatesUniqueResidenceMemberAndCompletesBothStates() throws Exception {long id=approvedIn();execute("in",id,200);assertThat(count("residence","person_id",102)).isOne();assertThat(jdbc.queryForObject("SELECT status FROM household_member WHERE person_id=102",String.class)).isEqualTo("ACTIVE");assertThat(statusOf(id)).isEqualTo("COMPLETED");assertThat(jdbc.queryForObject("SELECT business_status FROM migration_in WHERE application_id=?",String.class,id)).isEqualTo("COMPLETED");execute("in",id,409);}
 @Test void executeInReactivatesPreviouslyMovedOutMember() throws Exception {jdbc.update("INSERT INTO household_member(household_id,person_id,relationship,join_date,status,version) VALUES(101,102,'OTHER',DATE '2020-01-01','MOVED_OUT',0)");long id=approvedIn();execute("in",id,200);assertThat(jdbc.queryForObject("SELECT status FROM household_member WHERE household_id=101 AND person_id=102",String.class)).isEqualTo("ACTIVE");assertThat(count("household_member","person_id",102)).isEqualTo(1);}
 @Test void executeOutArchivesSnapshotRemovesCurrentResidenceAndChangesHead() throws Exception {long id=approvedOut(103);execute("out",id,200);assertThat(count("residence","person_id",101)).isZero();assertThat(jdbc.queryForObject("SELECT status FROM household_member WHERE person_id=101",String.class)).isEqualTo("LEFT");assertThat(jdbc.queryForObject("SELECT head_person_id FROM household WHERE household_id=101",Long.class)).isEqualTo(103);assertThat(jdbc.queryForObject("SELECT registered_address_snapshot FROM residence_archive WHERE application_id=?",String.class,id)).isEqualTo("北京市东城区旧址");jdbc.update("UPDATE household SET address='新地址' WHERE household_id=101");assertThat(jdbc.queryForObject("SELECT registered_address_snapshot FROM residence_archive WHERE application_id=?",String.class,id)).isEqualTo("北京市东城区旧址");execute("out",id,409);}
 @Test void headWithOtherMembersNeedsValidNewHeadAtExecution() throws Exception {long id=approvedOut(null);execute("out",id,409);assertThat(count("residence_archive","application_id",id)).isZero();assertThat(count("residence","person_id",101)).isOne();}
 @Test void lastMemberOutMarksHouseholdPendingCancellation() throws Exception {jdbc.update("DELETE FROM residence WHERE person_id=103");jdbc.update("DELETE FROM household_member WHERE person_id=103");long id=approvedOut(null);execute("out",id,200);assertThat(jdbc.queryForObject("SELECT status FROM household WHERE household_id=101",String.class)).isEqualTo("PENDING_CANCELLATION");}
 @Test void failureAfterArchiveRollsBackEveryWrite() throws Exception {long id=approvedOut(103);doThrow(new IllegalStateException("simulated")).when(hook).afterArchiveInserted();mvc.perform(post("/api/migrations/out/applications/"+id+"/execute").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"version\":2}")).andExpect(status().is5xxServerError());assertThat(count("residence_archive","application_id",id)).isZero();assertThat(count("residence","person_id",101)).isOne();assertThat(statusOf(id)).isEqualTo("APPROVED");}
 @Test void failureAfterResidenceDeleteRollsBackArchiveResidenceAndMember() throws Exception {long id=approvedOut(103);doThrow(new IllegalStateException("simulated-delete-boundary")).when(hook).afterResidenceDeleted();execute("out",id,500);assertThat(count("residence_archive","application_id",id)).isZero();assertThat(count("residence","person_id",101)).isOne();assertThat(jdbc.queryForObject("SELECT status FROM household_member WHERE person_id=101",String.class)).isEqualTo("ACTIVE");assertThat(statusOf(id)).isEqualTo("APPROVED");}
 @Test void failureAfterResidenceInsertRollsBackMigrationInCompletely() throws Exception {long id=approvedIn();doThrow(new IllegalStateException("simulated-in-boundary")).when(hook).afterResidenceInserted();execute("in",id,500);assertThat(count("residence","person_id",102)).isZero();assertThat(count("household_member","person_id",102)).isZero();assertThat(statusOf(id)).isEqualTo("APPROVED");}
 @Test void crossDistrictOutAndInUseOneTransferBatch() throws Exception {long out=createOut(101,103);jdbc.update("UPDATE migration_out SET migration_type='IN_CITY_CROSS_DISTRICT',to_region_code='110101' WHERE application_id=?",out);material(out,"IDENTITY_PROOF","VERIFIED");material(out,"HOUSEHOLD_BOOK","VERIFIED");submitApprove(out);execute("out",out,200);String batch=jdbc.queryForObject("SELECT transfer_batch_no FROM migration_out WHERE application_id=?",String.class,out);assertThat(batch).startsWith("TR-");long in=createCrossIn(101,batch);material(in,"IDENTITY_PROOF","VERIFIED");material(in,"ADDRESS_PROOF","VERIFIED");material(in,"MIGRATION_PROOF","VERIFIED");submitApprove(in);execute("in",in,200);assertThat(count("residence","person_id",101)).isOne();assertThat(jdbc.queryForObject("SELECT transfer_batch_no FROM migration_in WHERE application_id=?",String.class,in)).isEqualTo(batch);}
 @Test void archiveIdentityIsMaskedForReadOnlyArchiveViewer() throws Exception {long id=approvedOut(103);execute("out",id,200);mvc.perform(get("/api/residence-archives").header("Authorization",bearer(token("approver")))).andExpect(status().isOk()).andExpect(jsonPath("$.data.content[0].identityNo").value("1101**********0011"));}

 private void expectCreateInFor(int person,int expected){createInFor(person,expected);}
 private long createOut(long person,int head)throws Exception{return createOut(person,Long.valueOf(head));}
 private long approvedOut(int head)throws Exception{return approvedOut(Long.valueOf(head));}
 private long approvedIn() throws Exception {long id=createIn();material(id,"IDENTITY_PROOF","VERIFIED");material(id,"ADDRESS_PROOF","VERIFIED");submitApprove(id);return id;}
 private long approvedOut(Long newHead) throws Exception {long id=createOut(101,newHead);material(id,"IDENTITY_PROOF","VERIFIED");material(id,"HOUSEHOLD_BOOK","VERIFIED");if(newHead==null)material(id,"HOUSEHOLD_CONSENT","VERIFIED");submitApprove(id);return id;}
 private void submitApprove(long id)throws Exception{mvc.perform(post("/api/applications/"+id+"/submit").header("Authorization",bearer(token("household")))).andExpect(status().isOk());long approval=jdbc.queryForObject("SELECT approval_id FROM sys_approval_request WHERE application_id=?",Long.class,id);mvc.perform(post("/api/approvals/"+approval+"/approve").header("Authorization",bearer(token("approver"))).contentType(MediaType.APPLICATION_JSON).content("{\"comment\":\"同意\",\"version\":0}")).andExpect(status().isOk());}
 private void material(long id,String type,String verify){jdbc.update("INSERT INTO application_material(application_id,material_type,material_name,original_filename,stored_filename,storage_path,content_type,file_size,file_sha256,required_flag,verify_status,verify_user_id,uploaded_by) VALUES(?,?,?,'x.pdf',?,?,'application/pdf',1,?,1,?,7,6)",id,type,type,UUID.randomUUID()+".pdf","test",UUID.randomUUID().toString().replace("-","")+UUID.randomUUID().toString().replace("-",""),verify);}
 private long createIn(){return createInFor(102,201);} private long createInFor(long person,int expected){try{String b=mvc.perform(post("/api/migrations/in/applications").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"personId\":"+person+",\"migrationType\":\"OUTSIDE_CITY\",\"fromRegionCode\":\"370100\",\"fromAddress\":\"济南\",\"toRegionCode\":\"110101\",\"toHouseholdId\":101,\"inDate\":\"2026-07-12\",\"reason\":\"投靠\",\"title\":\"迁入申请\"}")).andExpect(status().is(expected)).andReturn().getResponse().getContentAsString();return expected==201?json.readTree(b).path("data").path("applicationId").asLong():0;}catch(Exception e){throw new RuntimeException(e);}}
 private long createCrossIn(long person,String batch)throws Exception{String b=mvc.perform(post("/api/migrations/in/applications").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"personId\":"+person+",\"migrationType\":\"IN_CITY_CROSS_DISTRICT\",\"fromRegionCode\":\"110000\",\"fromAddress\":\"原区地址\",\"toRegionCode\":\"110101\",\"toHouseholdId\":101,\"transferBatchNo\":\""+batch+"\",\"inDate\":\"2026-07-13\",\"reason\":\"跨区\",\"title\":\"跨区迁入\"}")).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();return json.readTree(b).path("data").path("applicationId").asLong();}
 private void expectCreateIn(String user,int expected){try{mvc.perform(post("/api/migrations/in/applications").header("Authorization",bearer(token(user))).contentType(MediaType.APPLICATION_JSON).content("{\"personId\":102,\"migrationType\":\"OUTSIDE_CITY\",\"fromAddress\":\"济南\",\"toRegionCode\":\"110101\",\"toHouseholdId\":101,\"inDate\":\"2026-07-12\",\"reason\":\"投靠\",\"title\":\"迁入申请\"}")).andExpect(status().is(expected));}catch(Exception e){throw new RuntimeException(e);}}
 private long createOut(long person,Long head)throws Exception{String h=head==null?"null":head.toString();String b=mvc.perform(post("/api/migrations/out/applications").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"personId\":"+person+",\"migrationType\":\"OUTSIDE_CITY\",\"toRegionCode\":\"310000\",\"toAddress\":\"上海\",\"outDate\":\"2026-07-12\",\"reason\":\"工作\",\"newHeadPersonId\":"+h+",\"fromHouseholdId\":999,\"fromAddressSnapshot\":\"伪造\",\"title\":\"迁出申请\"}")).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();return json.readTree(b).path("data").path("applicationId").asLong();}
 private void expectCreateOut(long p,Long h,int expected){try{String head=h==null?"null":h.toString();mvc.perform(post("/api/migrations/out/applications").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"personId\":"+p+",\"migrationType\":\"OUTSIDE_CITY\",\"toAddress\":\"上海\",\"outDate\":\"2026-07-12\",\"reason\":\"工作\",\"newHeadPersonId\":"+head+",\"title\":\"迁出申请\"}")).andExpect(status().is(expected));}catch(Exception e){throw new RuntimeException(e);}}
 private void execute(String direction,long id,int status)throws Exception{mvc.perform(post("/api/migrations/"+direction+"/applications/"+id+"/execute").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"version\":2}")).andExpect(status().is(status));}
 private int count(String table,String key,long id){return jdbc.queryForObject("SELECT COUNT(*) FROM "+table+" WHERE "+key+"=?",Integer.class,id);}private String statusOf(long id){return jdbc.queryForObject("SELECT status FROM business_application WHERE application_id=?",String.class,id);}
 private String token(String user)throws Exception{String b=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"username\":\""+user+"\",\"password\":\"123456\"}")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();return json.readTree(b).path("data").path("token").asText();}private String bearer(String t){return "Bearer "+t;}
}
