package com.wjx871.population.migration;

import com.wjx871.population.application.*; import com.wjx871.population.approval.*; import com.wjx871.population.audit.OperationLogService; import com.wjx871.population.common.BusinessException; import com.wjx871.population.material.*; import com.wjx871.population.person.*; import com.wjx871.population.security.*;
import jakarta.servlet.http.HttpServletRequest; import java.time.*; import java.time.format.DateTimeFormatter; import java.util.*; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;

@Service @RequiredArgsConstructor
public class MigrationService {
 private final MigrationMapper mapper; private final ApplicationService applications; private final BusinessApplicationMapper applicationMapper; private final PersonMapper persons; private final MigrationMaterialRequirementService materials; private final ApplicationMaterialMapper materialMapper; private final ApprovalRequestMapper approvalRequests; private final MigrationTransactionHook hook; private final OperationLogService audit; private final ApprovalLogMapper logs;

 @Transactional public MigrationCreatedView createIn(MigrationInRequest r,HttpServletRequest http){requirePerson(r.personId());if(mapper.findResidence(r.personId()).isPresent())throw conflict("该人员已存在当前户籍");HouseholdSnapshot h=requireActiveHousehold(r.toHouseholdId());validateInType(r);ApplicationView a=applications.createSpecialized(appRequest(BusinessType.MIGRATION_IN,r.title(),r.personId(),r.toHouseholdId(),r.reason(),r.remark(),null),http);MigrationIn v=inValue(a.applicationId(),r);mapper.insertIn(v);return new MigrationCreatedView(a.applicationId(),a.applicationNo(),v.getInId(),a.status(),v.getBusinessStatus());}
 @Transactional public MigrationCreatedView createOut(MigrationOutRequest r,HttpServletRequest http){requirePerson(r.personId());Residence residence=mapper.findResidence(r.personId()).orElseThrow(()->conflict("该人员没有当前有效户籍"));HouseholdSnapshot h=requireActiveHousehold(residence.getHouseholdId());validateHead(r,h);ApplicationView a=applications.createSpecialized(appRequest(BusinessType.MIGRATION_OUT,r.title(),r.personId(),h.getHouseholdId(),r.reason(),r.remark(),null),http);MigrationOut v=outValue(a.applicationId(),r,residence);mapper.insertOut(v);return new MigrationCreatedView(a.applicationId(),a.applicationNo(),v.getOutId(),a.status(),v.getBusinessStatus());}
 @Transactional public MigrationCreatedView updateIn(Long id,MigrationInRequest r){BusinessApplication a=applications.require(id);applications.assertOwner(a,CurrentUserContext.requireUser());requireDraft(a);MigrationIn old=mapper.findIn(id).orElseThrow(()->notFound("迁入详情不存在"));if(r.version()==null)throw bad("version 不能为空");requirePerson(r.personId());if(mapper.findResidence(r.personId()).isPresent())throw conflict("该人员已存在当前户籍");requireActiveHousehold(r.toHouseholdId());validateInType(r);MigrationIn v=inValue(id,r);if(mapper.updateInDraft(v,r.version())==0)ApplicationService.conflict();ApplicationView av=applications.updateSpecialized(id,appRequest(BusinessType.MIGRATION_IN,r.title(),r.personId(),r.toHouseholdId(),r.reason(),r.remark(),a.getVersion()));return new MigrationCreatedView(id,av.applicationNo(),old.getInId(),av.status(),MigrationBusinessStatus.DRAFT);}
 @Transactional public MigrationCreatedView updateOut(Long id,MigrationOutRequest r){BusinessApplication a=applications.require(id);applications.assertOwner(a,CurrentUserContext.requireUser());requireDraft(a);MigrationOut old=mapper.findOut(id).orElseThrow(()->notFound("迁出详情不存在"));if(r.version()==null)throw bad("version 不能为空");Residence res=mapper.findResidence(r.personId()).orElseThrow(()->conflict("该人员没有当前有效户籍"));HouseholdSnapshot h=requireActiveHousehold(res.getHouseholdId());validateHead(r,h);MigrationOut v=outValue(id,r,res);if(mapper.updateOutDraft(v,r.version())==0)ApplicationService.conflict();ApplicationView av=applications.updateSpecialized(id,appRequest(BusinessType.MIGRATION_OUT,r.title(),r.personId(),h.getHouseholdId(),r.reason(),r.remark(),a.getVersion()));return new MigrationCreatedView(id,av.applicationNo(),old.getOutId(),av.status(),MigrationBusinessStatus.DRAFT);}

 @Transactional(readOnly=true) public MigrationDetailView detail(Long id){BusinessApplication a=applications.require(id);assertMigrationScope(a,CurrentUserContext.requireUser());MigrationIn in=mapper.findIn(id).orElse(null);MigrationOut out=mapper.findOut(id).orElse(null);if(in==null&&out==null)throw notFound("迁移详情不存在");Long personId=in!=null?in.getPersonId():out.getPersonId();Residence res=mapper.findResidence(personId).orElse(null);Long householdId=res!=null?res.getHouseholdId():(in!=null?in.getToHouseholdId():out.getFromHouseholdId());HouseholdSnapshot h=mapper.findHousehold(householdId).orElse(null);boolean executable=a.getStatus()==ApplicationStatus.APPROVED&&((in!=null&&in.getBusinessStatus()==MigrationBusinessStatus.APPROVED)||(out!=null&&out.getBusinessStatus()==MigrationBusinessStatus.APPROVED));return new MigrationDetailView(ApplicationView.from(a),in,out,res,h,h==null?List.of():mapper.activeMembers(h.getHouseholdId()),materialMapper.selectByApplicationId(id).stream().map(MaterialView::from).toList(),approvalRequests.selectByApplicationId(id).orElse(null),logs.selectByApplicationId(id).stream().map(ApprovalLogView::from).toList(),executable,executable?null:"申请尚未批准或已执行");}

 @Transactional public void executeIn(Long id,ExecuteRequest request,HttpServletRequest http){AuthenticatedUser u=CurrentUserContext.requireUser();BusinessApplication a=applications.require(id);assertExecution(a,u);MigrationIn v=mapper.lockIn(id).orElseThrow(()->notFound("迁入详情不存在"));requireApproved(a,v.getBusinessStatus(),v.getVersion(),request.version());requirePerson(v.getPersonId());if(mapper.lockResidence(v.getPersonId()).isPresent())throw conflict("该人员已存在当前户籍");if(mapper.countActiveMembership(v.getPersonId())>0)throw conflict("该人员已是其他家庭户有效成员");HouseholdSnapshot h=requireActiveHousehold(v.getToHouseholdId());materials.validateVerified(id);validateBatch(v);Residence r=new Residence();r.setPersonId(v.getPersonId());r.setHouseholdId(h.getHouseholdId());r.setRegisteredAddress(h.getAddress());r.setRegionCode(v.getToRegionCode());r.setRegisterTypeCode(v.getMigrationType().name());r.setRegisterDate(v.getInDate());r.setStartDate(v.getInDate());r.setCreatedBy(u.userId());mapper.insertResidence(r);hook.afterResidenceInserted();if(mapper.reactivateMember(h.getHouseholdId(),v.getPersonId(),v.getInDate())==0)mapper.insertMember(h.getHouseholdId(),v.getPersonId(),v.getInDate());mapper.updatePersonResidence(v.getPersonId(),"REGISTERED",h.getAddress());completeIn(a,v,u.userId());executionLog(a,u,http,"MIGRATION_IN_EXECUTE");}
 @Transactional public void executeOut(Long id,ExecuteRequest request,HttpServletRequest http){AuthenticatedUser u=CurrentUserContext.requireUser();BusinessApplication a=applications.require(id);assertExecution(a,u);MigrationOut v=mapper.lockOut(id).orElseThrow(()->notFound("迁出详情不存在"));requireApproved(a,v.getBusinessStatus(),v.getVersion(),request.version());Residence r=mapper.lockResidence(v.getPersonId()).orElseThrow(()->conflict("该人员没有当前有效户籍"));if(!r.getHouseholdId().equals(v.getFromHouseholdId()))throw conflict("当前户籍与迁出申请不一致");HouseholdSnapshot h=mapper.lockHousehold(r.getHouseholdId()).orElseThrow(()->notFound("家庭户不存在"));if(mapper.countActiveMembership(v.getPersonId())!=1)throw conflict("当前家庭成员关系无效");validateHeadExecution(v,h);materials.validateVerified(id);ResidenceArchive arc=archive(a,v,r,h,u.userId());mapper.insertArchive(arc);hook.afterArchiveInserted();if(mapper.deleteResidence(r.getResidenceId(),r.getVersion())==0)ApplicationService.conflict();hook.afterResidenceDeleted();if(mapper.leaveMember(h.getHouseholdId(),v.getPersonId(),v.getOutDate())==0)throw conflict("当前家庭成员关系无效");if(v.getPersonId().equals(h.getHeadPersonId())){if(h.getActiveMemberCount()>1){if(mapper.changeHead(h.getHouseholdId(),v.getPersonId(),v.getNewHeadPersonId())==0)ApplicationService.conflict();}else if(mapper.markHouseholdPending(h.getHouseholdId(),v.getPersonId())==0)ApplicationService.conflict();}mapper.updatePersonResidence(v.getPersonId(),"MIGRATED_OUT",null);String batch=v.getMigrationType()==MigrationType.IN_CITY_CROSS_DISTRICT?batchNo():null;completeOut(a,v,u.userId(),batch);executionLog(a,u,http,"MIGRATION_OUT_EXECUTE");}

 private void completeIn(BusinessApplication a,MigrationIn v,Long user){if(mapper.updateInStatus(a.getApplicationId(),MigrationBusinessStatus.APPROVED,MigrationBusinessStatus.COMPLETED,v.getVersion(),user)==0)ApplicationService.conflict();completeApplication(a);}
 private void completeOut(BusinessApplication a,MigrationOut v,Long user,String batch){if(mapper.updateOutStatus(a.getApplicationId(),MigrationBusinessStatus.APPROVED,MigrationBusinessStatus.COMPLETED,v.getVersion(),user,batch)==0)ApplicationService.conflict();completeApplication(a);}
 private void completeApplication(BusinessApplication a){if(applicationMapper.updateStatus(a.getApplicationId(),ApplicationStatus.APPROVED,ApplicationStatus.COMPLETED,a.getVersion())==0)ApplicationService.conflict();}
 private void executionLog(BusinessApplication a,AuthenticatedUser u,HttpServletRequest http,String type){logs.insert(ApprovalLog.of(null,a.getApplicationId(),ApprovalAction.EXECUTE,ApplicationStatus.APPROVED.name(),ApplicationStatus.COMPLETED.name(),u.userId(),"业务执行完成",audit.clientIp(http)));audit.recordTransactional(u.userId(),type,http);}
 private ResidenceArchive archive(BusinessApplication a,MigrationOut v,Residence r,HouseholdSnapshot h,Long user){ResidenceArchive x=new ResidenceArchive();x.setOriginalRegistrationId(r.getResidenceId());x.setPersonId(v.getPersonId());x.setHouseholdId(h.getHouseholdId());x.setApplicationId(a.getApplicationId());x.setMigrationOutId(v.getOutId());x.setArchiveType(v.getMigrationType()==MigrationType.IN_CITY_CROSS_DISTRICT?"CROSS_DISTRICT_TRANSFER_OUT":"MIGRATION_OUT");x.setArchiveReason(v.getReason());x.setRegisteredAddressSnapshot(r.getRegisteredAddress());x.setRegionCodeSnapshot(r.getRegionCode());x.setRegisterTypeCodeSnapshot(r.getRegisterTypeCode());x.setRegisterDateSnapshot(r.getRegisterDate());x.setStartDateSnapshot(r.getStartDate());x.setEndDateSnapshot(v.getOutDate());x.setOriginalStatus(r.getStatus());x.setArchivedBy(user);return x;}
 private void validateBatch(MigrationIn v){if(v.getMigrationType()!=MigrationType.IN_CITY_CROSS_DISTRICT)return;if(v.getTransferBatchNo()==null||v.getTransferBatchNo().isBlank())throw conflict("同市跨区迁入必须关联迁移批次");MigrationOut o=mapper.findCompletedBatch(v.getTransferBatchNo()).orElseThrow(()->conflict("迁移批次无效"));if(!o.getPersonId().equals(v.getPersonId())||o.getMigrationType()!=MigrationType.IN_CITY_CROSS_DISTRICT||!Objects.equals(o.getToRegionCode(),v.getToRegionCode())||mapper.countCompletedInBatch(v.getTransferBatchNo())>0)throw conflict("迁移批次不匹配或已使用");}
 private void validateInType(MigrationInRequest r){if(r.migrationType()==MigrationType.IN_CITY_CROSS_DISTRICT&&(r.transferBatchNo()==null||r.transferBatchNo().isBlank()))throw bad("同市跨区迁入必须填写 transferBatchNo");}
 private void validateHead(MigrationOutRequest r,HouseholdSnapshot h){if(r.personId().equals(h.getHeadPersonId())&&h.getActiveMemberCount()>1){if(r.newHeadPersonId()==null) return;if(r.newHeadPersonId().equals(r.personId())||!mapper.activeMembers(h.getHouseholdId()).contains(r.newHeadPersonId()))throw conflict("新户主必须是本户其他有效成员");}}
 private void validateHeadExecution(MigrationOut v,HouseholdSnapshot h){if(v.getPersonId().equals(h.getHeadPersonId())&&h.getActiveMemberCount()>1&&(v.getNewHeadPersonId()==null||v.getNewHeadPersonId().equals(v.getPersonId())||!mapper.activeMembers(h.getHouseholdId()).contains(v.getNewHeadPersonId())))throw conflict("户主迁出且仍有其他成员时必须指定有效新户主");}
 private void assertExecution(BusinessApplication a,AuthenticatedUser u){if(!u.permissions().contains("migration:execute"))throw new BusinessException(HttpStatus.FORBIDDEN,"无迁移执行权限");assertMigrationScope(a,u);}
 private void assertMigrationScope(BusinessApplication a,AuthenticatedUser u){if(a.getApplicantUserId().equals(u.userId())||u.dataScope()==DataScope.ALL)return;if(u.dataScope()==DataScope.DEPARTMENT&&Objects.equals(a.getApplicantDepartmentId(),u.departmentId()))return;if(u.dataScope()==DataScope.REGION&&Objects.equals(a.getApplicantRegionCode(),u.regionCode()))return;throw new BusinessException(HttpStatus.FORBIDDEN,"超出迁移数据范围");}
 private void requireApproved(BusinessApplication a,MigrationBusinessStatus s,int actual,int expected){if(a.getStatus()!=ApplicationStatus.APPROVED||s!=MigrationBusinessStatus.APPROVED)throw conflict("申请尚未批准或已执行");if(actual!=expected)ApplicationService.conflict();}
 private HouseholdSnapshot requireActiveHousehold(Long id){HouseholdSnapshot h=mapper.findHousehold(id).orElseThrow(()->notFound("家庭户不存在"));if(!"ACTIVE".equals(h.getStatus()))throw conflict("目标家庭户不是有效状态");return h;}
 private void requireDraft(BusinessApplication a){if(a.getStatus()!=ApplicationStatus.DRAFT)throw conflict("只有草稿可以修改");}
 private void requirePerson(Long id){com.wjx871.population.person.Person p=persons.selectById(id).orElseThrow(()->notFound("人员不存在"));if("CANCELLED".equals(p.getCurrentStatusCode())||"DECEASED".equals(p.getCurrentStatusCode()))throw conflict("已注销人员不能办理户籍迁移");}
 private ApplicationRequest appRequest(BusinessType t,String title,Long person,Long household,String reason,String remark,Integer version){return new ApplicationRequest(t,title,person,household,reason,remark,version);}
 private MigrationIn inValue(Long id,MigrationInRequest r){MigrationIn v=new MigrationIn();v.setApplicationId(id);v.setPersonId(r.personId());v.setMigrationType(r.migrationType());v.setFromRegionCode(r.fromRegionCode());v.setFromAddress(r.fromAddress());v.setToRegionCode(r.toRegionCode());v.setToHouseholdId(r.toHouseholdId());v.setInDate(r.inDate());v.setReason(r.reason());v.setTransferBatchNo(r.transferBatchNo());v.setBusinessStatus(MigrationBusinessStatus.DRAFT);v.setVersion(0);return v;}
 private MigrationOut outValue(Long id,MigrationOutRequest q,Residence r){MigrationOut v=new MigrationOut();v.setApplicationId(id);v.setPersonId(q.personId());v.setMigrationType(q.migrationType());v.setFromRegionCode(r.getRegionCode());v.setFromHouseholdId(r.getHouseholdId());v.setFromAddressSnapshot(r.getRegisteredAddress());v.setToRegionCode(q.toRegionCode());v.setToAddress(q.toAddress());v.setOutDate(q.outDate());v.setReason(q.reason());v.setNewHeadPersonId(q.newHeadPersonId());v.setBusinessStatus(MigrationBusinessStatus.DRAFT);v.setVersion(0);return v;}
 private String batchNo(){return "TR-"+LocalDate.now().format(DateTimeFormatter.BASIC_ISO_DATE)+"-"+UUID.randomUUID().toString().substring(0,6).toUpperCase();}
 private BusinessException conflict(String m){return new BusinessException(HttpStatus.CONFLICT,m);}private BusinessException bad(String m){return new BusinessException(HttpStatus.BAD_REQUEST,m);}private BusinessException notFound(String m){return new BusinessException(HttpStatus.NOT_FOUND,m);}
}
