package com.wjx871.population.migration;
import com.wjx871.population.common.BusinessException; import com.wjx871.population.security.*; import java.time.LocalDateTime; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @RequiredArgsConstructor public class ResidenceArchiveService {
 private final MigrationMapper mapper;
 @Transactional(readOnly=true) public Page<ArchiveView> search(String person,String identity,String household,String type,String region,LocalDateTime from,LocalDateTime to,Pageable p){AuthenticatedUser u=CurrentUserContext.requireUser();String scoped=scopeRegion(u,region);boolean full=u.permissions().contains("migration:execute")||u.permissions().contains("system:user:manage");return new PageImpl<>(mapper.searchArchives(person,identity,household,type,scoped,from,to,p.getPageSize(),p.getOffset()).stream().map(a->ArchiveView.from(a,full)).toList(),p,mapper.countArchives(person,identity,household,type,scoped,from,to));}
 @Transactional(readOnly=true) public ArchiveView get(Long id){AuthenticatedUser u=CurrentUserContext.requireUser();ResidenceArchive a=mapper.findArchive(id).orElseThrow(()->new BusinessException(HttpStatus.NOT_FOUND,"归档不存在"));if(u.dataScope()!=DataScope.ALL&&u.dataScope()!=DataScope.SELF&&!sameRegion(u.regionCode(),a.getRegionCodeSnapshot()))throw new BusinessException(HttpStatus.FORBIDDEN,"超出数据范围");return ArchiveView.from(a,u.permissions().contains("migration:execute")||u.permissions().contains("system:user:manage"));}
 private boolean sameRegion(String a,String b){return a!=null&&b!=null&&a.length()>=2&&b.length()>=2&&a.substring(0,2).equals(b.substring(0,2));}
 private String scopeRegion(AuthenticatedUser u,String requested){if(u.dataScope()==DataScope.ALL)return requested;if(u.dataScope()==DataScope.SELF)throw new BusinessException(HttpStatus.FORBIDDEN,"SELF 数据范围不能查询迁移归档");if(requested!=null&&!sameRegion(requested,u.regionCode()))throw new BusinessException(HttpStatus.FORBIDDEN,"超出数据范围");return u.regionCode();}
}
