package com.wjx871.population.approval;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

import com.fasterxml.jackson.databind.*; import java.nio.charset.StandardCharsets; import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.MediaType; import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.mock.web.MockMultipartFile; import org.springframework.test.web.servlet.MockMvc;

@SpringBootTest @AutoConfigureMockMvc
class Phase02ApprovalIntegrationTest {
 @Autowired MockMvc mvc; @Autowired ObjectMapper json; @Autowired JdbcTemplate jdbc;
 @BeforeEach void clean(){jdbc.update("DELETE FROM sys_approval_log");jdbc.update("DELETE FROM sys_approval_request");jdbc.update("DELETE FROM application_material");jdbc.update("DELETE FROM business_application");jdbc.update("DELETE FROM operation_log");}

 @Test void l2CreatesDraftAndL1CannotCreate() throws Exception {String token=token("population");mvc.perform(post("/api/applications").header("Authorization",bearer(token)).contentType(MediaType.APPLICATION_JSON).content(createJson())).andExpect(status().isCreated()).andExpect(jsonPath("$.data.status").value("DRAFT")).andExpect(jsonPath("$.data.applicationNo").value(org.hamcrest.Matchers.startsWith("APP-")));mvc.perform(get("/api/applications").header("Authorization",bearer(token))).andExpect(status().isOk()).andExpect(jsonPath("$.data.content.length()").value(1));mvc.perform(post("/api/applications").header("Authorization",bearer(token("viewer"))).contentType(MediaType.APPLICATION_JSON).content(createJson())).andExpect(status().isForbidden());}
 @Test void nonApplicantCannotModifyDraft() throws Exception {long id=create("population");mvc.perform(put("/api/applications/"+id).header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content(updateJson(0))).andExpect(status().isForbidden());}
 @Test void nonDraftCannotBeModified() throws Exception {long id=create("population");upload(id,"proof.pdf","application/pdf",true,"x");submit(id,"population");mvc.perform(put("/api/applications/"+id).header("Authorization",bearer(token("population"))).contentType(MediaType.APPLICATION_JSON).content(updateJson(1))).andExpect(status().isConflict());}
 @Test void legalUploadStoresHashAndTraversalNameIsSanitized() throws Exception {long id=create("population");String body=upload(id,"../../evil.pdf","application/pdf",true,"%PDF-test");JsonNode data=json.readTree(body).path("data");assertThat(data.path("fileSha256").asText()).hasSize(64);assertThat(data.path("originalFilename").asText()).isEqualTo("evil.pdf");String stored=jdbc.queryForObject("SELECT stored_filename FROM application_material WHERE material_id=?",String.class,data.path("materialId").asLong());assertThat(stored).doesNotContain("..").doesNotContain("/").doesNotContain("\\");}
 @Test void illegalExtensionAndOversizedFileAreRejected() throws Exception {long id=create("population");mvc.perform(multipart("/api/applications/"+id+"/materials").file(file("bad.exe","application/pdf",new byte[]{1})).param("materialType","PROOF").param("materialName","bad").header("Authorization",bearer(token("population")))).andExpect(status().isBadRequest());byte[] huge=new byte[1024*1024+1];mvc.perform(multipart("/api/applications/"+id+"/materials").file(file("large.pdf","application/pdf",huge)).param("materialType","PROOF").param("materialName","large").header("Authorization",bearer(token("population")))).andExpect(status().isBadRequest());}
 @Test void draftMaterialDeleteRemovesMetadataAndPhysicalFile() throws Exception {long id=create("population");long material=uploadId(id,"delete.pdf",true);String path=jdbc.queryForObject("SELECT storage_path FROM application_material WHERE material_id=?",String.class,material);assertThat(java.nio.file.Files.exists(java.nio.file.Path.of(path))).isTrue();mvc.perform(delete("/api/materials/"+material).header("Authorization",bearer(token("population")))).andExpect(status().isOk());assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM application_material WHERE material_id=?",Integer.class,material)).isZero();assertThat(java.nio.file.Files.exists(java.nio.file.Path.of(path))).isFalse();}
 @Test void missingRequiredMaterialCannotSubmit() throws Exception {long id=create("population");mvc.perform(post("/api/applications/"+id+"/submit").header("Authorization",bearer(token("population")))).andExpect(status().isConflict());}
 @Test void submitCreatesPendingRequestLogsAndOperationLog() throws Exception {long id=create("population");upload(id,"proof.pdf","application/pdf",true,"x");submit(id,"population");assertThat(statusOf(id)).isEqualTo("UNDER_REVIEW");assertThat(jdbc.queryForObject("SELECT status FROM sys_approval_request WHERE application_id=?",String.class,id)).isEqualTo("PENDING");assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM sys_approval_log WHERE application_id=? AND action='SUBMIT'",Integer.class,id)).isEqualTo(1);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM operation_log WHERE operation_type='APPLICATION_SUBMIT'",Integer.class)).isEqualTo(1);}
 @Test void approverSeesOwnRegionButOtherRegionDoesNot() throws Exception {long id=create("population");upload(id,"proof.pdf","application/pdf",true,"x");submit(id,"population");mvc.perform(get("/api/approvals/pending").header("Authorization",bearer(token("approver")))).andExpect(status().isOk()).andExpect(jsonPath("$.data.length()").value(1));mvc.perform(get("/api/approvals/pending").header("Authorization",bearer(token("approver-other")))).andExpect(status().isOk()).andExpect(jsonPath("$.data.length()").value(0));}
 @Test void applicantCannotApproveOwnApplicationEvenAsAdmin() throws Exception {long id=create("admin");upload(id,"proof.pdf","application/pdf",true,"x","admin");submit(id,"admin");long approval=approvalId(id);mvc.perform(post("/api/approvals/"+approval+"/approve").header("Authorization",bearer(token("admin"))).contentType(MediaType.APPLICATION_JSON).content("{\"comment\":\"ok\",\"version\":0}")).andExpect(status().isForbidden());}
 @Test void unverifiedRequiredMaterialBlocksApprovalThenVerificationAllowsIt() throws Exception {long id=create("population");long material=uploadId(id,"proof.pdf",true);submit(id,"population");long approval=approvalId(id);approve(approval,0,"approver",409);verify(material,"VERIFIED","approver");approve(approval,0,"approver",200);assertThat(statusOf(id)).isEqualTo("APPROVED");assertThat(jdbc.queryForObject("SELECT status FROM sys_approval_request WHERE approval_id=?",String.class,approval)).isEqualTo("APPROVED");mvc.perform(get("/api/approvals/processed").header("Authorization",bearer(token("approver")))).andExpect(status().isOk()).andExpect(jsonPath("$.data.length()").value(1));}
 @Test void rejectionRequiresCommentAndProducesConsistentState() throws Exception {long id=create("population");uploadId(id,"proof.pdf",true);submit(id,"population");long approval=approvalId(id);mvc.perform(post("/api/approvals/"+approval+"/reject").header("Authorization",bearer(token("approver"))).contentType(MediaType.APPLICATION_JSON).content("{\"comment\":\"\",\"version\":0}")).andExpect(status().isBadRequest());mvc.perform(post("/api/approvals/"+approval+"/reject").header("Authorization",bearer(token("approver"))).contentType(MediaType.APPLICATION_JSON).content("{\"comment\":\"材料不完整\",\"version\":0}")).andExpect(status().isOk());assertThat(statusOf(id)).isEqualTo("REJECTED");assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM operation_log WHERE operation_type='APPROVAL_REJECT'",Integer.class)).isEqualTo(1);}
 @Test void applicantCanWithdrawPendingButNotProcessedApproval() throws Exception {long first=create("population");uploadId(first,"a.pdf",true);submit(first,"population");withdraw(first,200);assertThat(statusOf(first)).isEqualTo("WITHDRAWN");assertThat(jdbc.queryForObject("SELECT status FROM sys_approval_request WHERE application_id=?",String.class,first)).isEqualTo("CANCELLED");long second=create("population");long material=uploadId(second,"b.pdf",true);submit(second,"population");verify(material,"VERIFIED","approver");approve(approvalId(second),0,"approver",200);withdraw(second,409);}
 @Test void duplicateApprovalAndOptimisticLockOnlyAllowOneSuccessLog() throws Exception {long id=create("population");long material=uploadId(id,"a.pdf",true);submit(id,"population");verify(material,"VERIFIED","approver");long approval=approvalId(id);approve(approval,99,"approver",409);approve(approval,0,"approver",200);approve(approval,0,"approver",409);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM sys_approval_log WHERE approval_id=? AND action='APPROVE'",Integer.class,approval)).isEqualTo(1);}
 @Test void approvalLogsAreReadOnlyAndDetailContainsMaterials() throws Exception {long id=create("population");uploadId(id,"a.pdf",true);submit(id,"population");long approval=approvalId(id);mvc.perform(get("/api/approvals/"+approval).header("Authorization",bearer(token("approver")))).andExpect(status().isOk()).andExpect(jsonPath("$.data.materials.length()").value(1)).andExpect(jsonPath("$.data.logs.length()").value(2));mvc.perform(put("/api/applications/"+id+"/approval-logs").header("Authorization",bearer(token("admin")))).andExpect(status().isMethodNotAllowed());}
 @Test void genericEntryRejectsMigrationIn() throws Exception { assertSpecializedRejected("MIGRATION_IN"); }
 @Test void genericEntryRejectsMigrationOut() throws Exception { assertSpecializedRejected("MIGRATION_OUT"); }
 @Test void genericEntryRejectsPersonCancellation() throws Exception { assertSpecializedRejected("PERSON_CANCELLATION"); }
 @Test void genericEntryRejectsHouseholdCancellation() throws Exception { assertSpecializedRejected("HOUSEHOLD_CANCELLATION"); }
 @Test void illegalPaginationReturnsBadRequest() throws Exception {String authorization=bearer(token("population"));mvc.perform(get("/api/applications?page=-1&size=5").header("Authorization",authorization)).andExpect(status().isBadRequest()).andExpect(jsonPath("$.code").value(400));mvc.perform(get("/api/applications?page=0&size=0").header("Authorization",authorization)).andExpect(status().isBadRequest()).andExpect(jsonPath("$.code").value(400));mvc.perform(get("/api/applications?page=not-a-number&size=5").header("Authorization",authorization)).andExpect(status().isBadRequest()).andExpect(jsonPath("$.code").value(400));}

 private void assertSpecializedRejected(String type)throws Exception{mvc.perform(post("/api/applications").header("Authorization",bearer(token("population"))).contentType(MediaType.APPLICATION_JSON).content("{\"businessType\":\""+type+"\",\"title\":\"非法通用入口\",\"reason\":\"测试\"}")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.message").value("该业务必须通过对应的专业业务入口创建"));}
 private long create(String user)throws Exception{String b=mvc.perform(post("/api/applications").header("Authorization",bearer(token(user))).contentType(MediaType.APPLICATION_JSON).content(createJson())).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();return json.readTree(b).path("data").path("applicationId").asLong();}
 private String upload(long id,String filename,String type,boolean required,String content)throws Exception{return upload(id,filename,type,required,content,"population");}
 private String upload(long id,String filename,String type,boolean required,String content,String user)throws Exception{return mvc.perform(multipart("/api/applications/"+id+"/materials").file(file(filename,type,content.getBytes(StandardCharsets.UTF_8))).param("materialType","PROOF").param("materialName","证明材料").param("requiredFlag",String.valueOf(required)).header("Authorization",bearer(token(user)))).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();}
 private long uploadId(long id,String filename,boolean required)throws Exception{return json.readTree(upload(id,filename,"application/pdf",required,"%PDF")).path("data").path("materialId").asLong();}
 private MockMultipartFile file(String n,String type,byte[] data){return new MockMultipartFile("file",n,type,data);}
 private void submit(long id,String user)throws Exception{mvc.perform(post("/api/applications/"+id+"/submit").header("Authorization",bearer(token(user)))).andExpect(status().isOk());}
 private void withdraw(long id,int expected)throws Exception{mvc.perform(post("/api/applications/"+id+"/withdraw").header("Authorization",bearer(token("population")))).andExpect(status().is(expected));}
 private void verify(long material,String result,String user)throws Exception{mvc.perform(post("/api/materials/"+material+"/verify").header("Authorization",bearer(token(user))).contentType(MediaType.APPLICATION_JSON).content("{\"result\":\""+result+"\",\"comment\":\"有效\"}")).andExpect(status().isOk());}
 private void approve(long id,int version,String user,int expected)throws Exception{mvc.perform(post("/api/approvals/"+id+"/approve").header("Authorization",bearer(token(user))).contentType(MediaType.APPLICATION_JSON).content("{\"comment\":\"同意\",\"version\":"+version+"}")).andExpect(status().is(expected));}
 private long approvalId(long app){return jdbc.queryForObject("SELECT approval_id FROM sys_approval_request WHERE application_id=?",Long.class,app);} private String statusOf(long id){return jdbc.queryForObject("SELECT status FROM business_application WHERE application_id=?",String.class,id);}
 private String token(String user)throws Exception{String b=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"username\":\""+user+"\",\"password\":\"123456\"}")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();return json.readTree(b).path("data").path("token").asText();}
 private String bearer(String t){return "Bearer "+t;} private String createJson(){return "{\"businessType\":\"GENERAL_SERVICE\",\"title\":\"通用业务申请\",\"reason\":\"课程申请\"}";} private String updateJson(int v){return "{\"businessType\":\"GENERAL_SERVICE\",\"title\":\"更新申请\",\"reason\":\"更新理由\",\"version\":"+v+"}";}
}
