const permitService = require('../../../services/permit')
const applicationService = require('../../../services/application')
const adapter = require('../../../adapters/mobile-business')
const { guard, can } = require('../../../utils/permission')
const { messageOf } = require('../../../utils/error')
const { cleanQueryParams } = require('../../../utils/request-params')

const MATERIALS = [{ type: 'CURRENT_RESIDENCE_PERMIT', name: '当前居住证' }, { type: 'CONTINUED_RESIDENCE_PROOF', name: '持续居住证明' }]
const BASIS_OPTIONS = [{ label: '就业', value: 'EMPLOYMENT' }, { label: '就学', value: 'STUDY' }, { label: '经商', value: 'BUSINESS' }, { label: '家庭团聚', value: 'FAMILY' }, { label: '其他', value: 'OTHER' }]

Page({
  data: { step: 1, permits: [], selected: null, title: '居住证签注申请', reason: '', remark: '', basisIndex: 0, basisOptions: BASIS_OPTIONS, applicationId: null, applicationNo: '', materials: MATERIALS.map((item) => Object.assign({ uploaded: false, uploading: false }, item)), loading: true, error: '', creating: false, submitting: false },
  onLoad(options) { if (this._initialLoadStarted) return; this._initialLoadStarted = true; const permitId = options && options.permitId; if (!guard('residence-permit:apply')) return this.setData({ loading: false, error: '当前账号无权发起居住证签注申请' }); if (!permitId && !can(getApp().globalData.user, 'residence-permit:expiry:view')) return this.setData({ loading: false, error: '当前账号无权查看可签注证件' }); this._authorized = true; this._permitId = permitId; return this.loadPermits() },
  async loadPermits() { if (!this._authorized || this._loading) return; this._loading = true; this.setData({ loading: true, error: '' }); try { let permits; if (this._permitId) permits = [await permitService.detail(this._permitId)]; else permits = await permitService.expiring(30); permits = (Array.isArray(permits) ? permits : []).map(adapter.permit).filter((item) => item.rawStatus === 'ACTIVE'); this.setData({ permits, selected: permits.length === 1 ? permits[0] : null }) } catch (error) { this.setData({ error: messageOf(error) }) } finally { this._loading = false; this.setData({ loading: false }) } },
  select(e) { if (!this.data.applicationId) this.setData({ selected: this.data.permits.find((item) => String(item.permitId) === String(e.currentTarget.dataset.id)) || null }) },
  inputTitle(e) { this.setData({ title: e.detail.value }) }, inputReason(e) { this.setData({ reason: e.detail.value }) }, inputRemark(e) { this.setData({ remark: e.detail.value }) }, changeBasis(e) { this.setData({ basisIndex: Number(e.detail.value) }) },
  next() { if (!this.data.selected) return wx.showToast({ title: '请选择需要签注的居住证', icon: 'none' }); this.setData({ step: 2 }) },
  previous() { if (!this.data.applicationId) this.setData({ step: 1 }) },
  async createApplication() { if (this.data.creating || this.data.applicationId) return; const title = this.data.title.trim(), reason = this.data.reason.trim(); if (!title || !reason) return wx.showToast({ title: '请填写申请标题和原因', icon: 'none' }); this.setData({ creating: true }); try { const payload = cleanQueryParams({ title, reason, remark: this.data.remark.trim(), residenceBasisCode: this.data.basisOptions[this.data.basisIndex].value }); const result = await permitService.createEndorsement(this.data.selected.permitId, payload); this.setData({ applicationId: result.applicationId, applicationNo: result.applicationNo, step: 3 }); wx.showToast({ title: '草稿已创建', icon: 'success' }) } catch (error) { wx.showToast({ title: messageOf(error), icon: 'none' }) } finally { this.setData({ creating: false }) } },
  chooseMaterial(e) { const index = Number(e.currentTarget.dataset.index); if (this.data.materials[index].uploading) return; wx.chooseMessageFile({ count: 1, type: 'file', success: (result) => this.uploadMaterial(index, result.tempFiles[0]) }) },
  async uploadMaterial(index, file) { const materials = this.data.materials.slice(); materials[index] = Object.assign({}, materials[index], { uploading: true }); this.setData({ materials }); try { await permitService.uploadMaterial(this.data.applicationId, file.path, materials[index].type, materials[index].name); materials[index] = Object.assign({}, materials[index], { uploaded: true, uploading: false, filename: file.name }); this.setData({ materials }); wx.showToast({ title: '材料已上传', icon: 'success' }) } catch (error) { materials[index] = Object.assign({}, materials[index], { uploading: false }); this.setData({ materials }); wx.showToast({ title: messageOf(error), icon: 'none' }) } },
  async submit() { if (this.data.submitting || !this.data.applicationId) return; if (!this.data.materials.every((item) => item.uploaded)) return wx.showToast({ title: '请先上传全部必需材料', icon: 'none' }); this.setData({ submitting: true }); try { await applicationService.submit(this.data.applicationId); wx.showToast({ title: '申请已提交', icon: 'success' }); setTimeout(() => wx.redirectTo({ url: `/pages/applications/detail/index?id=${this.data.applicationId}` }), 500) } catch (error) { wx.showToast({ title: messageOf(error), icon: 'none' }); if (error.statusCode === 409) this.openApplication() } finally { this.setData({ submitting: false }) } },
  openApplication() { if (this.data.applicationId) wx.redirectTo({ url: `/pages/applications/detail/index?id=${this.data.applicationId}` }) }
})
