package com.wjx871.population.person;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*; import com.fasterxml.jackson.databind.ObjectMapper; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.MediaType; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.test.web.servlet.MockMvc;
@SpringBootTest @AutoConfigureMockMvc class Phase08PersonIdentityIntegrationTest {@Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired JdbcTemplate jdbc;
@BeforeEach void clean(){jdbc.update("DELETE FROM person WHERE id_card='110105196001020047'");}
@Test void createNormalizesAndDerivesBirthDate()throws Exception{String b=mvc.perform(post("/api/persons").header("Authorization",bearer()).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"严格校验\",\"gender\":\"F\",\"idCard\":\"110105196001020047\",\"status\":\"正常\"}")).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();long id=json.readTree(b).path("data").path("personId").asLong();org.assertj.core.api.Assertions.assertThat(jdbc.queryForObject("SELECT id_card FROM person WHERE person_id=?",String.class,id)).isEqualTo("110105196001020047");org.assertj.core.api.Assertions.assertThat(jdbc.queryForObject("SELECT birth_date FROM person WHERE person_id=?",java.sql.Date.class,id).toLocalDate()).isEqualTo(java.time.LocalDate.of(1960,1,2));}
@Test void duplicateIdentityConflicts()throws Exception{createFemale();mvc.perform(post("/api/persons").header("Authorization",bearer()).contentType(MediaType.APPLICATION_JSON).content(female())).andExpect(status().isConflict());}
@Test void updateAlsoValidatesMismatch()throws Exception{long id=createFemale();mvc.perform(put("/api/persons/"+id).header("Authorization",bearer()).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"错误\",\"gender\":\"M\",\"idCard\":\"110105196001020047\",\"birthDate\":\"1960-01-02\",\"status\":\"正常\"}")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.message").value(org.hamcrest.Matchers.containsString("性别")));}
@Test void invalidChecksumReturnsSpecific400()throws Exception{mvc.perform(post("/api/persons").header("Authorization",bearer()).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"错误\",\"gender\":\"M\",\"idCard\":\"110105194912310010\"}")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.message").value(org.hamcrest.Matchers.containsString("校验位")));}
@Test void ordinaryDeleteIsNotAvailable()throws Exception{mvc.perform(delete("/api/persons/999").header("Authorization",bearer())).andExpect(status().isMethodNotAllowed());}
private long createFemale()throws Exception{String b=mvc.perform(post("/api/persons").header("Authorization",bearer()).contentType(MediaType.APPLICATION_JSON).content(female())).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();return json.readTree(b).path("data").path("personId").asLong();}private String female(){return "{\"name\":\"女性\",\"gender\":\"F\",\"idCard\":\"110105196001020047\",\"birthDate\":\"1960-01-02\",\"status\":\"正常\"}";}private String bearer()throws Exception{String b=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"username\":\"admin\",\"password\":\"123456\"}")).andReturn().getResponse().getContentAsString();return "Bearer "+json.readTree(b).path("data").path("token").asText();}}
