package com.wjx871.population.export;import com.wjx871.population.common.ApiResponse;import jakarta.servlet.http.HttpServletRequest;import jakarta.validation.Valid;import java.nio.charset.StandardCharsets;import lombok.RequiredArgsConstructor;import org.springframework.data.domain.*;import org.springframework.http.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/exports") @RequiredArgsConstructor public class ExportController {private final ExportService service;
@PostMapping("/normal")@ResponseStatus(HttpStatus.CREATED)@PreAuthorize("hasAuthority('data:export:normal')")public ApiResponse<ExportLogView> normal(@Valid@RequestBody NormalExportRequest q,HttpServletRequest h){return ApiResponse.created(service.normal(q,h));}
@PostMapping("/sensitive/applications")@ResponseStatus(HttpStatus.CREATED)@PreAuthorize("hasAuthority('data:export:sensitive:apply')")public ApiResponse<Long> sensitive(@Valid@RequestBody SensitiveExportRequest q,HttpServletRequest h){return ApiResponse.created(service.createSensitive(q,h));}
@GetMapping("/applications/{id}")@PreAuthorize("hasAnyAuthority('data:export:sensitive:apply','data:export:sensitive:execute','approval:view')")public ApiResponse<ExportApplicationView> application(@PathVariable Long id){return ApiResponse.ok(service.application(id));}
@PostMapping("/sensitive/applications/{id}/execute")@PreAuthorize("hasAuthority('data:export:sensitive:execute')")public ApiResponse<ExportLogView> execute(@PathVariable Long id,@Valid@RequestBody ExportVersionRequest q,HttpServletRequest h){return ApiResponse.ok(service.executeSensitive(id,q.version(),h));}
@GetMapping@PreAuthorize("hasAuthority('data:export:log:view')")public ApiResponse<Page<ExportLogView>> search(@RequestParam(required=false)String exportNo,@RequestParam(required=false)String module,@RequestParam(required=false)String exportType,@RequestParam(required=false)String status,Pageable p){return ApiResponse.ok(service.search(exportNo,module,exportType,status,p));}
@GetMapping("/{id}")@PreAuthorize("hasAuthority('data:export:log:view')")public ApiResponse<ExportLogView> detail(@PathVariable Long id){return ApiResponse.ok(service.detail(id));}
@GetMapping("/{id}/download")@PreAuthorize("hasAnyAuthority('data:export:normal','data:export:sensitive:download')")public ResponseEntity<org.springframework.core.io.Resource> download(@PathVariable Long id,HttpServletRequest h){var d=service.download(id,h);return ResponseEntity.ok().contentType(MediaType.parseMediaType(d.contentType())).header(HttpHeaders.CONTENT_DISPOSITION,ContentDisposition.attachment().filename(d.filename(),StandardCharsets.UTF_8).build().toString()).body(d.resource());}}
