package com.wjx871.population.cancellation;
import static org.assertj.core.api.Assertions.assertThat;import static org.mockito.Mockito.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;import com.fasterxml.jackson.databind.*;import java.util.*;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.test.mock.mockito.MockBean;import org.springframework.http.MediaType;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.test.web.servlet.MockMvc;
@SpringBootTest @AutoConfigureMockMvc class Phase04CancellationIntegrationTest {private org.springframework.test.web.servlet.result.StatusResultMatchers status(){return org.springframework.test.web.servlet.result.MockMvcResultMatchers.status();}@Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired JdbcTemplate jdbc;@MockBean CancellationTransactionHook hook;
@BeforeEach void setup(){reset(hook);jdbc.update("DELETE FROM household_archive");jdbc.update("DELETE FROM cancellation_record");jdbc.update("DELETE FROM residence_archive");jdbc.update("DELETE FROM migration_in");jdbc.update("DELETE FROM migration_out");jdbc.update("DELETE FROM residence");jdbc.update("DELETE FROM household_member");jdbc.update("DELETE FROM sys_approval_log");jdbc.update("DELETE FROM sys_approval_request");jdbc.update("DELETE FROM application_material");jdbc.update("DELETE FROM business_application");jdbc.update("DELETE FROM operation_log");jdbc.update("DELETE FROM household WHERE household_id>=201");jdbc.update("DELETE FROM person WHERE person_id>=201");jdbc.update("INSERT INTO person(person_id,name,gender,id_card,current_address,status,current_status_code) VALUES(201,'张甲','1','110101199001010011','旧址','正常','REGISTERED'),(202,'李乙','2','110101199202020022','旧址','正常','REGISTERED'),(203,'王丙','1','110101199303030033',NULL,'正常','MIGRATED_OUT')");jdbc.update("INSERT INTO household(household_id,household_no,head_person_id,address,region_code,household_type,establish_date,status,version) VALUES(201,'HC-201',201,'北京市旧址','110101','FAMILY',DATE '2020-01-01','ACTIVE',0),(202,'HC-202',NULL,'北京市空户','110101','FAMILY',DATE '2020-01-01','PENDING_CANCELLATION',0)");jdbc.update("INSERT INTO household_member(household_id,person_id,relationship,join_date,status,version) VALUES(201,201,'HEAD',DATE '2020-01-01','ACTIVE',0),(201,202,'CHILD',DATE '2020-01-01','ACTIVE',0)");jdbc.update("INSERT INTO residence(person_id,household_id,registered_address,region_code,register_type_code,register_date,start_date,status,created_by,version) VALUES(201,201,'北京市旧址','110101','BIRTH',DATE '2020-01-01',DATE '2020-01-01','ACTIVE',6,0),(202,201,'北京市旧址','110101','BIRTH',DATE '2020-01-01',DATE '2020-01-01','ACTIVE',6,0)");}
@Test void l2CreatesPersonDraftAndL1Cannot()throws Exception{createPerson("population",201,202L,201);createPerson("viewer",201,202L,403);}
@Test void draftCreatesGenericAndCancellationRecord()throws Exception{long id=createPerson("population",201,202L,201);assertThat(count("business_application","application_id",id)).isOne();assertThat(jdbc.queryForObject("SELECT business_status FROM cancellation_record WHERE application_id=?",String.class,id)).isEqualTo("DRAFT");}
@Test void backendReadsSourceHouseholdAndRejectsDuplicateOpenRequest()throws Exception{long id=createPerson("population",201,202L,201);assertThat(jdbc.queryForObject("SELECT source_household_id FROM cancellation_record WHERE application_id=?",Long.class,id)).isEqualTo(201);createPerson("population",201,202L,409);}
@Test void personCancellationDetailUsesReadOnlyResidenceQuery()throws Exception{long id=createPerson("population",201,202L,201);mvc.perform(get("/api/cancellations/applications/"+id).header("Authorization",bearer(token("population")))).andExpect(status().isOk()).andExpect(jsonPath("$.data.currentResidence.personId").value(201)).andExpect(jsonPath("$.data.currentResidence.status").value("ACTIVE"));}
@Test void headCancellationRequiresValidNewHead()throws Exception{createPerson("population",201,null,409);createPerson("population",201,999L,409);}
@Test void missingReasonMaterialBlocksSubmit()throws Exception{long id=createPerson("population",201,202L,201);material(id,"APPLICANT_IDENTITY_PROOF");material(id,"HOUSEHOLD_BOOK");submit(id,"population",409);}
@Test void approvalDoesNotAutomaticallyCancelPerson()throws Exception{long id=approvedPerson("DEATH",202L);assertThat(status(id)).isEqualTo("APPROVED");assertThat(jdbc.queryForObject("SELECT current_status_code FROM person WHERE person_id=201",String.class)).isEqualTo("REGISTERED");assertThat(count("residence","person_id",201)).isOne();}
@Test void deathExecutionArchivesAndKeepsPersonMaster()throws Exception{long id=approvedPerson("DEATH",202L);executePerson(id,200);assertThat(jdbc.queryForObject("SELECT current_status_code FROM person WHERE person_id=201",String.class)).isEqualTo("DECEASED");assertThat(count("person","person_id",201)).isOne();assertThat(count("residence","person_id",201)).isZero();assertThat(jdbc.queryForObject("SELECT archive_type FROM residence_archive WHERE application_id=?",String.class,id)).isEqualTo("DEATH_CANCELLATION");assertThat(jdbc.queryForObject("SELECT status FROM household_member WHERE person_id=201",String.class)).isEqualTo("CANCELLED");assertThat(jdbc.queryForObject("SELECT head_person_id FROM household WHERE household_id=201",Long.class)).isEqualTo(202);assertThat(status(id)).isEqualTo("COMPLETED");executePerson(id,409);}
@Test void ordinaryCancellationUsesCancelledStatus()throws Exception{long id=approvedPerson("SETTLED_ABROAD",202L);executePerson(id,200);assertThat(jdbc.queryForObject("SELECT current_status_code FROM person WHERE person_id=201",String.class)).isEqualTo("CANCELLED");}
@Test void lastMemberCancellationMarksHouseholdPendingAndClearsHead()throws Exception{jdbc.update("DELETE FROM residence WHERE person_id=202");jdbc.update("UPDATE household_member SET status='LEFT' WHERE person_id=202");long id=approvedPerson("DEATH",null);executePerson(id,200);assertThat(jdbc.queryForObject("SELECT status FROM household WHERE household_id=201",String.class)).isEqualTo("PENDING_CANCELLATION");assertThat(jdbc.queryForObject("SELECT head_person_id FROM household WHERE household_id=201",Long.class)).isNull();}
@Test void activeHouseholdCannotRequestCancellation()throws Exception{createHousehold(201,409);}
@Test void validHouseholdCancellationArchivesWithoutDeletingMaster()throws Exception{long id=approvedHousehold();executeHousehold(id,200);assertThat(jdbc.queryForObject("SELECT status FROM household WHERE household_id=202",String.class)).isEqualTo("CANCELLED");assertThat(count("household","household_id",202)).isOne();assertThat(count("household_archive","application_id",id)).isOne();executeHousehold(id,409);}
@Test void householdWithResidenceCannotExecuteCancellation()throws Exception{long id=approvedHousehold();jdbc.update("INSERT INTO household_member(household_id,person_id,relationship,join_date,status,version) VALUES(202,203,'MEMBER',DATE '2020-01-01','LEFT',0)");jdbc.update("INSERT INTO residence(person_id,household_id,registered_address,region_code,register_type_code,register_date,start_date,status,created_by,version) VALUES(203,202,'占用户籍','110101','OTHER',DATE '2020-01-01',DATE '2020-01-01','ACTIVE',6,0)");executeHousehold(id,409);assertThat(count("household_archive","application_id",id)).isZero();}
@Test void personRollbackAfterArchiveRestoresEverything()throws Exception{long id=approvedPerson("DEATH",202L);doThrow(new IllegalStateException("rollback")).when(hook).afterResidenceArchive();executePerson(id,500);assertPersonRollback(id);}
@Test void personRollbackAfterResidenceDeleteRestoresEverything()throws Exception{long id=approvedPerson("DEATH",202L);doThrow(new IllegalStateException("rollback")).when(hook).afterResidenceDelete();executePerson(id,500);assertPersonRollback(id);}
@Test void personRollbackAfterMemberUpdateRestoresEverything()throws Exception{long id=approvedPerson("DEATH",202L);doThrow(new IllegalStateException("rollback")).when(hook).afterMemberUpdate();executePerson(id,500);assertPersonRollback(id);}
@Test void personRollbackAfterPersonUpdateRestoresEverything()throws Exception{long id=approvedPerson("DEATH",202L);doThrow(new IllegalStateException("rollback")).when(hook).afterPersonUpdate();executePerson(id,500);assertPersonRollback(id);}
@Test void householdRollbackAfterArchiveRestoresArchiveAndStatus()throws Exception{long id=approvedHousehold();doThrow(new IllegalStateException("rollback")).when(hook).afterHouseholdArchive();executeHousehold(id,500);assertThat(count("household_archive","application_id",id)).isZero();assertThat(jdbc.queryForObject("SELECT status FROM household WHERE household_id=202",String.class)).isEqualTo("PENDING_CANCELLATION");assertThat(status(id)).isEqualTo("APPROVED");}
@Test void householdRollbackRestoresArchiveAndStatus()throws Exception{long id=approvedHousehold();doThrow(new IllegalStateException("rollback")).when(hook).afterHouseholdUpdate();executeHousehold(id,500);assertThat(count("household_archive","application_id",id)).isZero();assertThat(jdbc.queryForObject("SELECT status FROM household WHERE household_id=202",String.class)).isEqualTo("PENDING_CANCELLATION");assertThat(status(id)).isEqualTo("APPROVED");}
@Test void queryViewerSeesMaskedIdentity()throws Exception{long id=approvedPerson("DEATH",202L);executePerson(id,200);mvc.perform(get("/api/cancellations").header("Authorization",bearer(token("viewer")))).andExpect(status().isOk()).andExpect(jsonPath("$.data.content[0].identityNo").value("1101**********0011"));}
@Test void completedCancellationWritesAuditLogs()throws Exception{long id=approvedPerson("DEATH",202L);executePerson(id,200);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM operation_log WHERE operation_type='PERSON_CANCELLATION_EXECUTE'",Integer.class)).isOne();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM sys_approval_log WHERE application_id=? AND action='EXECUTE'",Integer.class,id)).isOne();}
private long approvedPerson(String reason,Long head)throws Exception{long id=createPerson("population",201,head,201,reason);material(id,"APPLICANT_IDENTITY_PROOF");material(id,"HOUSEHOLD_BOOK");material(id,reason.equals("DEATH")?"DEATH_CERTIFICATE":"SETTLEMENT_ABROAD_PROOF");submitApprove(id,"population");return id;}private long approvedHousehold()throws Exception{long id=createHousehold(202,201);material(id,"CANCELLATION_APPLICATION");material(id,"HOUSEHOLD_BOOK");material(id,"HOUSEHOLD_CANCELLATION_PROOF");submitApprove(id,"household");return id;}
private long createPerson(String user,long person,Long head,int expected)throws Exception{return createPerson(user,person,head,expected,"DEATH");}private long createPerson(String user,long person,Long head,int expected,String reason)throws Exception{String nh=head==null?"null":head.toString();String b=mvc.perform(post("/api/cancellations/person/applications").header("Authorization",bearer(token(user))).contentType(MediaType.APPLICATION_JSON).content("{\"personId\":"+person+",\"cancelReasonCode\":\""+reason+"\",\"eventDate\":\"2026-07-13\",\"newHeadPersonId\":"+nh+",\"sourceHouseholdId\":999,\"title\":\"人员注销\",\"reason\":\"课程办理\"}")).andExpect(status().is(expected)).andReturn().getResponse().getContentAsString();return expected==201?json.readTree(b).path("data").path("applicationId").asLong():0;}
private long createHousehold(long household,int expected)throws Exception{String b=mvc.perform(post("/api/cancellations/household/applications").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"householdId\":"+household+",\"cancelReasonCode\":\"NO_ACTIVE_MEMBERS\",\"eventDate\":\"2026-07-13\",\"title\":\"家庭户销户\",\"reason\":\"无有效成员\"}")).andExpect(status().is(expected)).andReturn().getResponse().getContentAsString();return expected==201?json.readTree(b).path("data").path("applicationId").asLong():0;}
private void material(long id,String type){String hash=UUID.randomUUID().toString().replace("-","")+UUID.randomUUID().toString().replace("-","");jdbc.update("INSERT INTO application_material(application_id,material_type,material_name,original_filename,stored_filename,storage_path,content_type,file_size,file_sha256,required_flag,verify_status,verify_user_id,uploaded_by) VALUES(?,?,?,'x.pdf',?,?,'application/pdf',1,?,1,'VERIFIED',7,6)",id,type,type,UUID.randomUUID()+".pdf","test",hash);}private void submit(long id,String user,int expected)throws Exception{mvc.perform(post("/api/applications/"+id+"/submit").header("Authorization",bearer(token(user)))).andExpect(status().is(expected));}private void submitApprove(long id,String user)throws Exception{submit(id,user,200);long approval=jdbc.queryForObject("SELECT approval_id FROM sys_approval_request WHERE application_id=?",Long.class,id);mvc.perform(post("/api/approvals/"+approval+"/approve").header("Authorization",bearer(token("approver"))).contentType(MediaType.APPLICATION_JSON).content("{\"comment\":\"同意\",\"version\":0}")).andExpect(status().isOk());}
private void executePerson(long id,int expected)throws Exception{mvc.perform(post("/api/cancellations/person/applications/"+id+"/execute").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"version\":2}")).andExpect(status().is(expected));}private void executeHousehold(long id,int expected)throws Exception{mvc.perform(post("/api/cancellations/household/applications/"+id+"/execute").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"version\":2}")).andExpect(status().is(expected));}
private void assertPersonRollback(long id){assertThat(count("residence_archive","application_id",id)).isZero();assertThat(count("residence","person_id",201)).isOne();assertThat(jdbc.queryForObject("SELECT status FROM household_member WHERE person_id=201",String.class)).isEqualTo("ACTIVE");assertThat(jdbc.queryForObject("SELECT current_status_code FROM person WHERE person_id=201",String.class)).isEqualTo("REGISTERED");assertThat(status(id)).isEqualTo("APPROVED");}private int count(String table,String key,long id){return jdbc.queryForObject("SELECT COUNT(*) FROM "+table+" WHERE "+key+"=?",Integer.class,id);}private String status(long id){return jdbc.queryForObject("SELECT status FROM business_application WHERE application_id=?",String.class,id);}private String token(String user)throws Exception{String b=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"username\":\""+user+"\",\"password\":\"123456\"}")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();return json.readTree(b).path("data").path("token").asText();}private String bearer(String t){return "Bearer "+t;}}
