package com.wjx871.population.reference;
import com.wjx871.population.audit.OperationLogService;import com.wjx871.population.common.BusinessException;import com.wjx871.population.security.CurrentUserContext;import jakarta.servlet.http.HttpServletRequest;import java.util.*;import lombok.RequiredArgsConstructor;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service@RequiredArgsConstructor public class AdminRegionService {private final AdminRegionMapper mapper;private final OperationLogService audit;
 public List<AdminRegion> search(String parent,Integer level,String status,String keyword){return mapper.search(trim(parent),level,trim(status),trim(keyword));}
 public AdminRegion get(String code){return mapper.findByCode(code).orElseThrow(()->notFound("行政区划不存在"));}
 public List<AdminRegion> children(String code){get(code);return mapper.search(code,null,null,null);}
 public List<AdminRegion> tree(){List<AdminRegion> all=mapper.search(null,null,"ENABLED",null);Map<Long,AdminRegion> byId=new LinkedHashMap<>();List<AdminRegion> roots=new ArrayList<>();all.forEach(x->{x.setChildren(new ArrayList<>());byId.put(x.getRegionId(),x);});for(AdminRegion x:all){if(x.getParentId()==null)roots.add(x);else{AdminRegion p=byId.get(x.getParentId());if(p!=null)p.getChildren().add(x);}}return roots;}
 @Transactional public AdminRegion create(AdminRegionCreateRequest q,HttpServletRequest http){if(mapper.findByCode(q.regionCode()).isPresent())throw conflict("行政区划编码已存在");AdminRegion p=parent(q.parentCode(),q.regionLevel(),q.regionCode());AdminRegion v=value(q.regionCode(),q.regionName(),p,q.regionLevel(),q.fullName(),q.sortNo());v.setStatus("ENABLED");v.setVersion(0);mapper.insert(v);log("REGION_CREATE",q.regionCode(),http);return get(q.regionCode());}
 @Transactional public AdminRegion update(String code,AdminRegionUpdateRequest q,HttpServletRequest http){AdminRegion old=get(code);AdminRegion p=parent(q.parentCode(),q.regionLevel(),code);AdminRegion v=value(code,q.regionName(),p,q.regionLevel(),q.fullName(),q.sortNo());if(mapper.update(v,q.version())==0)throw conflict("行政区划已被其他操作修改");log("REGION_UPDATE",code,http);return get(code);}
 @Transactional public void disable(String code,VersionRequest q,HttpServletRequest http){AdminRegion v=get(code);if(mapper.countEnabledChildren(v.getRegionId())>0)throw conflict("存在启用子区划，不能停用");change(code,"ENABLED","DISABLED",q.version(),"REGION_DISABLE",http);}
 @Transactional public void enable(String code,VersionRequest q,HttpServletRequest http){AdminRegion v=get(code);if(v.getParentId()!=null&&!"ENABLED".equals(get(v.getParentCode()).getStatus()))throw conflict("父区划未启用");change(code,"DISABLED","ENABLED",q.version(),"REGION_ENABLE",http);}
 private void change(String c,String from,String to,Integer ver,String op,HttpServletRequest h){if(mapper.updateStatus(c,from,to,ver)==0)throw conflict("状态或版本已变化");log(op,c,h);}private AdminRegion parent(String code,Integer level,String self){if(code==null||code.isBlank()){if(level!=1)throw new BusinessException(HttpStatus.BAD_REQUEST,"非根区划必须指定父区划");return null;}if(code.equals(self))throw new BusinessException(HttpStatus.BAD_REQUEST,"区划不能以自身为父节点");AdminRegion p=get(code);if(p.getRegionLevel()>=level)throw new BusinessException(HttpStatus.BAD_REQUEST,"子区划级别必须低于父区划");for(AdminRegion x=p;x!=null&&x.getParentCode()!=null;x=mapper.findByCode(x.getParentCode()).orElse(null))if(self.equals(x.getParentCode()))throw new BusinessException(HttpStatus.BAD_REQUEST,"区划父子关系不能形成循环");return p;}private AdminRegion value(String code,String name,AdminRegion p,Integer level,String full,Integer sort){AdminRegion v=new AdminRegion();v.setRegionCode(code);v.setRegionName(name);v.setParentId(p==null?null:p.getRegionId());v.setRegionLevel(level);v.setFullName(full);v.setSortNo(sort);return v;}private void log(String op,String code,HttpServletRequest h){audit.recordTransactional(CurrentUserContext.requireUser().userId(),op,"REGION",code,h);}private String trim(String x){return x==null||x.isBlank()?null:x.trim();}private BusinessException notFound(String m){return new BusinessException(HttpStatus.NOT_FOUND,m);}private BusinessException conflict(String m){return new BusinessException(HttpStatus.CONFLICT,m);}}
