package com.wjx871.population.reference;
import com.wjx871.population.common.ApiResponse;import jakarta.servlet.http.HttpServletRequest;import jakarta.validation.Valid;import java.util.*;import lombok.RequiredArgsConstructor;import org.springframework.http.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;
@RestController@RequestMapping("/api/admin-regions")@RequiredArgsConstructor public class AdminRegionController {private final AdminRegionService service;
@GetMapping@PreAuthorize("hasAuthority('region:view')")public ApiResponse<List<AdminRegion>> search(@RequestParam(required=false)String parentCode,@RequestParam(required=false)Integer regionLevel,@RequestParam(required=false)String status,@RequestParam(required=false)String keyword){return ApiResponse.ok(service.search(parentCode,regionLevel,status,keyword));}
@GetMapping("/tree")@PreAuthorize("hasAuthority('region:view')")public ApiResponse<List<AdminRegion>> tree(){return ApiResponse.ok(service.tree());}
@GetMapping("/{code}")@PreAuthorize("hasAuthority('region:view')")public ApiResponse<AdminRegion> get(@PathVariable String code){return ApiResponse.ok(service.get(code));}
@GetMapping("/{code}/children")@PreAuthorize("hasAuthority('region:view')")public ApiResponse<List<AdminRegion>> children(@PathVariable String code){return ApiResponse.ok(service.children(code));}
@PostMapping@ResponseStatus(HttpStatus.CREATED)@PreAuthorize("hasAuthority('region:manage')")public ApiResponse<AdminRegion> create(@Valid@RequestBody AdminRegionCreateRequest q,HttpServletRequest h){return ApiResponse.created(service.create(q,h));}
@PutMapping("/{code}")@PreAuthorize("hasAuthority('region:manage')")public ApiResponse<AdminRegion> update(@PathVariable String code,@Valid@RequestBody AdminRegionUpdateRequest q,HttpServletRequest h){return ApiResponse.ok(service.update(code,q,h));}
@PostMapping("/{code}/disable")@PreAuthorize("hasAuthority('region:manage')")public ApiResponse<Void> disable(@PathVariable String code,@Valid@RequestBody VersionRequest q,HttpServletRequest h){service.disable(code,q,h);return ApiResponse.ok(null);}
@PostMapping("/{code}/enable")@PreAuthorize("hasAuthority('region:manage')")public ApiResponse<Void> enable(@PathVariable String code,@Valid@RequestBody VersionRequest q,HttpServletRequest h){service.enable(code,q,h);return ApiResponse.ok(null);}}
