package com.wjx871.population.reference;import com.wjx871.population.audit.OperationLogService;import com.wjx871.population.common.BusinessException;import com.wjx871.population.security.*;import jakarta.servlet.http.HttpServletRequest;import java.util.*;import lombok.RequiredArgsConstructor;import org.springframework.data.domain.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service@RequiredArgsConstructor public class DataDictionaryService {private final DataDictionaryMapper mapper;private final OperationLogService audit;
public Page<DataDictionary> search(String type,String code,String keyword,String status,Pageable p){String allowed=canManage()?trim(status):"ENABLED";List<DataDictionary> rows=mapper.search(norm(type),norm(code),trim(keyword),allowed,p.getPageSize(),p.getOffset());return new PageImpl<>(rows,p,mapper.count(norm(type),norm(code),trim(keyword),allowed));}
public List<DataDictionary> byType(String type){return mapper.search(norm(type),null,null,canManage()?null:"ENABLED",1000,0);}public DataDictionary get(String type,String code){DataDictionary v=mapper.findByTypeCode(norm(type),norm(code)).orElseThrow(()->new BusinessException(HttpStatus.NOT_FOUND,"字典项不存在"));if(!canManage()&&!"ENABLED".equals(v.getStatus()))throw new BusinessException(HttpStatus.NOT_FOUND,"字典项不存在");return v;}
public boolean enabled(String type,String code){return mapper.findByTypeCode(norm(type),norm(code)).filter(v->"ENABLED".equals(v.getStatus())).isPresent();}
@Transactional public DataDictionary create(DictionaryCreateRequest q,HttpServletRequest h){if(mapper.findByTypeCode(q.dictionaryType(),q.dictionaryCode()).isPresent())throw conflict("字典类型和编码已存在");DataDictionary v=new DataDictionary();v.setDictType(q.dictionaryType());v.setDictCode(q.dictionaryCode());v.setDictName(q.displayName());v.setSortNo(q.sortNo());v.setStatus("ENABLED");v.setVersion(0);mapper.insert(v);log("DICTIONARY_CREATE",v.getDictId(),h);return mapper.findById(v.getDictId()).orElseThrow();}
@Transactional public DataDictionary update(Long id,DictionaryUpdateRequest q,HttpServletRequest h){DataDictionary v=require(id);v.setDictName(q.displayName());v.setSortNo(q.sortNo());if(mapper.update(v,q.version())==0)throw conflict("字典项已被其他操作修改");log("DICTIONARY_UPDATE",id,h);return require(id);}
@Transactional public void enable(Long id,VersionRequest q,HttpServletRequest h){change(id,"DISABLED","ENABLED",q.version(),"DICTIONARY_ENABLE",h);}@Transactional public void disable(Long id,VersionRequest q,HttpServletRequest h){change(id,"ENABLED","DISABLED",q.version(),"DICTIONARY_DISABLE",h);}
private void change(Long id,String from,String to,Integer ver,String op,HttpServletRequest h){require(id);if(mapper.updateStatus(id,from,to,ver)==0)throw conflict("状态或版本已变化");log(op,id,h);}private DataDictionary require(Long id){return mapper.findById(id).orElseThrow(()->new BusinessException(HttpStatus.NOT_FOUND,"字典项不存在"));}private boolean canManage(){AuthenticatedUser u=CurrentUserContext.requireUser();return u.permissions().contains("dictionary:manage");}private void log(String op,Long id,HttpServletRequest h){audit.recordTransactional(CurrentUserContext.requireUser().userId(),op,"DICTIONARY",String.valueOf(id),h);}private String norm(String x){x=trim(x);return x==null?null:x.toUpperCase(Locale.ROOT);}private String trim(String x){return x==null||x.isBlank()?null:x.trim();}private BusinessException conflict(String m){return new BusinessException(HttpStatus.CONFLICT,m);}}
