package com.wjx871.population.reference;import com.wjx871.population.common.ApiResponse;import jakarta.servlet.http.HttpServletRequest;import jakarta.validation.Valid;import java.util.*;import lombok.RequiredArgsConstructor;import org.springframework.data.domain.*;import org.springframework.http.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;
@RestController@RequestMapping("/api/dictionaries")@RequiredArgsConstructor public class DataDictionaryController {private final DataDictionaryService service;
@GetMapping@PreAuthorize("hasAuthority('dictionary:view')")public ApiResponse<Page<DataDictionary>> search(@RequestParam(required=false)String dictionaryType,@RequestParam(required=false)String dictionaryCode,@RequestParam(required=false)String keyword,@RequestParam(required=false)String status,Pageable p){return ApiResponse.ok(service.search(dictionaryType,dictionaryCode,keyword,status,p));}
@GetMapping("/{type}")@PreAuthorize("hasAuthority('dictionary:view')")public ApiResponse<List<DataDictionary>> type(@PathVariable String type){return ApiResponse.ok(service.byType(type));}
@GetMapping("/{type}/{code}")@PreAuthorize("hasAuthority('dictionary:view')")public ApiResponse<DataDictionary> get(@PathVariable String type,@PathVariable String code){return ApiResponse.ok(service.get(type,code));}
@PostMapping@ResponseStatus(HttpStatus.CREATED)@PreAuthorize("hasAuthority('dictionary:manage')")public ApiResponse<DataDictionary> create(@Valid@RequestBody DictionaryCreateRequest q,HttpServletRequest h){return ApiResponse.created(service.create(q,h));}
@PutMapping("/{id}")@PreAuthorize("hasAuthority('dictionary:manage')")public ApiResponse<DataDictionary> update(@PathVariable Long id,@Valid@RequestBody DictionaryUpdateRequest q,HttpServletRequest h){return ApiResponse.ok(service.update(id,q,h));}
@PostMapping("/{id}/enable")@PreAuthorize("hasAuthority('dictionary:manage')")public ApiResponse<Void> enable(@PathVariable Long id,@Valid@RequestBody VersionRequest q,HttpServletRequest h){service.enable(id,q,h);return ApiResponse.ok(null);}
@PostMapping("/{id}/disable")@PreAuthorize("hasAuthority('dictionary:manage')")public ApiResponse<Void> disable(@PathVariable Long id,@Valid@RequestBody VersionRequest q,HttpServletRequest h){service.disable(id,q,h);return ApiResponse.ok(null);}}
