package com.wjx871.population.material;
import com.wjx871.population.audit.OperationLogService; import com.wjx871.population.common.ApiResponse; import jakarta.servlet.http.HttpServletRequest; import jakarta.validation.Valid; import java.nio.charset.StandardCharsets; import java.util.List; import lombok.RequiredArgsConstructor;
import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile;
@RestController @RequiredArgsConstructor
public class MaterialController { private final MaterialService service; private final OperationLogService audit;
 @PostMapping(value="/api/applications/{id}/materials",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAuthority('material:upload')") public ApiResponse<MaterialView> upload(@PathVariable Long id,@RequestParam String materialType,@RequestParam String materialName,@RequestParam(defaultValue="false") boolean requiredFlag,@RequestPart("file") MultipartFile file){return ApiResponse.created(service.upload(id,materialType,materialName,requiredFlag,file));}
 @GetMapping("/api/applications/{id}/materials") @PreAuthorize("hasAuthority('material:view')") public ApiResponse<List<MaterialView>> list(@PathVariable Long id){return ApiResponse.ok(service.list(id));}
 @GetMapping("/api/materials/{id}/download") @PreAuthorize("hasAuthority('material:view')") public ResponseEntity<org.springframework.core.io.Resource> download(@PathVariable Long id){var d=service.download(id);return ResponseEntity.ok().contentType(MediaType.parseMediaType(d.contentType())).header(HttpHeaders.CONTENT_DISPOSITION,ContentDisposition.attachment().filename(d.filename(),StandardCharsets.UTF_8).build().toString()).body(d.resource());}
 @DeleteMapping("/api/materials/{id}") @PreAuthorize("hasAuthority('material:delete')") public ApiResponse<Void> delete(@PathVariable Long id){service.delete(id);return ApiResponse.ok(null);}
 @PostMapping("/api/materials/{id}/verify") @PreAuthorize("hasAuthority('material:verify')") public ApiResponse<MaterialView> verify(@PathVariable Long id,@Valid @RequestBody MaterialVerifyRequest body,HttpServletRequest req){return ApiResponse.ok(service.verify(id,body,audit.clientIp(req)));}
}
