export const APPLICATION_STATUS = Object.freeze({
  DRAFT: '草稿',
  SUBMITTED: '已提交',
  UNDER_REVIEW: '审批中',
  APPROVED: '已通过，待执行',
  REJECTED: '已驳回',
  RETURNED: '已退回，待处理',
  RESUBMITTED: '已重新提交',
  WITHDRAWN: '已撤回',
  COMPLETED: '已办结',
  CANCELLED: '已取消',
})

export const BUSINESS_TYPE = Object.freeze({
  MIGRATION_IN: 'MIGRATION_IN',
  MIGRATION_OUT: 'MIGRATION_OUT',
  FLOATING_REGISTRATION: 'FLOATING_REGISTRATION',
  RESIDENCE_PERMIT_FIRST_ISSUE: 'RESIDENCE_PERMIT_FIRST_ISSUE',
  RESIDENCE_PERMIT_ENDORSEMENT: 'RESIDENCE_PERMIT_ENDORSEMENT',
  RESIDENCE_PERMIT_CANCELLATION: 'RESIDENCE_PERMIT_CANCELLATION',
  PERSON_CANCELLATION: 'PERSON_CANCELLATION',
  HOUSEHOLD_CANCELLATION: 'HOUSEHOLD_CANCELLATION',
  KEY_POPULATION_REGISTER: 'KEY_POPULATION_REGISTER',
  KEY_POPULATION_RELEASE: 'KEY_POPULATION_RELEASE',
  SENSITIVE_DATA_EXPORT: 'SENSITIVE_DATA_EXPORT',
})

export const BUSINESS_TYPE_LABEL = Object.freeze({
  [BUSINESS_TYPE.MIGRATION_IN]: '迁入申请',
  [BUSINESS_TYPE.MIGRATION_OUT]: '迁出申请',
  [BUSINESS_TYPE.FLOATING_REGISTRATION]: '流动人口登记',
  [BUSINESS_TYPE.RESIDENCE_PERMIT_FIRST_ISSUE]: '居住证首次申领',
  [BUSINESS_TYPE.RESIDENCE_PERMIT_ENDORSEMENT]: '居住证签注',
  [BUSINESS_TYPE.RESIDENCE_PERMIT_CANCELLATION]: '居住证注销',
  [BUSINESS_TYPE.PERSON_CANCELLATION]: '人员注销',
  [BUSINESS_TYPE.HOUSEHOLD_CANCELLATION]: '家庭户销户',
  [BUSINESS_TYPE.KEY_POPULATION_REGISTER]: '重点人口建档',
  [BUSINESS_TYPE.KEY_POPULATION_RELEASE]: '重点人口解除',
  [BUSINESS_TYPE.SENSITIVE_DATA_EXPORT]: '敏感数据导出',
})

export const READONLY_APPLICATION_STATUS = new Set([
  'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'RETURNED', 'RESUBMITTED',
  'WITHDRAWN', 'COMPLETED', 'CANCELLED',
])

export const APPROVAL_STATUS = Object.freeze({
  PENDING: '待审批',
  APPROVED: '已通过',
  REJECTED: '已驳回',
  CANCELLED: '已取消',
})
