import { ROLE_CODE } from './roles'

export const PERMISSIONS = Object.freeze({
  DASHBOARD_VIEW: 'dashboard:view',
  PERSON_VIEW: 'person:view',
  PERSON_CREATE: 'person:create',
  PERSON_UPDATE: 'person:update',
  PERSON_DELETE: 'person:delete',
  /** 详情中临时查看完整敏感信息；列表默认仍脱敏 */
  PERSON_SENSITIVE_VIEW: 'person:sensitive:view',
  HOUSEHOLD_VIEW: 'household:view',
  HOUSEHOLD_CREATE: 'household:create',
  HOUSEHOLD_UPDATE: 'household:update',
  HOUSEHOLD_MEMBER_MANAGE: 'household:member:manage',
  HOUSEHOLD_DELETE: 'household:delete',
  MIGRATION_VIEW: 'migration:view',
  MIGRATION_IN_CREATE: 'migration:in:create',
  MIGRATION_OUT_CREATE: 'migration:out:create',
  MIGRATION_EXECUTE: 'migration:execute',
  MIGRATION_ARCHIVE_VIEW: 'migration:archive:view',
  APPLICATION_VIEW: 'application:view',
  APPLICATION_CREATE: 'application:create',
  APPLICATION_EDIT: 'application:edit',
  APPLICATION_SUBMIT: 'application:submit',
  APPLICATION_WITHDRAW: 'application:withdraw',
  MATERIAL_VIEW: 'material:view',
  MATERIAL_UPLOAD: 'material:upload',
  MATERIAL_DELETE: 'material:delete',
  MATERIAL_VERIFY: 'material:verify',
  APPROVAL_VIEW: 'approval:view',
  APPROVAL_HANDLE: 'approval:handle',
  FLOATING_VIEW: 'floating:view',
  FLOATING_CREATE: 'floating:create',
  FLOATING_EDIT: 'floating:edit',
  FLOATING_EXECUTE: 'floating:execute',
  FLOATING_CLOSE: 'floating:close',
  /** @deprecated legacy — 旧粗粒度权限，待通用证件清理后移除 */
  FLOATING_MANAGE: 'floating:manage',
  RESIDENCE_PERMIT_APPLY: 'residence-permit:apply',
  RESIDENCE_PERMIT_VIEW: 'residence-permit:view',
  RESIDENCE_PERMIT_ISSUE: 'residence-permit:issue',
  RESIDENCE_PERMIT_ENDORSE: 'residence-permit:endorse',
  RESIDENCE_PERMIT_CANCEL: 'residence-permit:cancel',
  RESIDENCE_PERMIT_LOG_VIEW: 'residence-permit:log:view',
  RESIDENCE_PERMIT_EXPIRY_VIEW: 'residence-permit:expiry:view',
  KEY_VIEW: 'key:view',
  KEY_APPLY: 'key:apply',
  KEY_MANAGE: 'key:manage',
  CERTIFICATE_VIEW: 'certificate:view',
  /** @deprecated legacy — 旧通用证件权限，待清理后移除 */
  CERTIFICATE_MANAGE: 'certificate:manage',
  /** @deprecated legacy — 旧通用证件权限，待清理后移除 */
  CERTIFICATE_DELETE: 'certificate:delete',
  USER_VIEW: 'user:view',
  USER_MANAGE: 'user:manage',
  DICTIONARY_VIEW: 'dictionary:view',
  DICTIONARY_MANAGE: 'dictionary:manage'
})

export const ROLE_DEFAULT_PERMISSIONS = Object.freeze({
  [ROLE_CODE.NORMAL_USER]: [
    'population:view',
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PERSON_VIEW,
    PERMISSIONS.HOUSEHOLD_VIEW,
    PERMISSIONS.MIGRATION_VIEW,
    PERMISSIONS.MIGRATION_ARCHIVE_VIEW,
    PERMISSIONS.FLOATING_VIEW,
    PERMISSIONS.RESIDENCE_PERMIT_VIEW,
    PERMISSIONS.RESIDENCE_PERMIT_LOG_VIEW,
    PERMISSIONS.RESIDENCE_PERMIT_EXPIRY_VIEW,
    PERMISSIONS.CERTIFICATE_VIEW
  ],
  [ROLE_CODE.HOUSEHOLD_ADMIN]: [
    'population:view',
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PERSON_VIEW,
    PERMISSIONS.PERSON_CREATE,
    PERMISSIONS.PERSON_UPDATE,
    PERMISSIONS.PERSON_SENSITIVE_VIEW,
    PERMISSIONS.HOUSEHOLD_VIEW,
    PERMISSIONS.HOUSEHOLD_CREATE,
    PERMISSIONS.HOUSEHOLD_UPDATE,
    PERMISSIONS.HOUSEHOLD_MEMBER_MANAGE,
    PERMISSIONS.MIGRATION_VIEW,
    PERMISSIONS.MIGRATION_IN_CREATE,
    PERMISSIONS.MIGRATION_OUT_CREATE,
    PERMISSIONS.APPLICATION_VIEW,
    PERMISSIONS.APPLICATION_EDIT,
    PERMISSIONS.APPLICATION_SUBMIT,
    PERMISSIONS.APPLICATION_WITHDRAW,
    PERMISSIONS.MATERIAL_VIEW,
    PERMISSIONS.MATERIAL_UPLOAD,
    PERMISSIONS.MATERIAL_DELETE,
    PERMISSIONS.FLOATING_VIEW,
    PERMISSIONS.FLOATING_CREATE,
    PERMISSIONS.FLOATING_EDIT,
    PERMISSIONS.FLOATING_MANAGE,
    PERMISSIONS.RESIDENCE_PERMIT_VIEW,
    PERMISSIONS.RESIDENCE_PERMIT_APPLY,
    PERMISSIONS.RESIDENCE_PERMIT_LOG_VIEW,
    PERMISSIONS.RESIDENCE_PERMIT_EXPIRY_VIEW,
    PERMISSIONS.KEY_VIEW,
    PERMISSIONS.KEY_APPLY,
    PERMISSIONS.CERTIFICATE_VIEW,
    PERMISSIONS.CERTIFICATE_MANAGE
  ],
  [ROLE_CODE.SUPER_ADMIN]: ['*']
})
