package com.wjx871.population.keypopulation;import com.fasterxml.jackson.databind.*;import java.util.*;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.*;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.http.MediaType;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.test.web.servlet.MockMvc;import static org.assertj.core.api.Assertions.assertThat;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest@AutoConfigureMockMvc@TestInstance(TestInstance.Lifecycle.PER_CLASS)@TestMethodOrder(MethodOrderer.OrderAnnotation.class)class Phase10KeyPopulationIntegrationTest{@Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired JdbcTemplate jdbc;long registerApp,recordId,releaseApp;
@BeforeAll void setup(){jdbc.update("INSERT INTO person(person_id,name,gender,id_card,phone,current_address,status,current_status_code) VALUES(10001,'重点甲','M','110105198001010016','13800138000','示例省示例市示例西区测试路1号','正常','REGISTERED'),(10002,'注销乙','F','110105198002020024','13900139000','示例地址','注销','CANCELLED'),(10003,'外区丙','M','120101198003030039','13700137000','外区地址','正常','REGISTERED')");jdbc.update("INSERT INTO household(household_id,household_no,address,region_code,household_type,establish_date,status,version) VALUES(10001,'KEY-H1','示例地址','110105','FAMILY','2020-01-01','ACTIVE',0),(10003,'KEY-H3','外区地址','120101','FAMILY','2020-01-01','ACTIVE',0)");jdbc.update("INSERT INTO residence(person_id,household_id,registered_address,region_code,register_type_code,register_date,start_date,status,version) VALUES(10001,10001,'示例地址','110105','OTHER','2020-01-01','2020-01-01','ACTIVE',0),(10002,10001,'历史地址','110105','OTHER','2020-01-01','2020-01-01','INACTIVE',0),(10003,10003,'外区地址','120101','OTHER','2020-01-01','2020-01-01','ACTIVE',0)");}
@Test@Order(1)void emptyPagination(){fetch("/api/key-populations","viewer",200);}
@Test@Order(2)void viewerCannotApply()throws Exception{postJson("/api/key-populations/register-applications","viewer",registerBody(10001,"OTHER"),403);}
@Test@Order(3)void missingPerson()throws Exception{postJson("/api/key-populations/register-applications","population",registerBody(99999,"OTHER"),404);}
@Test@Order(4)void cancelledPerson()throws Exception{postJson("/api/key-populations/register-applications","population",registerBody(10002,"OTHER"),409);}
@Test@Order(5)void invalidType()throws Exception{postJson("/api/key-populations/register-applications","population",registerBody(10001,"INVALID"),400);}
@Test@Order(6)void crossRegionCreate()throws Exception{postJson("/api/key-populations/register-applications","population",registerBody(10003,"OTHER"),404);}
@Test@Order(7)void createRegisterDraft()throws Exception{String b=postJson("/api/key-populations/register-applications","population",registerBody(10001,"OTHER"),201);registerApp=json.readTree(b).path("data").path("application").path("applicationId").asLong();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM key_population",Integer.class)).isZero();}
@Test@Order(8)void duplicateOpenRegister()throws Exception{postJson("/api/key-populations/register-applications","population",registerBody(10001,"OTHER"),409);}
@Test@Order(9)void detailDraft(){fetch("/api/key-populations/register-applications/"+registerApp,"population",200);}
@Test@Order(10)void missingMaterialsBlockSubmit()throws Exception{postJson("/api/key-populations/register-applications/"+registerApp+"/submit","population",null,409);}
@Test@Order(11)void unverifiedMaterialsCanSubmitForApproval()throws Exception{material(registerApp,"KEY_POPULATION_BASIS","PENDING");material(registerApp,"SITUATION_DESCRIPTION","PENDING");postJson("/api/key-populations/register-applications/"+registerApp+"/submit","population",null,200);assertThat(appStatus(registerApp)).isEqualTo("UNDER_REVIEW");}
@Test@Order(12)void unverifiedMaterialsBlockApproval()throws Exception{long approval=jdbc.queryForObject("SELECT approval_id FROM sys_approval_request WHERE application_id=?",Long.class,registerApp);postJson("/api/approvals/"+approval+"/approve","approver","{\"comment\":\"审核意见\",\"version\":0}",409);}
@Test@Order(13)void unapprovedCannotExecute()throws Exception{postJson("/api/key-populations/register-applications/"+registerApp+"/execute","population","{\"version\":1}",409);}
@Test@Order(14)void approvalDoesNotAutoRegister()throws Exception{jdbc.update("UPDATE application_material SET verify_status='VERIFIED' WHERE application_id=?",registerApp);approve(registerApp,true);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM key_population",Integer.class)).isZero();}
@Test@Order(15)void approverCannotExecute()throws Exception{postJson("/api/key-populations/register-applications/"+registerApp+"/execute","approver","{\"version\":2}",403);}
@Test@Order(16)void explicitRegister()throws Exception{postJson("/api/key-populations/register-applications/"+registerApp+"/execute","population","{\"version\":2}",200);recordId=jdbc.queryForObject("SELECT key_id FROM key_population WHERE source_application_id=?",Long.class,registerApp);assertThat(appStatus(registerApp)).isEqualTo("COMPLETED");}
@Test@Order(17)void repeatedRegister()throws Exception{postJson("/api/key-populations/register-applications/"+registerApp+"/execute","population","{\"version\":3}",409);}
@Test@Order(18)void activeDuplicateBlocked()throws Exception{postJson("/api/key-populations/register-applications","population",registerBody(10001,"OTHER"),409);}
@Test@Order(19)void queryFilters(){fetch("/api/key-populations?personName=重点甲&populationType=OTHER&status=ACTIVE","population",200);}
@Test@Order(20)void personQuery(){fetch("/api/persons/10001/key-populations","population",200);}
@Test@Order(21)void detailMasked()throws Exception{String b=fetch("/api/key-populations/"+recordId,"population",200);assertThat(b).contains("1101**********0016").doesNotContain("110105198001010016").contains("138****8000");}
@Test@Order(22)void adminFullSensitive()throws Exception{assertThat(fetch("/api/key-populations/"+recordId,"admin",200)).contains("110105198001010016");}
@Test@Order(23)void registerHistory(){fetch("/api/key-populations/"+recordId+"/history","population",200);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM key_population_history WHERE event_type='REGISTERED'",Integer.class)).isOne();}
@Test@Order(24)void historySnapshotSafe(){String s=jdbc.queryForObject("SELECT snapshot_json FROM key_population_history WHERE event_type='REGISTERED'",String.class);assertThat(s).doesNotContain("110105198001010016").doesNotContain("13800138000");}
@Test@Order(25)void releaseMissingRecord()throws Exception{postJson("/api/key-populations/99999/release-applications","population",releaseBody("2026-07-13"),404);}
@Test@Order(26)void releaseDateBeforeRegistration()throws Exception{postJson("/api/key-populations/"+recordId+"/release-applications","population",releaseBody("2019-01-01"),400);}
@Test@Order(27)void createReleaseDraft()throws Exception{String b=postJson("/api/key-populations/"+recordId+"/release-applications","population",releaseBody("2026-07-13"),201);releaseApp=json.readTree(b).path("data").path("application").path("applicationId").asLong();}
@Test@Order(28)void duplicateOpenRelease()throws Exception{postJson("/api/key-populations/"+recordId+"/release-applications","population",releaseBody("2026-07-13"),409);}
@Test@Order(29)void releaseMissingMaterials()throws Exception{postJson("/api/key-populations/release-applications/"+releaseApp+"/submit","population",null,409);}
@Test@Order(30)void releaseSubmit()throws Exception{material(releaseApp,"KEY_POPULATION_BASIS","VERIFIED");material(releaseApp,"SITUATION_DESCRIPTION","VERIFIED");postJson("/api/key-populations/release-applications/"+releaseApp+"/submit","population",null,200);}
@Test@Order(31)void releaseApprovalDoesNotAutoRelease()throws Exception{approve(releaseApp,true);assertThat(jdbc.queryForObject("SELECT status FROM key_population WHERE key_id=?",String.class,recordId)).isEqualTo("ACTIVE");}
@Test@Order(32)void explicitRelease()throws Exception{postJson("/api/key-populations/release-applications/"+releaseApp+"/execute","population","{\"version\":2}",200);assertThat(jdbc.queryForObject("SELECT status FROM key_population WHERE key_id=?",String.class,recordId)).isEqualTo("RELEASED");}
@Test@Order(33)void repeatedRelease()throws Exception{postJson("/api/key-populations/release-applications/"+releaseApp+"/execute","population","{\"version\":3}",409);}
@Test@Order(34)void releasedCannotReleaseAgain()throws Exception{postJson("/api/key-populations/"+recordId+"/release-applications","population",releaseBody("2026-07-13"),409);}
@Test@Order(35)void releaseHistoryAndAudit(){assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM key_population_history WHERE record_id=?",Integer.class,recordId)).isEqualTo(2);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM operation_log WHERE operation_type LIKE 'KEY_POPULATION_%'",Integer.class)).isGreaterThanOrEqualTo(4);}
@Test@Order(36)void rejectedApplicationNoRecord()throws Exception{jdbc.update("UPDATE key_population SET status='RELEASED' WHERE key_id=?",recordId);String b=postJson("/api/key-populations/register-applications","population",registerBody(10001,"OTHER"),201);long id=json.readTree(b).path("data").path("application").path("applicationId").asLong();material(id,"KEY_POPULATION_BASIS","VERIFIED");material(id,"SITUATION_DESCRIPTION","VERIFIED");postJson("/api/key-populations/register-applications/"+id+"/submit","population",null,200);approve(id,false);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM key_population WHERE source_application_id=?",Integer.class,id)).isZero();}
@RepeatedTest(20)@Order(100)void invariantsRemainStable(){assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM (SELECT person_id,key_type FROM key_population WHERE status='ACTIVE' GROUP BY person_id,key_type HAVING COUNT(*)>1) x",Integer.class)).isZero();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM key_population_history WHERE snapshot_json LIKE '%110105198001010016%'",Integer.class)).isZero();}
private String registerBody(long person,String type){return"{\"personId\":"+person+",\"populationType\":\""+type+"\",\"attentionLevel\":\"MEDIUM\",\"registerReason\":\"课程测试建档\",\"registerDate\":\"2026-07-13\",\"title\":\"重点人口建档\"}";}private String releaseBody(String date){return"{\"releaseReason\":\"课程测试解除\",\"releaseDate\":\""+date+"\",\"title\":\"重点人口解除\"}";}private void material(long app,String type,String status){String x=UUID.randomUUID().toString().replace("-","");jdbc.update("INSERT INTO application_material(application_id,material_type,material_name,original_filename,stored_filename,storage_path,content_type,file_size,file_sha256,required_flag,verify_status,uploaded_by) VALUES(?,?,?,'test.pdf',?,'test','application/pdf',1,?,1,?,2)",app,type,type,x+".pdf",x+x,status);}private String appStatus(long id){return jdbc.queryForObject("SELECT status FROM business_application WHERE application_id=?",String.class,id);}private void approve(long app,boolean ok)throws Exception{long approval=jdbc.queryForObject("SELECT approval_id FROM sys_approval_request WHERE application_id=?",Long.class,app);String path="/api/approvals/"+approval+(ok?"/approve":"/reject");postJson(path,"approver","{\"comment\":\"审核意见\",\"version\":0}",200);}private String fetch(String path,String user,int status){try{return mvc.perform(get(path).header("Authorization",bearer(user))).andExpect(status().is(status)).andReturn().getResponse().getContentAsString();}catch(Exception e){throw new RuntimeException(e);}}private String postJson(String path,String user,String body,int status)throws Exception{var b=post(path).header("Authorization",bearer(user));if(body!=null)b.contentType(MediaType.APPLICATION_JSON).content(body);return mvc.perform(b).andExpect(status().is(status)).andReturn().getResponse().getContentAsString();}private String bearer(String u)throws Exception{String b=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"username\":\""+u+"\",\"password\":\"123456\"}")).andReturn().getResponse().getContentAsString();return"Bearer "+json.readTree(b).path("data").path("token").asText();}}
