-- Phase 10 key population lifecycle (MySQL 8, repeatable).
DROP PROCEDURE IF EXISTS phase10_add_column;
DELIMITER $$
CREATE PROCEDURE phase10_add_column(IN p_table VARCHAR(64),IN p_column VARCHAR(64),IN p_ddl TEXT) BEGIN IF NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name=p_table AND column_name=p_column) THEN SET @p10=p_ddl;PREPARE s FROM @p10;EXECUTE s;DEALLOCATE PREPARE s;END IF;END$$
DELIMITER ;
CALL phase10_add_column('key_population','register_reason','ALTER TABLE key_population ADD COLUMN register_reason VARCHAR(500) NULL AFTER management_level');
CALL phase10_add_column('key_population','responsible_department_id','ALTER TABLE key_population ADD COLUMN responsible_department_id BIGINT NULL AFTER register_date');
CALL phase10_add_column('key_population','responsible_user_id','ALTER TABLE key_population ADD COLUMN responsible_user_id BIGINT NULL AFTER responsible_department_id');
CALL phase10_add_column('key_population','release_reason','ALTER TABLE key_population ADD COLUMN release_reason VARCHAR(500) NULL AFTER status');
CALL phase10_add_column('key_population','release_date','ALTER TABLE key_population ADD COLUMN release_date DATE NULL AFTER release_reason');
CALL phase10_add_column('key_population','source_application_id','ALTER TABLE key_population ADD COLUMN source_application_id BIGINT NULL AFTER release_date');
CALL phase10_add_column('key_population','version','ALTER TABLE key_population ADD COLUMN version INT NOT NULL DEFAULT 0 AFTER source_application_id');
CALL phase10_add_column('key_population','active_flag','ALTER TABLE key_population ADD COLUMN active_flag TINYINT GENERATED ALWAYS AS (CASE WHEN status=''ACTIVE'' THEN 1 ELSE NULL END) STORED AFTER version');
UPDATE key_population SET status=CASE WHEN status IN('有效','ACTIVE') THEN 'ACTIVE' WHEN status IN('解除','RELEASED') THEN 'RELEASED' ELSE status END,register_reason=COALESCE(register_reason,remark,'历史兼容记录');
DROP PROCEDURE IF EXISTS phase10_add_column;

CREATE TABLE IF NOT EXISTS key_population_application(detail_id BIGINT NOT NULL AUTO_INCREMENT,application_id BIGINT NOT NULL,operation_type VARCHAR(20) NOT NULL,record_id BIGINT NULL,person_id BIGINT NOT NULL,population_type VARCHAR(50) NOT NULL,attention_level VARCHAR(20) NOT NULL,reason VARCHAR(500) NOT NULL,event_date DATE NOT NULL,responsible_department_id BIGINT NULL,responsible_user_id BIGINT NULL,business_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',version INT NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(detail_id),UNIQUE KEY uk_key_population_application(application_id),KEY idx_key_app_person_type_status(person_id,population_type,operation_type,business_status),KEY idx_key_app_record_status(record_id,operation_type,business_status),CONSTRAINT fk_key_app_application FOREIGN KEY(application_id) REFERENCES business_application(application_id),CONSTRAINT fk_key_app_record FOREIGN KEY(record_id) REFERENCES key_population(key_id),CONSTRAINT fk_key_app_person FOREIGN KEY(person_id) REFERENCES person(person_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS key_population_history(history_id BIGINT NOT NULL AUTO_INCREMENT,record_id BIGINT NOT NULL,person_id BIGINT NOT NULL,event_type VARCHAR(30) NOT NULL,previous_status VARCHAR(20) NULL,new_status VARCHAR(20) NOT NULL,reason VARCHAR(500) NULL,source_application_id BIGINT NOT NULL,operator_id BIGINT NOT NULL,occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,snapshot_json JSON NOT NULL,PRIMARY KEY(history_id),UNIQUE KEY uk_key_history_application_event(source_application_id,event_type),KEY idx_key_history_record_time(record_id,occurred_at),CONSTRAINT fk_key_history_record FOREIGN KEY(record_id) REFERENCES key_population(key_id),CONSTRAINT fk_key_history_person FOREIGN KEY(person_id) REFERENCES person(person_id),CONSTRAINT fk_key_history_application FOREIGN KEY(source_application_id) REFERENCES business_application(application_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP PROCEDURE IF EXISTS phase10_add_index;
DELIMITER $$
CREATE PROCEDURE phase10_add_index(IN p_table VARCHAR(64),IN p_index VARCHAR(64),IN p_ddl TEXT) BEGIN IF NOT EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name=p_table AND index_name=p_index) THEN SET @p10=p_ddl;PREPARE s FROM @p10;EXECUTE s;DEALLOCATE PREPARE s;END IF;END$$
DELIMITER ;
CALL phase10_add_index('key_population','uk_key_population_active','CREATE UNIQUE INDEX uk_key_population_active ON key_population(person_id,key_type,active_flag)');
CALL phase10_add_index('key_population','idx_key_population_query','CREATE INDEX idx_key_population_query ON key_population(key_type,status,management_level,register_date)');
DROP PROCEDURE IF EXISTS phase10_add_index;
INSERT INTO sys_permission(permission_code,permission_name,module_name,permission_type,status) VALUES('key-population:view','查看重点人口','KEY_POPULATION','API','ENABLED'),('key-population:apply','申请重点人口业务','KEY_POPULATION','API','ENABLED'),('key-population:execute','执行重点人口业务','KEY_POPULATION','API','ENABLED') ON DUPLICATE KEY UPDATE permission_name=VALUES(permission_name),status='ENABLED';
INSERT IGNORE INTO sys_role_permission(role_id,permission_id) SELECT r.role_id,p.permission_id FROM sys_role r CROSS JOIN sys_permission p WHERE (p.permission_code='key-population:view') OR (r.role_code='POPULATION_MANAGER' AND p.permission_code IN('key-population:apply','key-population:execute')) OR r.role_code='SYSTEM_ADMIN';
