-- Phase 06 export security, permission and audit controls (MySQL 8)
USE population_miniterm;

CREATE TABLE IF NOT EXISTS data_export_request(export_request_id BIGINT NOT NULL AUTO_INCREMENT,application_id BIGINT NOT NULL,export_module VARCHAR(40) NOT NULL,export_scope VARCHAR(30) NOT NULL,filter_snapshot TEXT NOT NULL,requested_fields TEXT NOT NULL,requested_format VARCHAR(20) NOT NULL,reason VARCHAR(500) NOT NULL,expected_row_limit INT NOT NULL,business_status VARCHAR(30) NOT NULL,generated_export_log_id BIGINT,operator_id BIGINT,executed_at DATETIME,version INT NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(export_request_id),UNIQUE KEY uk_export_request_application(application_id),KEY idx_export_request_status(business_status,created_at),CONSTRAINT fk_export_request_application FOREIGN KEY(application_id) REFERENCES business_application(application_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS data_export_log(export_log_id BIGINT NOT NULL AUTO_INCREMENT,application_id BIGINT,export_no VARCHAR(50) NOT NULL,export_module VARCHAR(40) NOT NULL,export_type VARCHAR(30) NOT NULL,requested_by BIGINT NOT NULL,executed_by BIGINT,department_id BIGINT,region_code VARCHAR(20),filter_snapshot TEXT NOT NULL,exported_fields TEXT NOT NULL,row_count INT NOT NULL DEFAULT 0,file_name VARCHAR(255) NOT NULL,stored_filename VARCHAR(255) NOT NULL,storage_path VARCHAR(500) NOT NULL,file_sha256 CHAR(64),file_size BIGINT,status VARCHAR(30) NOT NULL,failure_reason VARCHAR(500),created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,completed_at DATETIME,downloaded_at DATETIME,download_count INT NOT NULL DEFAULT 0,version INT NOT NULL DEFAULT 0,PRIMARY KEY(export_log_id),UNIQUE KEY uk_export_no(export_no),UNIQUE KEY uk_export_stored_filename(stored_filename),KEY idx_export_scope(department_id,region_code,created_at),KEY idx_export_status_completed(status,completed_at),CONSTRAINT fk_export_log_application FOREIGN KEY(application_id) REFERENCES business_application(application_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO sys_permission(permission_code,permission_name,module_name,permission_type,status) VALUES
 ('sensitive-data:view-full','查看完整敏感信息','SECURITY','API','ENABLED'),('data:export:normal','普通脱敏导出','EXPORT','API','ENABLED'),('data:export:sensitive:apply','申请敏感导出','EXPORT','API','ENABLED'),('data:export:sensitive:execute','执行敏感导出','EXPORT','API','ENABLED'),('data:export:sensitive:download','下载敏感导出','EXPORT','API','ENABLED'),('data:export:log:view','查看导出记录','EXPORT','API','ENABLED'),('system:user:view','查看用户','SYSTEM','API','ENABLED'),('system:user:manage','管理用户','SYSTEM','API','ENABLED'),('system:role:view','查看角色','SYSTEM','API','ENABLED'),('system:role:manage','管理角色','SYSTEM','API','ENABLED'),('system:department:view','查看部门','SYSTEM','API','ENABLED'),('system:department:manage','管理部门','SYSTEM','API','ENABLED'),('system:permission:view','查看权限','SYSTEM','API','ENABLED'),('certificate:view','查看证件','CERTIFICATE','API','ENABLED')
 ON DUPLICATE KEY UPDATE permission_name=VALUES(permission_name),status='ENABLED';
INSERT IGNORE INTO sys_role_permission(role_id,permission_id) SELECT r.role_id,p.permission_id FROM sys_role r CROSS JOIN sys_permission p WHERE
 (r.role_code='QUERY_VIEWER' AND p.permission_code IN('data:export:normal','data:export:log:view','certificate:view')) OR
 (r.role_code='POPULATION_MANAGER' AND p.permission_code IN('data:export:normal','data:export:sensitive:apply','data:export:log:view','certificate:view')) OR
 (r.role_code='HOUSEHOLD_MANAGER' AND p.permission_code IN('sensitive-data:view-full','data:export:normal','data:export:sensitive:apply','data:export:sensitive:execute','data:export:sensitive:download','data:export:log:view','certificate:view')) OR
 (r.role_code='APPROVER' AND p.permission_code IN('data:export:log:view','data:export:sensitive:download','certificate:view')) OR r.role_code='SYSTEM_ADMIN';
