package com.wjx871.population.floating;
import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;import com.fasterxml.jackson.databind.*;import java.time.*;import java.util.*;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.test.mock.mockito.MockBean;import org.springframework.boot.test.context.TestConfiguration;import org.springframework.context.annotation.*;import org.springframework.http.MediaType;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.test.web.servlet.MockMvc;
@SpringBootTest(properties={"residence-permit.min-residence-days=180","residence-permit.validity-days=365","residence-permit.endorsement-early-days=30","residence-permit.expiry-warning-days=30"}) @AutoConfigureMockMvc @Import(Phase05FloatingResidenceIntegrationTest.ClockConfig.class) class Phase05FloatingResidenceIntegrationTest {
@TestConfiguration static class ClockConfig{@Bean@Primary Clock fixedClock(){return Clock.fixed(Instant.parse("2026-07-11T00:00:00Z"),ZoneOffset.UTC);}}
@Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired JdbcTemplate jdbc;@Autowired ResidencePermitExpiryService expiry;@MockBean FloatingResidenceTransactionHook hook;
@BeforeEach void setup(){reset(hook);jdbc.update("DELETE FROM residence_permit_log");jdbc.update("DELETE FROM residence_permit_application");jdbc.update("DELETE FROM residence_permit");jdbc.update("DELETE FROM floating_population");jdbc.update("DELETE FROM floating_registration_application");jdbc.update("DELETE FROM residence_archive");jdbc.update("DELETE FROM cancellation_record");jdbc.update("DELETE FROM migration_in");jdbc.update("DELETE FROM migration_out");jdbc.update("DELETE FROM residence");jdbc.update("DELETE FROM household_member");jdbc.update("DELETE FROM sys_approval_log");jdbc.update("DELETE FROM sys_approval_request");jdbc.update("DELETE FROM application_material");jdbc.update("DELETE FROM business_application");jdbc.update("DELETE FROM operation_log");jdbc.update("DELETE FROM person WHERE person_id>=301");jdbc.update("INSERT INTO person(person_id,name,gender,id_card,phone,current_address,status,current_status_code) VALUES(301,'流动甲','1','370101199001010011','13800138000','原址','正常','MIGRATED_OUT'),(302,'注销乙','2','370101199202020022','13900139000',NULL,'正常','CANCELLED'),(303,'死亡丙','1','370101199303030033',NULL,NULL,'正常','DECEASED')");}
@Test void l2CanCreateFloatingApplication()throws Exception{assertThat(createFloating("population",301,201)).isPositive();}
@Test void l1CannotCreateFloatingApplication()throws Exception{createFloating("viewer",301,403);}
@Test void specializedFloatingCreationCreatesBothRecords()throws Exception{long id=createFloating("population",301,201);assertThat(count("business_application","application_id",id)).isOne();assertThat(count("floating_registration_application","application_id",id)).isOne();}
@Test void cancelledPersonCannotCreate()throws Exception{createFloating("population",302,409);}
@Test void deceasedPersonCannotCreate()throws Exception{createFloating("population",303,409);}
@Test void plannedLeaveBeforeArrivalRejected()throws Exception{mvc.perform(post("/api/floating-registrations/applications").header("Authorization",bearer(token("population"))).contentType(MediaType.APPLICATION_JSON).content(floatingJson(301).replace("2027-01-01","2025-01-01"))).andExpect(status().isBadRequest());}
@Test void genericEntryRejectsFloatingRegistration()throws Exception{genericReject("FLOATING_REGISTRATION");}
@Test void genericEntryRejectsPermitFirstIssue()throws Exception{genericReject("RESIDENCE_PERMIT_FIRST_ISSUE");}
@Test void genericEntryRejectsPermitEndorsement()throws Exception{genericReject("RESIDENCE_PERMIT_ENDORSEMENT");}
@Test void genericEntryRejectsPermitCancellation()throws Exception{genericReject("RESIDENCE_PERMIT_CANCELLATION");}
@Test void missingRequiredMaterialsBlocksSubmit()throws Exception{long id=createFloating("population",301,201);submit(id,"population",409);}
@Test void approvalDoesNotAutomaticallyCreateFloatingPopulation()throws Exception{long id=approvedFloating();assertThat(appStatus(id)).isEqualTo("APPROVED");assertThat(count("floating_population","source_application_id",id)).isZero();}
@Test void executeCreatesActiveRegistrationAndConfiguredEligibility()throws Exception{long id=approvedFloating();executeFloating(id,200);assertThat(jdbc.queryForObject("SELECT status FROM floating_population WHERE source_application_id=?",String.class,id)).isEqualTo("ACTIVE");assertThat(jdbc.queryForObject("SELECT eligible_from_date FROM floating_population WHERE source_application_id=?",LocalDate.class,id)).isEqualTo(LocalDate.of(2026,6,30));assertThat(jdbc.queryForObject("SELECT registration_no FROM floating_population WHERE source_application_id=?",String.class,id)).startsWith("FR-20260711-");}
@Test void executeDoesNotCreateResidenceOrHouseholdMember()throws Exception{long id=approvedFloating();executeFloating(id,200);assertThat(count("residence","person_id",301)).isZero();assertThat(count("household_member","person_id",301)).isZero();}
@Test void duplicateExecutionOnlySucceedsOnce()throws Exception{long id=approvedFloating();executeFloating(id,200);executeFloating(id,409);assertThat(count("floating_population","person_id",301)).isOne();}
@Test void duplicateActiveRegistrationRejected()throws Exception{long first=approvedFloating();executeFloating(first,200);long second=approvedFloating();executeFloating(second,409);}
@Test void localResidenceInSameRegionBlocksExecution()throws Exception{jdbc.update("INSERT INTO household(household_id,household_no,address,region_code,establish_date,status,version) VALUES(301,'HF301','本区地址','110000',DATE '2020-01-01','ACTIVE',0)");jdbc.update("INSERT INTO residence(person_id,household_id,registered_address,region_code,register_type_code,register_date,start_date,status,version) VALUES(301,301,'本区地址','110000','OTHER',DATE '2020-01-01',DATE '2020-01-01','ACTIVE',0)");long id=approvedFloating();executeFloating(id,409);}
@Test void floatingExecutionRollbackIsComplete()throws Exception{long id=approvedFloating();doThrow(new IllegalStateException("rollback")).when(hook).afterFloatingInsert();executeFloating(id,500);assertThat(count("floating_population","source_application_id",id)).isZero();assertThat(appStatus(id)).isEqualTo("APPROVED");}
@Test void queryMasksIdentityForL2()throws Exception{long id=approvedFloating();executeFloating(id,200);mvc.perform(get("/api/floating-populations?status=ACTIVE").header("Authorization",bearer(token("population")))).andExpect(status().isOk()).andExpect(jsonPath("$.data.content[0].identityNo").value("3701**********0011"));}
@Test void firstIssueSelectableFloatingExcludesPeopleWithActivePermit()throws Exception{issuedPermitFlow();mvc.perform(get("/api/floating-populations?status=ACTIVE&availableForFirstIssue=true").header("Authorization",bearer(token("population")))).andExpect(status().isOk()).andExpect(jsonPath("$.data.content").isEmpty());}
@Test void firstIssueRequiresExistingFloating()throws Exception{createFirst(999,404);}
@Test void firstIssueCreatesGenericAndProfessionalRecords()throws Exception{long f=executedFloating();long id=createFirst(f,201);assertThat(count("residence_permit_application","application_id",id)).isOne();assertThat(jdbc.queryForObject("SELECT apply_type FROM residence_permit_application WHERE application_id=?",String.class,id)).isEqualTo("FIRST_ISSUE");}
@Test void familyReunionFirstIssueRequiresRelationshipProofInsteadOfOtherSupportingDocument()throws Exception{String body=mvc.perform(post("/api/floating-registrations/applications").header("Authorization",bearer(token("population"))).contentType(MediaType.APPLICATION_JSON).content(floatingJson(301).replace("\"EMPLOYMENT\"","\"FAMILY_REUNION\""))).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();long floatingApplicationId=json.readTree(body).path("data").path("applicationId").asLong();for(String type:List.of("APPLICANT_IDENTITY_PROOF","RESIDENCE_ADDRESS_PROOF","FAMILY_RELATIONSHIP_PROOF"))material(floatingApplicationId,type);submitApprove(floatingApplicationId,"population");executeFloating(floatingApplicationId,200);long floatingId=jdbc.queryForObject("SELECT floating_id FROM floating_population WHERE source_application_id=?",Long.class,floatingApplicationId);long permitApplicationId=createFirst(floatingId,201);for(String type:List.of("APPLICANT_IDENTITY_PROOF","PERSON_PHOTO","RESIDENCE_ADDRESS_PROOF","FAMILY_RELATIONSHIP_PROOF"))material(permitApplicationId,type);submit(permitApplicationId,"population",200);}
@Test void permitProfessionalDetailUsesGenericApplicationId()throws Exception{long f=executedFloating();long id=createFirst(f,201);mvc.perform(get("/api/residence-permits/applications/"+id).header("Authorization",bearer(token("population")))).andExpect(status().isOk()).andExpect(jsonPath("$.data.professional.applicationId").value(id));}
@Test void missingPermitProfessionalDetailReturns404()throws Exception{long f=executedFloating();long id=createFirst(f,201);jdbc.update("DELETE FROM residence_permit_application WHERE application_id=?",id);mvc.perform(get("/api/residence-permits/applications/"+id).header("Authorization",bearer(token("population")))).andExpect(status().isNotFound()).andExpect(jsonPath("$.message").value("居住证专业详情不存在"));}
@Test void permitApprovalDoesNotAutomaticallyIssue()throws Exception{long f=executedFloating();long id=approvedFirst(f);assertThat(count("residence_permit","source_application_id",id)).isZero();}
@Test void issueCreatesPermitAndIssueLog()throws Exception{long f=executedFloating();long id=approvedFirst(f);issue(id,200);assertThat(jdbc.queryForObject("SELECT permit_no FROM residence_permit WHERE source_application_id=?",String.class,id)).startsWith("RP-20260711-");assertThat(jdbc.queryForObject("SELECT valid_until FROM residence_permit WHERE source_application_id=?",LocalDate.class,id)).isEqualTo(LocalDate.of(2027,7,11));assertThat(jdbc.queryForObject("SELECT action FROM residence_permit_log",String.class)).isEqualTo("ISSUE");assertThat(count("certificate","person_id",301)).isZero();}
@Test void issueRollbackAfterInsertRemovesPermit()throws Exception{long f=executedFloating();long id=approvedFirst(f);doThrow(new IllegalStateException("rollback")).when(hook).afterPermitInsert();issue(id,500);assertThat(count("residence_permit","source_application_id",id)).isZero();assertThat(appStatus(id)).isEqualTo("APPROVED");}
@Test void duplicateActivePermitRejected()throws Exception{long f=executedFloating();long one=approvedFirst(f);issue(one,200);createFirst(f,409);}
@Test void closeRegistrationCancelsPermitAndWritesLog()throws Exception{long f=issuedPermitFlow();long permit=jdbc.queryForObject("SELECT permit_id FROM residence_permit",Long.class);mvc.perform(post("/api/floating-populations/"+f+"/close").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"reasonCode\":\"LEFT_REGION\",\"comment\":\"离开本区\",\"version\":0}")).andExpect(status().isOk());assertThat(jdbc.queryForObject("SELECT status FROM residence_permit WHERE permit_id=?",String.class,permit)).isEqualTo("CANCELLED");assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM residence_permit_log WHERE action='REGISTRATION_CLOSED'",Integer.class)).isOne();}
@Test void closeRollbackRestoresRegistration()throws Exception{long f=executedFloating();doThrow(new IllegalStateException("rollback")).when(hook).afterFloatingClose();mvc.perform(post("/api/floating-populations/"+f+"/close").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"reasonCode\":\"LEFT_REGION\",\"comment\":\"离开\",\"version\":0}")).andExpect(status().is5xxServerError());assertThat(jdbc.queryForObject("SELECT status FROM floating_population WHERE floating_id=?",String.class,f)).isEqualTo("ACTIVE");}
@Test void expiryTaskExpiresPermitOnce()throws Exception{long f=issuedPermitFlow();jdbc.update("UPDATE residence_permit SET valid_until=DATE '2026-07-10'");expiry.runNow();expiry.runNow();assertThat(jdbc.queryForObject("SELECT status FROM residence_permit",String.class)).isEqualTo("EXPIRED");assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM residence_permit_log WHERE action='EXPIRE'",Integer.class)).isOne();}
@Test void plannedLeaveExpiryKeepsRegistrationHistory()throws Exception{long f=executedFloating();jdbc.update("UPDATE floating_population SET planned_leave_date=DATE '2026-07-10' WHERE floating_id=?",f);expiry.runNow();assertThat(jdbc.queryForObject("SELECT status FROM floating_population WHERE floating_id=?",String.class,f)).isEqualTo("EXPIRED");assertThat(count("floating_population","floating_id",f)).isOne();}
@Test void executionWritesOperationAndApprovalLogs()throws Exception{long id=approvedFloating();executeFloating(id,200);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM operation_log WHERE operation_type='FLOATING_RESIDENCE_EXECUTE'",Integer.class)).isOne();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM sys_approval_log WHERE application_id=? AND action='EXECUTE'",Integer.class,id)).isOne();}
@Test void endorsementOutsideWindowRejected()throws Exception{issuedPermitFlow();long permit=permitId();long id=approvedPermitAction(permit,"endorsement");executePermitAction(id,"endorse",409);}
@Test void endorsementUpdatesValidityAndWritesLog()throws Exception{issuedPermitFlow();long permit=permitId();jdbc.update("UPDATE residence_permit SET valid_until=DATE '2026-07-20' WHERE permit_id=?",permit);long id=approvedPermitAction(permit,"endorsement");executePermitAction(id,"endorse",200);assertThat(jdbc.queryForObject("SELECT valid_until FROM residence_permit WHERE permit_id=?",LocalDate.class,permit)).isEqualTo(LocalDate.of(2027,7,20));assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM residence_permit_log WHERE action='ENDORSE'",Integer.class)).isOne();}
@Test void endorsementRollbackRestoresValidity()throws Exception{issuedPermitFlow();long permit=permitId();jdbc.update("UPDATE residence_permit SET valid_until=DATE '2026-07-20' WHERE permit_id=?",permit);long id=approvedPermitAction(permit,"endorsement");doThrow(new IllegalStateException("rollback")).when(hook).afterPermitUpdate();executePermitAction(id,"endorse",500);assertThat(jdbc.queryForObject("SELECT valid_until FROM residence_permit WHERE permit_id=?",LocalDate.class,permit)).isEqualTo(LocalDate.of(2026,7,20));}
@Test void cancellationClearsCurrentFlagAndWritesLog()throws Exception{issuedPermitFlow();long permit=permitId();long id=approvedPermitAction(permit,"cancellation");executePermitAction(id,"cancel",200);assertThat(jdbc.queryForObject("SELECT status FROM residence_permit WHERE permit_id=?",String.class,permit)).isEqualTo("CANCELLED");assertThat(jdbc.queryForObject("SELECT current_flag FROM residence_permit WHERE permit_id=?",Integer.class,permit)).isNull();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM residence_permit_log WHERE action='CANCEL'",Integer.class)).isOne();}
@Test void cancellationRollbackRestoresPermit()throws Exception{issuedPermitFlow();long permit=permitId();long id=approvedPermitAction(permit,"cancellation");doThrow(new IllegalStateException("rollback")).when(hook).afterPermitUpdate();executePermitAction(id,"cancel",500);assertThat(jdbc.queryForObject("SELECT status FROM residence_permit WHERE permit_id=?",String.class,permit)).isEqualTo("ACTIVE");}
@Test void expiryRollbackRestoresPermitAndDoesNotLog()throws Exception{issuedPermitFlow();long permit=permitId();jdbc.update("UPDATE residence_permit SET valid_until=DATE '2026-07-10' WHERE permit_id=?",permit);doThrow(new IllegalStateException("rollback")).when(hook).afterPermitExpire();assertThatThrownBy(()->expiry.runNow()).isInstanceOf(IllegalStateException.class);assertThat(jdbc.queryForObject("SELECT status FROM residence_permit WHERE permit_id=?",String.class,permit)).isEqualTo("ACTIVE");assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM residence_permit_log WHERE action='EXPIRE'",Integer.class)).isZero();}
private long approvedFloating()throws Exception{long id=createFloating("population",301,201);for(String x:List.of("APPLICANT_IDENTITY_PROOF","RESIDENCE_ADDRESS_PROOF","EMPLOYMENT_PROOF"))material(id,x);submitApprove(id,"population");return id;}private long executedFloating()throws Exception{long id=approvedFloating();executeFloating(id,200);return jdbc.queryForObject("SELECT floating_id FROM floating_population WHERE source_application_id=?",Long.class,id);}private long issuedPermitFlow()throws Exception{long f=executedFloating();long id=approvedFirst(f);issue(id,200);return f;}private long approvedFirst(long f)throws Exception{long id=createFirst(f,201);for(String x:List.of("APPLICANT_IDENTITY_PROOF","PERSON_PHOTO","RESIDENCE_ADDRESS_PROOF","EMPLOYMENT_PROOF"))material(id,x);submitApprove(id,"population");return id;}
private long createFloating(String user,long person,int expected)throws Exception{String b=mvc.perform(post("/api/floating-registrations/applications").header("Authorization",bearer(token(user))).contentType(MediaType.APPLICATION_JSON).content(floatingJson(person))).andExpect(status().is(expected)).andReturn().getResponse().getContentAsString();return expected==201?json.readTree(b).path("data").path("applicationId").asLong():0;}private String floatingJson(long person){return "{\"personId\":"+person+",\"sourceRegionCode\":\"370100\",\"sourceAddress\":\"山东示例\",\"currentRegionCode\":\"110000\",\"currentAddress\":\"北京示例\",\"residenceReasonCode\":\"EMPLOYMENT\",\"residenceProofType\":\"RENTAL_CONTRACT\",\"arrivalDate\":\"2026-01-01\",\"plannedLeaveDate\":\"2027-01-01\",\"applicantPhone\":\"13800138000\",\"title\":\"流动登记\",\"reason\":\"就业居住\"}";}
private long createFirst(long f,int expected)throws Exception{String b=mvc.perform(post("/api/residence-permits/applications/first-issue").header("Authorization",bearer(token("population"))).contentType(MediaType.APPLICATION_JSON).content("{\"floatingId\":"+f+",\"residenceBasisCode\":\"EMPLOYMENT\",\"title\":\"首次申领\",\"reason\":\"符合条件\"}")).andExpect(status().is(expected)).andReturn().getResponse().getContentAsString();return expected==201?json.readTree(b).path("data").path("applicationId").asLong():0;}private void executeFloating(long id,int expected)throws Exception{mvc.perform(post("/api/floating-registrations/applications/"+id+"/execute").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"version\":2}")).andExpect(status().is(expected));}private void issue(long id,int expected)throws Exception{mvc.perform(post("/api/residence-permits/applications/"+id+"/issue").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"issuingAuthority\":\"示例公安机关\",\"version\":2}")).andExpect(status().is(expected));}
private long permitId(){return jdbc.queryForObject("SELECT permit_id FROM residence_permit",Long.class);}private long approvedPermitAction(long permit,String action)throws Exception{String b=mvc.perform(post("/api/residence-permits/applications/"+permit+"/"+action).header("Authorization",bearer(token("population"))).contentType(MediaType.APPLICATION_JSON).content("{\"title\":\"居住证业务\",\"reason\":\"课程申请\"}")).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();long id=json.readTree(b).path("data").path("applicationId").asLong();for(String x:action.equals("endorsement")?List.of("CURRENT_RESIDENCE_PERMIT","CONTINUED_RESIDENCE_PROOF"):List.of("CURRENT_RESIDENCE_PERMIT","CANCELLATION_APPLICATION"))material(id,x);submitApprove(id,"population");return id;}private void executePermitAction(long id,String action,int expected)throws Exception{mvc.perform(post("/api/residence-permits/applications/"+id+"/"+action).header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"version\":2}")).andExpect(status().is(expected));}
private void genericReject(String type)throws Exception{mvc.perform(post("/api/applications").header("Authorization",bearer(token("population"))).contentType(MediaType.APPLICATION_JSON).content("{\"businessType\":\""+type+"\",\"title\":\"非法入口\",\"reason\":\"测试\"}")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.message").value("该业务必须通过对应的专业业务入口创建"));}private void material(long id,String type){String hash=UUID.randomUUID().toString().replace("-","")+UUID.randomUUID().toString().replace("-","");jdbc.update("INSERT INTO application_material(application_id,material_type,material_name,original_filename,stored_filename,storage_path,content_type,file_size,file_sha256,required_flag,verify_status,verify_user_id,uploaded_by) VALUES(?,?,?,'x.pdf',?,?,'application/pdf',1,?,1,'VERIFIED',7,6)",id,type,type,UUID.randomUUID()+".pdf","test",hash);}private void submitApprove(long id,String user)throws Exception{submit(id,user,200);long approval=jdbc.queryForObject("SELECT approval_id FROM sys_approval_request WHERE application_id=?",Long.class,id);mvc.perform(post("/api/approvals/"+approval+"/approve").header("Authorization",bearer(token("approver"))).contentType(MediaType.APPLICATION_JSON).content("{\"comment\":\"同意\",\"version\":0}")).andExpect(status().isOk());}private void submit(long id,String user,int expected)throws Exception{mvc.perform(post("/api/applications/"+id+"/submit").header("Authorization",bearer(token(user)))).andExpect(status().is(expected));}
private int count(String table,String key,long id){return jdbc.queryForObject("SELECT COUNT(*) FROM "+table+" WHERE "+key+"=?",Integer.class,id);}private String appStatus(long id){return jdbc.queryForObject("SELECT status FROM business_application WHERE application_id=?",String.class,id);}private String token(String user)throws Exception{String b=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"username\":\""+user+"\",\"password\":\"123456\"}")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();return json.readTree(b).path("data").path("token").asText();}private String bearer(String t){return "Bearer "+t;}}
