package com.wjx871.population.reference;import com.fasterxml.jackson.databind.*;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.*;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.http.MediaType;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.test.web.servlet.MockMvc;import static org.assertj.core.api.Assertions.assertThat;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest@AutoConfigureMockMvc@TestMethodOrder(MethodOrderer.OrderAnnotation.class)class Phase09DataDictionaryIntegrationTest{@Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired JdbcTemplate jdbc;static long id;
@Test@Order(1)void ordinaryReadsEnabledOnly()throws Exception{String b=mvc.perform(get("/api/dictionaries/CERTIFICATE_TYPE").header("Authorization",bearer("viewer"))).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();assertThat(b).contains("PASSPORT").doesNotContain("DISABLED_TEST");}
@Test@Order(2)void adminCanListDisabled()throws Exception{mvc.perform(get("/api/dictionaries").param("status","DISABLED").header("Authorization",bearer("admin"))).andExpect(status().isOk()).andExpect(jsonPath("$.data.totalElements").value(1));}
@Test@Order(3)void viewerCannotManage()throws Exception{mvc.perform(post("/api/dictionaries").header("Authorization",bearer("viewer")).contentType(MediaType.APPLICATION_JSON).content(create())).andExpect(status().isForbidden());}
@Test@Order(4)void createAndAudit()throws Exception{String b=mvc.perform(post("/api/dictionaries").header("Authorization",bearer("admin")).contentType(MediaType.APPLICATION_JSON).content(create())).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();id=json.readTree(b).path("data").path("dictId").asLong();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM operation_log WHERE operation_type='DICTIONARY_CREATE'",Integer.class)).isGreaterThan(0);}
@Test@Order(5)void duplicateRejected()throws Exception{mvc.perform(post("/api/dictionaries").header("Authorization",bearer("admin")).contentType(MediaType.APPLICATION_JSON).content(create())).andExpect(status().isConflict());}
@Test@Order(6)void update()throws Exception{mvc.perform(put("/api/dictionaries/"+id).header("Authorization",bearer("admin")).contentType(MediaType.APPLICATION_JSON).content("{\"displayName\":\"测试值更新\",\"sortNo\":2,\"version\":0}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.dictName").value("测试值更新"));}
@Test@Order(7)void disableHidesFromOrdinary()throws Exception{mvc.perform(post("/api/dictionaries/"+id+"/disable").header("Authorization",bearer("admin")).contentType(MediaType.APPLICATION_JSON).content("{\"version\":1}")).andExpect(status().isOk());mvc.perform(get("/api/dictionaries/TEST_TYPE/TEST_CODE").header("Authorization",bearer("viewer"))).andExpect(status().isNotFound());}
@Test@Order(8)void enable()throws Exception{mvc.perform(post("/api/dictionaries/"+id+"/enable").header("Authorization",bearer("admin")).contentType(MediaType.APPLICATION_JSON).content("{\"version\":2}")).andExpect(status().isOk());}
@Test@Order(9)void typeAndCodeRequired()throws Exception{mvc.perform(post("/api/dictionaries").header("Authorization",bearer("admin")).contentType(MediaType.APPLICATION_JSON).content("{\"dictionaryType\":\"\",\"dictionaryCode\":\"\",\"displayName\":\"x\",\"sortNo\":0}")).andExpect(status().isBadRequest());}
@Test@Order(10)void pageableFilter()throws Exception{mvc.perform(get("/api/dictionaries").param("dictionaryType","CERTIFICATE_TYPE").param("page","0").param("size","2").header("Authorization",bearer("viewer"))).andExpect(status().isOk()).andExpect(jsonPath("$.data.content.length()").value(2));}
@Test@Order(11)void disabledTypeCannotBeResolvedForNewBusiness(){DataDictionaryMapper m=null;assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM data_dictionary WHERE dict_type='CERTIFICATE_TYPE' AND dict_code='DISABLED_TEST' AND status='ENABLED'",Integer.class)).isZero();}
private String create(){return"{\"dictionaryType\":\"TEST_TYPE\",\"dictionaryCode\":\"TEST_CODE\",\"displayName\":\"测试值\",\"sortNo\":1}";}private String bearer(String u)throws Exception{String b=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"username\":\""+u+"\",\"password\":\"123456\"}")).andReturn().getResponse().getContentAsString();return"Bearer "+json.readTree(b).path("data").path("token").asText();}}
