package com.wjx871.population.reference;
import com.fasterxml.jackson.databind.*;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.*;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.http.MediaType;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.test.web.servlet.MockMvc;import static org.assertj.core.api.Assertions.assertThat;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest@AutoConfigureMockMvc@TestMethodOrder(MethodOrderer.OrderAnnotation.class)class Phase09AdminRegionIntegrationTest{@Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired JdbcTemplate jdbc;
@Test@Order(1)void rootsAndStableSort()throws Exception{String b=mvc.perform(get("/api/admin-regions").param("regionLevel","1").header("Authorization",bearer("viewer"))).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();JsonNode a=json.readTree(b).path("data");assertThat(a.size()).isGreaterThanOrEqualTo(2);assertThat(a.get(0).path("regionCode").asText()).isEqualTo("110000");}
@Test@Order(2)void childrenAndTreeWithoutScopeTruncation()throws Exception{mvc.perform(get("/api/admin-regions/110100/children").header("Authorization",bearer("viewer"))).andExpect(status().isOk()).andExpect(jsonPath("$.data[0].regionCode").value("110101"));String b=mvc.perform(get("/api/admin-regions/tree").header("Authorization",bearer("viewer"))).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();assertThat(b).contains("110105001001").contains("120000");}
@Test@Order(3)void detail()throws Exception{mvc.perform(get("/api/admin-regions/110105").header("Authorization",bearer("viewer"))).andExpect(status().isOk()).andExpect(jsonPath("$.data.parentCode").value("110100"));}
@Test@Order(4)void viewerCannotManage()throws Exception{mvc.perform(post("/api/admin-regions").header("Authorization",bearer("viewer")).contentType(MediaType.APPLICATION_JSON).content(create("119900","110000",2))).andExpect(status().isForbidden());}
@Test@Order(5)void createAndAudit()throws Exception{mvc.perform(post("/api/admin-regions").header("Authorization",bearer("admin")).contentType(MediaType.APPLICATION_JSON).content(create("119900","110000",2))).andExpect(status().isCreated());assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM operation_log WHERE operation_type='REGION_CREATE'",Integer.class)).isGreaterThan(0);}
@Test@Order(6)void duplicateCode()throws Exception{mvc.perform(post("/api/admin-regions").header("Authorization",bearer("admin")).contentType(MediaType.APPLICATION_JSON).content(create("119900","110000",2))).andExpect(status().isConflict());}
@Test@Order(7)void missingParent()throws Exception{mvc.perform(post("/api/admin-regions").header("Authorization",bearer("admin")).contentType(MediaType.APPLICATION_JSON).content(create("119901","NOPE",2))).andExpect(status().isNotFound());}
@Test@Order(8)void invalidLevel()throws Exception{mvc.perform(post("/api/admin-regions").header("Authorization",bearer("admin")).contentType(MediaType.APPLICATION_JSON).content(create("119902","110000",1))).andExpect(status().isBadRequest());}
@Test@Order(9)void selfCycleRejected()throws Exception{mvc.perform(put("/api/admin-regions/119900").header("Authorization",bearer("admin")).contentType(MediaType.APPLICATION_JSON).content("{\"regionName\":\"循环\",\"parentCode\":\"119900\",\"regionLevel\":3,\"fullName\":\"循环\",\"sortNo\":1,\"version\":0}")).andExpect(status().isBadRequest());}
@Test@Order(10)void enabledChildBlocksDisable()throws Exception{mvc.perform(post("/api/admin-regions/110100/disable").header("Authorization",bearer("admin")).contentType(MediaType.APPLICATION_JSON).content("{\"version\":0}")).andExpect(status().isConflict());}
@Test@Order(11)void disableAndEnableLeaf()throws Exception{mvc.perform(post("/api/admin-regions/119900/disable").header("Authorization",bearer("admin")).contentType(MediaType.APPLICATION_JSON).content("{\"version\":0}")).andExpect(status().isOk());mvc.perform(post("/api/admin-regions/119900/enable").header("Authorization",bearer("admin")).contentType(MediaType.APPLICATION_JSON).content("{\"version\":1}")).andExpect(status().isOk());}
private String create(String c,String p,int l){return "{\"regionCode\":\""+c+"\",\"regionName\":\"测试区划\",\"parentCode\":\""+p+"\",\"regionLevel\":"+l+",\"fullName\":\"示例省测试区划\",\"sortNo\":99}";}private String bearer(String u)throws Exception{String b=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"username\":\""+u+"\",\"password\":\"123456\"}")).andReturn().getResponse().getContentAsString();return"Bearer "+json.readTree(b).path("data").path("token").asText();}}
