package com.wjx871.population.floating;import com.wjx871.population.common.ApiResponse;import jakarta.servlet.http.HttpServletRequest;import jakarta.validation.Valid;import lombok.RequiredArgsConstructor;import org.springframework.data.domain.*;import org.springframework.http.HttpStatus;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;
@RestController @RequiredArgsConstructor public class FloatingRegistrationController {private final FloatingResidenceService service;
@PostMapping("/api/floating-registrations/applications")@ResponseStatus(HttpStatus.CREATED)@PreAuthorize("hasAuthority('floating:create')")public ApiResponse<FloatingCreatedView> create(@Valid@RequestBody FloatingRegistrationRequest q,HttpServletRequest h){return ApiResponse.created(service.createFloating(q,h));}
@PutMapping("/api/floating-registrations/applications/{id}")@PreAuthorize("hasAuthority('floating:edit') and hasAuthority('application:edit')")public ApiResponse<FloatingCreatedView> update(@PathVariable Long id,@Valid@RequestBody FloatingRegistrationRequest q){return ApiResponse.ok(service.updateFloating(id,q));}
@GetMapping("/api/floating-registrations/applications/{id}")@PreAuthorize("hasAuthority('floating:view')")public ApiResponse<FloatingDetailView> application(@PathVariable Long id){return ApiResponse.ok(service.floatingApplication(id));}
@PostMapping("/api/floating-registrations/applications/{id}/execute")@PreAuthorize("hasAuthority('floating:execute')")public ApiResponse<FloatingPopulation> execute(@PathVariable Long id,@Valid@RequestBody VersionRequest q,HttpServletRequest h){return ApiResponse.ok(service.executeFloating(id,q.version(),h));}
@GetMapping("/api/floating-populations")@PreAuthorize("hasAuthority('floating:view')")public ApiResponse<Page<FloatingPopulation>> search(@RequestParam(required=false)String registrationNo,@RequestParam(required=false)String personName,@RequestParam(required=false)String identityNo,@RequestParam(required=false)String currentRegionCode,@RequestParam(required=false)String status,@RequestParam(required=false,defaultValue="false")Boolean availableForFirstIssue,@RequestParam(required=false,defaultValue="false")Boolean includeHistory,Pageable p){return ApiResponse.ok(service.floatingSearch(registrationNo,personName,identityNo,currentRegionCode,status,Boolean.TRUE.equals(availableForFirstIssue),Boolean.TRUE.equals(includeHistory),p));}
@GetMapping("/api/floating-populations/{id}")@PreAuthorize("hasAuthority('floating:view')")public ApiResponse<FloatingPopulation> detail(@PathVariable Long id){return ApiResponse.ok(service.floating(id));}
@PostMapping("/api/floating-populations/{id}/close")@PreAuthorize("hasAuthority('floating:close')")public ApiResponse<Void> close(@PathVariable Long id,@Valid@RequestBody CloseRegistrationRequest q,HttpServletRequest h){service.closeFloating(id,q,h);return ApiResponse.ok(null);}}
