package com.wjx871.population.floating;import com.wjx871.population.common.ApiResponse;import jakarta.servlet.http.HttpServletRequest;import jakarta.validation.Valid;import java.time.LocalDate;import java.util.List;import lombok.RequiredArgsConstructor;import org.springframework.data.domain.*;import org.springframework.format.annotation.DateTimeFormat;import org.springframework.http.HttpStatus;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/residence-permits") @RequiredArgsConstructor public class ResidencePermitController {private final FloatingResidenceService service;
@PostMapping("/applications/first-issue")@ResponseStatus(HttpStatus.CREATED)@PreAuthorize("hasAuthority('residence-permit:apply')")public ApiResponse<FloatingCreatedView> first(@Valid@RequestBody PermitApplicationRequest q,HttpServletRequest h){return ApiResponse.created(service.createFirstIssue(q,h));}
@PostMapping("/applications/{permitId}/endorsement")@ResponseStatus(HttpStatus.CREATED)@PreAuthorize("hasAuthority('residence-permit:apply')")public ApiResponse<FloatingCreatedView> endorsement(@PathVariable Long permitId,@Valid@RequestBody PermitApplicationRequest q,HttpServletRequest h){return ApiResponse.created(service.createEndorsement(permitId,q,h));}
@PostMapping("/applications/{permitId}/cancellation")@ResponseStatus(HttpStatus.CREATED)@PreAuthorize("hasAuthority('residence-permit:apply')")public ApiResponse<FloatingCreatedView> cancellation(@PathVariable Long permitId,@Valid@RequestBody PermitApplicationRequest q,HttpServletRequest h){return ApiResponse.created(service.createCancellation(permitId,q,h));}
@PutMapping("/applications/{id}")@PreAuthorize("hasAuthority('application:edit') and hasAuthority('residence-permit:apply')")public ApiResponse<FloatingCreatedView> update(@PathVariable Long id,@Valid@RequestBody PermitApplicationRequest q){return ApiResponse.ok(service.updatePermitApplication(id,q));}
@GetMapping("/applications/{id}")@PreAuthorize("hasAuthority('residence-permit:view')")public ApiResponse<FloatingDetailView> application(@PathVariable Long id){return ApiResponse.ok(service.permitApplication(id));}
@PostMapping("/applications/{id}/issue")@PreAuthorize("hasAuthority('residence-permit:issue')")public ApiResponse<ResidencePermit> issue(@PathVariable Long id,@Valid@RequestBody IssuePermitRequest q,HttpServletRequest h){return ApiResponse.ok(service.issue(id,q,h));}
@PostMapping("/applications/{id}/endorse")@PreAuthorize("hasAuthority('residence-permit:endorse')")public ApiResponse<ResidencePermit> endorse(@PathVariable Long id,@Valid@RequestBody VersionRequest q,HttpServletRequest h){return ApiResponse.ok(service.endorse(id,q.version(),h));}
@PostMapping("/applications/{id}/cancel")@PreAuthorize("hasAuthority('residence-permit:cancel')")public ApiResponse<Void> cancel(@PathVariable Long id,@Valid@RequestBody VersionRequest q,HttpServletRequest h){service.cancelPermitApplication(id,q.version(),h);return ApiResponse.ok(null);}
@GetMapping@PreAuthorize("hasAuthority('residence-permit:view')")public ApiResponse<Page<ResidencePermit>> search(@RequestParam(required=false)String permitNo,@RequestParam(required=false)String personName,@RequestParam(required=false)String identityNo,@RequestParam(required=false)String currentRegionCode,@RequestParam(required=false)String status,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate validFrom,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate validTo,Pageable p){return ApiResponse.ok(service.permitSearch(permitNo,personName,identityNo,currentRegionCode,status,validFrom,validTo,p));}
@GetMapping("/expiring")@PreAuthorize("hasAuthority('residence-permit:expiry:view')")public ApiResponse<List<ExpiringPermitView>> expiring(@RequestParam(required=false)Integer days){return ApiResponse.ok(service.expiring(days));}
@GetMapping("/{id}")@PreAuthorize("hasAuthority('residence-permit:view')")public ApiResponse<ResidencePermit> detail(@PathVariable Long id){return ApiResponse.ok(service.permit(id));}
@GetMapping("/{id}/logs")@PreAuthorize("hasAuthority('residence-permit:log:view')")public ApiResponse<List<ResidencePermitLog>> logs(@PathVariable Long id){return ApiResponse.ok(service.logs(id));}}
