<template>
  <div class="page-container">
    <div class="page-header"><div><h1>{{ title }}</h1><p class="subtitle">展示申请状态，不直接创建或删除已生效迁移记录。</p></div><el-button v-if="canCreate" type="primary" :icon="Plus" @click="router.push(`${route.path}/apply`)">发起{{ isIn ? '迁入' : '迁出' }}申请</el-button></div>
    <SearchPanel @search="fetchList" @reset="reset"><el-form :inline="true"><el-form-item label="申请状态"><el-select v-model="query.status" clearable style="width: 140px"><el-option v-for="(label, value) in APPLICATION_STATUS" :key="value" :label="label" :value="value" /></el-select></el-form-item><el-form-item label="申请编号"><el-input v-model.trim="query.applicationNo" clearable /></el-form-item></el-form></SearchPanel>
    <el-card shadow="never"><el-table :data="records" v-loading="loading" border stripe><el-table-column prop="applicationNo" label="申请编号" width="180" /><el-table-column prop="title" label="申请标题" min-width="180" show-overflow-tooltip /><el-table-column prop="applicantName" label="申请人" width="120" /><el-table-column label="状态" width="150"><template #default="{ row }"><StatusTag :value="row.status" /></template></el-table-column><el-table-column prop="createdAt" label="创建时间" min-width="170"><template #default="{ row }">{{ formatDateTime(row.createdAt) }}</template></el-table-column><el-table-column label="操作" width="150" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="view(row)">查看</el-button><el-button v-if="row.status === 'DRAFT' && canEdit" link type="primary" @click="edit(row)">编辑</el-button></template></el-table-column></el-table><AppPagination v-model:current="query.current" v-model:size="query.size" :total="total" @change="fetchList" /></el-card>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { Plus } from '@element-plus/icons-vue'
import SearchPanel from '../../components/common/SearchPanel.vue'; import AppPagination from '../../components/common/AppPagination.vue'; import StatusTag from '../../components/common/StatusTag.vue'
import { getApplicationPage } from '../../api/applications'; import { normalizeApplicationPage } from '../../adapters/application'; import { APPLICATION_STATUS, BUSINESS_TYPE } from '../../constants/application'; import { formatDateTime } from '../../utils/date'; import { useUserStore } from '../../stores/user'; import { PERMISSIONS } from '../../constants/permissions'
const route=useRoute();const router=useRouter();const userStore=useUserStore();const isIn=computed(()=>route.meta.type==='in');const title=computed(()=>isIn.value?'迁入申请':'迁出申请');const canCreate=computed(()=>userStore.hasPermission(isIn.value?PERMISSIONS.MIGRATION_IN_CREATE:PERMISSIONS.MIGRATION_OUT_CREATE));const canEdit=computed(()=>userStore.hasPermission(PERMISSIONS.APPLICATION_EDIT));const loading=ref(false);const records=ref([]);const total=ref(0);const query=reactive({applicationNo:'',status:'',current:1,size:10});
async function fetchList(){loading.value=true;try{const page=normalizeApplicationPage(await getApplicationPage({...query,businessType:isIn.value?BUSINESS_TYPE.MIGRATION_IN:BUSINESS_TYPE.MIGRATION_OUT}));records.value=page.records;total.value=page.total}finally{loading.value=false}}function reset(){query.applicationNo='';query.status='';query.current=1;fetchList()}function view(row){router.push(`/applications/${row.applicationId}`)}function edit(row){router.push({path:`${route.path}/apply`,query:{applicationId:row.applicationId}})}watch(isIn,reset);onMounted(fetchList)
</script>

<style scoped>.page-container{display:flex;flex-direction:column;gap:16px}.page-header{display:flex;justify-content:space-between;align-items:end}.page-header h1{margin:0 0 8px}.subtitle{margin:0;color:var(--el-text-color-secondary)}</style>
