package com.wjx871.population.certificate;import com.fasterxml.jackson.databind.*;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.*;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.http.MediaType;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.test.web.servlet.MockMvc;import static org.assertj.core.api.Assertions.assertThat;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest@AutoConfigureMockMvc@TestInstance(TestInstance.Lifecycle.PER_CLASS)@TestMethodOrder(MethodOrderer.OrderAnnotation.class)class Phase09CertificateIntegrationTest{@Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired JdbcTemplate jdbc;long activeId,cancelId;
@BeforeAll void data(){jdbc.update("INSERT INTO person(person_id,name,gender,id_card,birth_date,status,current_status_code) VALUES(9201,'证件甲','M','110105198001010016','1980-01-01','正常','REGISTERED'),(9202,'已注销乙','F','110105198002020024','1980-02-02','注销','CANCELLED'),(9203,'外区丙','M','120101198003030039','1980-03-03','正常','REGISTERED')");jdbc.update("INSERT INTO household(household_id,household_no,address,region_code,household_type,establish_date,status,version) VALUES(9201,'CERT-H1','示例地址','110105','FAMILY','2020-01-01','ACTIVE',0),(9202,'CERT-H2','外区地址','120101','FAMILY','2020-01-01','ACTIVE',0)");jdbc.update("INSERT INTO residence(person_id,household_id,registered_address,region_code,register_type_code,register_date,start_date,status,version) VALUES(9201,9201,'示例地址','110105','HOUSEHOLD','2020-01-01','2020-01-01','ACTIVE',0),(9203,9202,'外区地址','120101','HOUSEHOLD','2020-01-01','2020-01-01','ACTIVE',0)");}
@Test@Order(1)void create()throws Exception{String b=performCreate("population",9201,"PASSPORT","P123456789","2020-01-01","2030-01-01",201);activeId=json.readTree(b).path("data").path("certificateId").asLong();assertThat(b).contains("P123****6789").doesNotContain("P123456789");}
@Test@Order(2)void missingPerson()throws Exception{performCreate("admin",999999,"PASSPORT","P-MISSING-1","2020-01-01","2030-01-01",404);}
@Test@Order(3)void cancelledPerson()throws Exception{performCreate("admin",9202,"PASSPORT","P-CANCEL-1","2020-01-01","2030-01-01",409);}
@Test@Order(4)void duplicateNumber()throws Exception{performCreate("admin",9201,"PASSPORT","P123456789","2020-01-01","2030-01-01",409);}
@Test@Order(5)void residencePermitForbidden()throws Exception{performCreate("admin",9201,"RESIDENCE_PERMIT","RP12345678","2020-01-01","2030-01-01",400);}
@Test@Order(6)void disabledTypeForbidden()throws Exception{performCreate("admin",9201,"DISABLED_TEST","D12345678","2020-01-01","2030-01-01",400);}
@Test@Order(7)void futureIssueRejected()throws Exception{performCreate("admin",9201,"OTHER","O12345678","2999-01-01",null,400);}
@Test@Order(8)void invalidExpiryRejected()throws Exception{performCreate("admin",9201,"OTHER","O22345678","2025-01-01","2024-01-01",400);}
@Test@Order(9)void update()throws Exception{mvc.perform(put("/api/certificates/"+activeId).header("Authorization",bearer("population")).contentType(MediaType.APPLICATION_JSON).content("{\"certificateType\":\"PASSPORT\",\"certificateNo\":\"P987654321\",\"issueDate\":\"2020-01-01\",\"expireDate\":\"2031-01-01\",\"version\":0}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.version").value(1));}
@Test@Order(10)void listAndFilters()throws Exception{mvc.perform(get("/api/certificates").param("certificateType","PASSPORT").param("personName","证件甲").header("Authorization",bearer("population"))).andExpect(status().isOk()).andExpect(jsonPath("$.data.totalElements").value(1));}
@Test@Order(11)void personList()throws Exception{mvc.perform(get("/api/persons/9201/certificates").header("Authorization",bearer("population"))).andExpect(status().isOk()).andExpect(jsonPath("$.data.totalElements").value(1));}
@Test@Order(12)void expiringAndExpiredComputed()throws Exception{String b=performCreate("admin",9201,"OTHER","EXP1234567","2020-01-01","2020-01-02",201);long id=json.readTree(b).path("data").path("certificateId").asLong();mvc.perform(get("/api/certificates/"+id).header("Authorization",bearer("admin"))).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("EXPIRED"));mvc.perform(get("/api/certificates").param("status","EXPIRED").header("Authorization",bearer("admin"))).andExpect(status().isOk()).andExpect(jsonPath("$.data.totalElements").value(org.hamcrest.Matchers.greaterThanOrEqualTo(1)));}
@Test@Order(13)void dataScopeFiltersOtherRegion()throws Exception{String b=performCreate("admin",9203,"PASSPORT","OUT1234567","2020-01-01","2030-01-01",201);long id=json.readTree(b).path("data").path("certificateId").asLong();mvc.perform(get("/api/certificates/"+id).header("Authorization",bearer("population"))).andExpect(status().isNotFound());mvc.perform(get("/api/certificates").param("personId","9203").header("Authorization",bearer("population"))).andExpect(status().isOk()).andExpect(jsonPath("$.data.totalElements").value(0));}
@Test@Order(14)void viewerCannotEdit()throws Exception{performCreate("viewer",9201,"OTHER","NOAUTH1234","2020-01-01",null,403);}
@Test@Order(15)void adminFullNumberPopulationMasked()throws Exception{String admin=mvc.perform(get("/api/certificates/"+activeId).header("Authorization",bearer("admin"))).andReturn().getResponse().getContentAsString();String population=mvc.perform(get("/api/certificates/"+activeId).header("Authorization",bearer("population"))).andReturn().getResponse().getContentAsString();assertThat(admin).contains("P987654321");assertThat(population).contains("P987****4321").doesNotContain("P987654321");}
@Test@Order(16)void cancelAndAudit()throws Exception{mvc.perform(post("/api/certificates/"+activeId+"/cancel").header("Authorization",bearer("population")).contentType(MediaType.APPLICATION_JSON).content("{\"reason\":\"测试注销\",\"version\":1}")).andExpect(status().isOk());assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM operation_log WHERE operation_type='CERTIFICATE_CANCEL' AND detail NOT LIKE '%P987654321%'",Integer.class)).isGreaterThan(0);}
@Test@Order(17)void repeatedCancelRejected()throws Exception{mvc.perform(post("/api/certificates/"+activeId+"/cancel").header("Authorization",bearer("population")).contentType(MediaType.APPLICATION_JSON).content("{\"reason\":\"重复\",\"version\":2}")).andExpect(status().isConflict());}
@Test@Order(18)void cancelledCannotRestoreByUpdate()throws Exception{mvc.perform(put("/api/certificates/"+activeId).header("Authorization",bearer("population")).contentType(MediaType.APPLICATION_JSON).content("{\"certificateType\":\"OTHER\",\"certificateNo\":\"RESTORE123\",\"issueDate\":\"2020-01-01\",\"version\":2}")).andExpect(status().isConflict());}
@Test@Order(19)void noDeleteEndpoint()throws Exception{mvc.perform(delete("/api/certificates/"+activeId).header("Authorization",bearer("admin"))).andExpect(status().isMethodNotAllowed());}
@Test@Order(20)void residencePermitTablesUnaffected(){assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM residence_permit",Integer.class)).isZero();}
private String performCreate(String u,long person,String type,String no,String issue,String expire,int status)throws Exception{String body="{\"personId\":"+person+",\"certificateType\":\""+type+"\",\"certificateNo\":\""+no+"\",\"issueDate\":\""+issue+"\""+(expire==null?"":",\"expireDate\":\""+expire+"\"")+"}";return mvc.perform(post("/api/certificates").header("Authorization",bearer(u)).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().is(status)).andReturn().getResponse().getContentAsString();}private String bearer(String u)throws Exception{String b=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"username\":\""+u+"\",\"password\":\"123456\"}")).andReturn().getResponse().getContentAsString();return"Bearer "+json.readTree(b).path("data").path("token").asText();}}
