<template>
  <div class="page-container" v-loading="loading">
    <div class="page-header"><div><h1>申请详情</h1><p class="subtitle">申请状态以服务端返回为准；审批通过不等于业务已办结。</p></div><el-button @click="router.back()">返回</el-button></div>
    <el-card v-if="application" shadow="never"><template #header><div class="card-header"><span>{{ application.applicationNo }}</span><StatusTag :value="application.status" /></div></template><el-descriptions :column="2" border><el-descriptions-item label="业务类型">{{ BUSINESS_TYPE_LABEL[application.businessType] || application.businessType }}</el-descriptions-item><el-descriptions-item label="申请人">{{ application.applicantName || '-' }}</el-descriptions-item><el-descriptions-item label="申请标题">{{ application.title }}</el-descriptions-item><el-descriptions-item label="创建时间">{{ formatDateTime(application.createdAt) }}</el-descriptions-item><el-descriptions-item label="申请原因" :span="2">{{ application.reason }}</el-descriptions-item><el-descriptions-item label="备注" :span="2">{{ application.remark || '-' }}</el-descriptions-item></el-descriptions></el-card>
    <el-card v-if="migration" shadow="never"><template #header>迁移业务信息</template><el-descriptions :column="2" border><el-descriptions-item label="办理人员">{{ migration.personId }}</el-descriptions-item><el-descriptions-item label="迁移类型">{{ migration.migrationType }}</el-descriptions-item><el-descriptions-item label="迁出地">{{ migration.fromAddressSnapshot || migration.fromAddress || '-' }}</el-descriptions-item><el-descriptions-item label="迁往地">{{ migration.toAddress || migration.toAddressSnapshot || '-' }}</el-descriptions-item><el-descriptions-item label="业务状态"><StatusTag :value="migration.businessStatus" /></el-descriptions-item><el-descriptions-item label="业务版本">{{ migration.version }}</el-descriptions-item></el-descriptions><div v-if="canExecute" class="execute-bar"><el-button type="success" :loading="executing" @click="execute">执行{{ detail?.migrationIn ? '迁入' : '迁出' }}业务</el-button><span>执行成功后将重新读取服务端状态。</span></div></el-card>
    <el-card shadow="never"><template #header>申请材料</template><MaterialUploader v-if="isDraft && canUpload" :application-id="applicationId" @uploaded="load"/><MaterialList :materials="materials" :can-delete="isDraft && canDelete" @changed="load"/></el-card>
    <el-card shadow="never"><template #header>审批轨迹</template><ApprovalTimeline :logs="logs"/></el-card>
    <ApplicationActionBar :application="application" :loading="actionLoading" @submit="submit" @withdraw="withdraw"/>
  </div>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { ElMessage, ElMessageBox } from 'element-plus'
import StatusTag from '../../components/common/StatusTag.vue'; import MaterialUploader from '../../components/business/MaterialUploader.vue'; import MaterialList from '../../components/business/MaterialList.vue'; import ApprovalTimeline from '../../components/business/ApprovalTimeline.vue'; import ApplicationActionBar from '../../components/business/ApplicationActionBar.vue'
import { getApplicationApprovalLogs, getApplicationDetail, submitApplication, withdrawApplication } from '../../api/applications'; import { executeMigrationIn, executeMigrationOut, getMigrationApplicationDetail } from '../../api/migrations'; import { getMaterials } from '../../api/materials'; import { getMigrationRecord } from '../../adapters/migration'; import { BUSINESS_TYPE_LABEL } from '../../constants/application'; import { PERMISSIONS } from '../../constants/permissions'; import { useUserStore } from '../../stores/user'; import { formatDateTime } from '../../utils/date'; import { getApiErrorMessage, isApiConflict } from '../../utils/apiError'
const route=useRoute();const router=useRouter();const userStore=useUserStore();const applicationId=computed(()=>route.params.applicationId);const loading=ref(false);const actionLoading=ref(false);const executing=ref(false);const application=ref(null);const detail=ref(null);const materials=ref([]);const logs=ref([]);const migration=computed(()=>getMigrationRecord(detail.value));const isDraft=computed(()=>application.value?.status==='DRAFT');const canUpload=computed(()=>userStore.hasPermission(PERMISSIONS.MATERIAL_UPLOAD));const canDelete=computed(()=>userStore.hasPermission(PERMISSIONS.MATERIAL_DELETE));const canExecute=computed(()=>application.value?.status==='APPROVED' && detail.value?.executable && userStore.hasPermission(PERMISSIONS.MIGRATION_EXECUTE));
async function load(){loading.value=true;try{application.value=await getApplicationDetail(applicationId.value);const [migrationResult,materialResult,logResult]=await Promise.all([getMigrationApplicationDetail(applicationId.value),getMaterials(applicationId.value),getApplicationApprovalLogs(applicationId.value)]);detail.value=migrationResult;materials.value=materialResult||migrationResult.materials||[];logs.value=logResult||migrationResult.approvalLogs||[]}catch(error){ElMessage.error(getApiErrorMessage(error,'加载申请详情失败'))}finally{loading.value=false}}
async function submit(){await ElMessageBox.confirm('提交后不能继续编辑草稿，确认提交吗？','提交申请',{type:'warning'});actionLoading.value=true;try{await submitApplication(applicationId.value);ElMessage.success('申请已提交');await load()}catch(error){if(isApiConflict(error))await load();ElMessage.error(getApiErrorMessage(error,'提交失败'))}finally{actionLoading.value=false}}
async function withdraw(){await ElMessageBox.confirm('确认撤回该申请吗？','撤回申请',{type:'warning'});actionLoading.value=true;try{await withdrawApplication(applicationId.value);ElMessage.success('申请已撤回');await load()}catch(error){if(isApiConflict(error))await load();ElMessage.error(getApiErrorMessage(error,'撤回失败'))}finally{actionLoading.value=false}}
async function execute(){await ElMessageBox.confirm('执行会由后端变更当前户籍并生成归档，确认继续吗？','执行迁移',{type:'warning'});executing.value=true;try{const record=getMigrationRecord(detail.value);if(detail.value?.migrationIn)await executeMigrationIn(applicationId.value,record.version);else await executeMigrationOut(applicationId.value,record.version);ElMessage.success('业务执行请求成功');await load()}catch(error){if(isApiConflict(error))await load();ElMessage.error(getApiErrorMessage(error,'业务执行失败'))}finally{executing.value=false}}
onMounted(load)
</script>

<style scoped>.page-container{display:flex;flex-direction:column;gap:16px}.page-header{display:flex;justify-content:space-between;align-items:end}.page-header h1{margin:0 0 8px}.subtitle{margin:0;color:var(--el-text-color-secondary)}.card-header,.execute-bar{display:flex;align-items:center;justify-content:space-between;gap:12px}.execute-bar{margin-top:16px;justify-content:flex-start}.execute-bar span{font-size:13px;color:var(--el-text-color-secondary)}</style>
