CREATE TABLE sys_department (
    department_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_code VARCHAR(50) NOT NULL UNIQUE,
    department_name VARCHAR(100) NOT NULL,
    parent_id BIGINT,
    region_code VARCHAR(50),
    status VARCHAR(20) NOT NULL,
    sort_no INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sys_role (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR(50) NOT NULL UNIQUE,
    role_name VARCHAR(50) NOT NULL,
    role_level VARCHAR(10) NOT NULL,
    data_scope VARCHAR(20) NOT NULL,
    description VARCHAR(255),
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sys_permission (
    permission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_code VARCHAR(100) NOT NULL UNIQUE,
    permission_name VARCHAR(100) NOT NULL,
    module_name VARCHAR(100),
    permission_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sys_user (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role_id BIGINT NOT NULL,
    department_id BIGINT,
    real_name VARCHAR(50),
    phone VARCHAR(20),
    status VARCHAR(20) NOT NULL,
    last_login_time TIMESTAMP,
    last_login_ip VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (role_id) REFERENCES sys_role(role_id),
    FOREIGN KEY (department_id) REFERENCES sys_department(department_id)
);

CREATE TABLE sys_role_permission (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    FOREIGN KEY (role_id) REFERENCES sys_role(role_id),
    FOREIGN KEY (permission_id) REFERENCES sys_permission(permission_id)
);

CREATE TABLE operation_log (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    operation_type VARCHAR(50) NOT NULL,
    module_name VARCHAR(100),
    request_path VARCHAR(255),
    request_method VARCHAR(20),
    target_table VARCHAR(100),
    target_id VARCHAR(100),
    operation_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR(50),
    operation_result VARCHAR(50),
    error_message VARCHAR(500),
    user_agent VARCHAR(500),
    detail CLOB,
    FOREIGN KEY (user_id) REFERENCES sys_user(user_id)
);

INSERT INTO sys_department (department_id, department_code, department_name, region_code, status, sort_no)
VALUES (1, 'QUERY', '查询部门', '110000', 'ENABLED', 1),
       (2, 'POPULATION', '人口部门', '110000', 'ENABLED', 2),
       (3, 'SYSTEM', '系统管理部门', '110000', 'ENABLED', 3),
       (4, 'HOUSEHOLD', '户籍部门', '110000', 'ENABLED', 4),
       (5, 'APPROVAL', '审批部门', '110000', 'ENABLED', 5);

INSERT INTO sys_role (role_id, role_code, role_name, role_level, data_scope, status)
VALUES (1, 'QUERY_VIEWER', '查询统计人员', 'L1', 'DEPARTMENT', 'ENABLED'),
       (2, 'POPULATION_MANAGER', '人口信息管理人员', 'L2', 'REGION', 'ENABLED'),
       (3, 'SYSTEM_ADMIN', '系统管理员', 'L3', 'ALL', 'ENABLED'),
       (4, 'DISABLED_ROLE', '停用角色', 'L1', 'SELF', 'DISABLED'),
       (5, 'HOUSEHOLD_MANAGER', '户籍管理人员', 'L2', 'REGION', 'ENABLED'),
       (6, 'APPROVER', '审批人员', 'L3', 'REGION', 'ENABLED');

INSERT INTO sys_permission (permission_id, permission_code, permission_name, module_name, permission_type, status)
VALUES (1, 'population:view', '查看人口', 'POPULATION', 'API', 'ENABLED'),
       (2, 'population:edit', '编辑人口', 'POPULATION', 'API', 'ENABLED'),
       (3, 'log:view', '查看日志', 'LOG', 'API', 'ENABLED');

INSERT INTO sys_role_permission (role_id, permission_id)
VALUES (1, 1), (1, 3), (2, 1), (2, 2), (3, 1), (3, 2), (3, 3),
       (5, 1), (6, 1), (6, 2);

INSERT INTO sys_user (user_id, username, password_hash, role_id, department_id, real_name, status)
VALUES (1, 'viewer', '$2a$10$hqLjVyldvMDp7tlJcpkDZOaTT1dCAuSA5I7FgRfD/B7QXluT8ArB.', 1, 1, '查询统计人员', 'ENABLED'),
       (2, 'population', '$2a$10$hqLjVyldvMDp7tlJcpkDZOaTT1dCAuSA5I7FgRfD/B7QXluT8ArB.', 2, 2, '人口信息管理人员', 'ENABLED'),
       (3, 'admin', '$2a$10$hqLjVyldvMDp7tlJcpkDZOaTT1dCAuSA5I7FgRfD/B7QXluT8ArB.', 3, 3, '系统管理员', 'ENABLED'),
       (4, 'disabled', '$2a$10$hqLjVyldvMDp7tlJcpkDZOaTT1dCAuSA5I7FgRfD/B7QXluT8ArB.', 1, 1, '停用用户', 'DISABLED'),
       (5, 'disabled-role', '$2a$10$hqLjVyldvMDp7tlJcpkDZOaTT1dCAuSA5I7FgRfD/B7QXluT8ArB.', 4, 1, '停用角色用户', 'ENABLED'),
       (6, 'household', '$2a$10$hqLjVyldvMDp7tlJcpkDZOaTT1dCAuSA5I7FgRfD/B7QXluT8ArB.', 5, 4, '户籍管理人员', 'ENABLED'),
       (7, 'approver', '$2a$10$hqLjVyldvMDp7tlJcpkDZOaTT1dCAuSA5I7FgRfD/B7QXluT8ArB.', 6, 5, '审批人员', 'ENABLED');

CREATE TABLE residents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    gender VARCHAR(20) NOT NULL,
    birth_date DATE NOT NULL,
    id_card_number VARCHAR(18) NOT NULL UNIQUE,
    phone_number VARCHAR(30),
    province VARCHAR(100),
    city VARCHAR(100),
    district VARCHAR(100),
    address VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE person (
    person_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    gender CHAR(1) NOT NULL,
    id_card VARCHAR(18) NOT NULL UNIQUE,
    birth_date DATE,
    ethnicity VARCHAR(30),
    phone VARCHAR(20),
    current_address VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT '正常',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE household (
    household_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_no VARCHAR(30) NOT NULL UNIQUE,
    head_person_id BIGINT,
    address VARCHAR(255) NOT NULL,
    establish_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE business_application (
 application_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, application_no VARCHAR(40) NOT NULL UNIQUE,
 business_type VARCHAR(50) NOT NULL,title VARCHAR(200) NOT NULL,applicant_user_id BIGINT NOT NULL,
 applicant_department_id BIGINT,applicant_region_code VARCHAR(20),target_person_id BIGINT,target_household_id BIGINT,
 status VARCHAR(30) NOT NULL,reason CLOB NOT NULL,remark VARCHAR(500),submitted_at TIMESTAMP,completed_at TIMESTAMP,
 version INT NOT NULL DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(applicant_user_id) REFERENCES sys_user(user_id),FOREIGN KEY(applicant_department_id) REFERENCES sys_department(department_id)
);
CREATE TABLE application_material (
 material_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,application_id BIGINT NOT NULL,material_type VARCHAR(50) NOT NULL,
 material_name VARCHAR(200) NOT NULL,original_filename VARCHAR(255) NOT NULL,stored_filename VARCHAR(255) NOT NULL,
 storage_path VARCHAR(500) NOT NULL,content_type VARCHAR(100) NOT NULL,file_size BIGINT NOT NULL,file_sha256 CHAR(64) NOT NULL,
 required_flag TINYINT NOT NULL,verify_status VARCHAR(30) NOT NULL,verify_user_id BIGINT,verify_comment VARCHAR(500),verified_at TIMESTAMP,
 uploaded_by BIGINT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(application_id) REFERENCES business_application(application_id),FOREIGN KEY(verify_user_id) REFERENCES sys_user(user_id),FOREIGN KEY(uploaded_by) REFERENCES sys_user(user_id)
);
CREATE TABLE sys_approval_request (
 approval_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,approval_no VARCHAR(40) NOT NULL UNIQUE,application_id BIGINT NOT NULL UNIQUE,
 status VARCHAR(30) NOT NULL,current_approver_id BIGINT,current_department_id BIGINT,current_region_code VARCHAR(20),submitted_by BIGINT NOT NULL,
 submitted_at TIMESTAMP NOT NULL,decided_by BIGINT,decided_at TIMESTAMP,decision_comment VARCHAR(500),version INT NOT NULL DEFAULT 0,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(application_id) REFERENCES business_application(application_id)
);
CREATE TABLE sys_approval_log (
 log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,approval_id BIGINT,application_id BIGINT NOT NULL,action VARCHAR(30) NOT NULL,
 from_status VARCHAR(30),to_status VARCHAR(30) NOT NULL,operator_user_id BIGINT NOT NULL,comment VARCHAR(500),operation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 ip_address VARCHAR(50),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(approval_id) REFERENCES sys_approval_request(approval_id),FOREIGN KEY(application_id) REFERENCES business_application(application_id)
);

INSERT INTO sys_permission(permission_id,permission_code,permission_name,module_name,permission_type,status) VALUES
 (4,'application:view','查看申请','APPLICATION','API','ENABLED'),(5,'application:create','创建申请','APPLICATION','API','ENABLED'),
 (6,'application:edit','编辑申请','APPLICATION','API','ENABLED'),(7,'application:submit','提交申请','APPLICATION','API','ENABLED'),
 (8,'application:withdraw','撤回申请','APPLICATION','API','ENABLED'),(9,'material:view','查看材料','MATERIAL','API','ENABLED'),
 (10,'material:upload','上传材料','MATERIAL','API','ENABLED'),(11,'material:delete','删除材料','MATERIAL','API','ENABLED'),
 (12,'material:verify','核验材料','MATERIAL','API','ENABLED'),(13,'approval:view','查看审批','APPROVAL','API','ENABLED'),
 (14,'approval:handle','处理审批','APPROVAL','API','ENABLED');
INSERT INTO sys_role_permission(role_id,permission_id) VALUES
 (1,4),(2,4),(2,5),(2,6),(2,7),(2,8),(2,9),(2,10),(2,11),
 (3,4),(3,5),(3,6),(3,7),(3,8),(3,9),(3,10),(3,11),(3,12),(3,13),(3,14),
 (5,4),(5,5),(5,6),(5,7),(5,8),(5,9),(5,10),(5,11),(6,4),(6,9),(6,12),(6,13),(6,14);
INSERT INTO sys_department(department_id,department_code,department_name,region_code,status,sort_no)
 VALUES(6,'APPROVAL_OTHER','外区审批部门','120000','ENABLED',6);
INSERT INTO sys_user(user_id,username,password_hash,role_id,department_id,real_name,status)
 VALUES(8,'approver-other','$2a$10$hqLjVyldvMDp7tlJcpkDZOaTT1dCAuSA5I7FgRfD/B7QXluT8ArB.',6,6,'外区审批人员','ENABLED');
