package com.wjx871.population.household;
import com.wjx871.population.audit.OperationLogService; import com.wjx871.population.common.BusinessException; import com.wjx871.population.person.*; import com.wjx871.population.security.*; import jakarta.servlet.http.HttpServletRequest; import java.util.*; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @RequiredArgsConstructor public class HouseholdService {
private static final Set<String> TYPES=Set.of("FAMILY","COLLECTIVE"); private static final Set<String> RELATIONS=Set.of("HEAD","SPOUSE","CHILD","PARENT","OTHER");
private final HouseholdMapper mapper;private final SensitiveDataMaskingService masking;private final OperationLogService audit;
@Transactional(readOnly=true) public Page<HouseholdView> search(String no,String head,String address,String region,String type,String status,Pageable p){var scope=DataScopeCriteria.current();validateRequestedRegion(region,scope);long total=mapper.count(t(no),t(head),t(address),t(region),t(type),t(status),scope);var list=mapper.search(t(no),t(head),t(address),t(region),t(type),t(status),scope,p.getPageSize(),p.getOffset(),order(p)).stream().map(h->view(h,List.of())).toList();return new PageImpl<>(list,p,total);}
@Transactional(readOnly=true) public HouseholdView detail(Long id){Household h=requireScoped(id);return view(h,memberViews(mapper.members(id)));}
@Transactional(readOnly=true) public List<HouseholdMemberView> members(Long id){requireScoped(id);return memberViews(mapper.members(id));}
@Transactional(readOnly=true) public HouseholdMemberView member(Long householdId,Long memberId){requireScoped(householdId);HouseholdMember m=mapper.lockMember(memberId).filter(x->householdId.equals(x.getHouseholdId())).orElseThrow(()->nf("家庭成员不存在"));return memberView(m);}
@Transactional public HouseholdView create(HouseholdCreateRequest q,HttpServletRequest req){scopeWrite(q.regionCode());if(!TYPES.contains(q.householdType()))bad("不支持的家庭户类型");if(mapper.countNo(q.householdNo().trim())>0)conflict("户号已存在");Person head=q.headPersonId()==null?null:eligible(q.headPersonId());Household h=new Household();h.setHouseholdNo(q.householdNo().trim());h.setAddress(q.address().trim());h.setRegionCode(q.regionCode().trim());h.setHouseholdType(q.householdType());h.setEstablishDate(q.establishDate());h.setStatus("ACTIVE");h.setHeadPersonId(head==null?null:head.getPersonId());h.setVersion(0);mapper.insertHousehold(h);if(head!=null){ensureFree(head.getPersonId());HouseholdMember m=new HouseholdMember();m.setHouseholdId(h.getHouseholdId());m.setPersonId(head.getPersonId());m.setRelationship("HEAD");m.setJoinDate(q.establishDate());m.setStatus("ACTIVE");m.setVersion(0);mapper.insertMember(m);}log("HOUSEHOLD_CREATE",null,req);return detail(h.getHouseholdId());}
@Transactional public HouseholdView update(Long id,HouseholdUpdateRequest q,HttpServletRequest req){Household h=mapper.lock(id).orElseThrow(()->nf("家庭户不存在"));scopeWrite(h.getRegionCode());scopeWrite(q.regionCode());if(!"ACTIVE".equals(h.getStatus())||!h.getStatus().equals(q.status()))conflict("普通修改不得改变家庭户状态");if(!TYPES.contains(q.householdType()))bad("不支持的家庭户类型");h.setAddress(q.address().trim());h.setRegionCode(q.regionCode().trim());h.setHouseholdType(q.householdType());h.setEstablishDate(q.establishDate());h.setVersion(q.version());if(mapper.updateHousehold(h)==0)conflict("家庭户版本冲突");log("HOUSEHOLD_UPDATE",null,req);return detail(id);}
@Transactional public HouseholdMemberView add(Long hid,MemberAddRequest q,HttpServletRequest req){Household h=activeLocked(hid);Person p=eligible(q.personId());ensureFree(p.getPersonId());String relation=relationship(q.relationship());if("HEAD".equals(relation)&&h.getHeadPersonId()!=null)conflict("家庭户已有户主，请使用户主变更接口");HouseholdMember m=new HouseholdMember();m.setHouseholdId(hid);m.setPersonId(p.getPersonId());m.setRelationship(relation);m.setJoinDate(q.joinDate());m.setStatus("ACTIVE");m.setVersion(0);try{mapper.insertMember(m);}catch(RuntimeException e){conflict("人员已存在家庭关系");}log("HOUSEHOLD_MEMBER_ADD",null,req);return member(hid,m.getMemberId());}
@Transactional public HouseholdMemberView updateMember(Long hid,Long mid,MemberUpdateRequest q,HttpServletRequest req){activeLocked(hid);HouseholdMember m=memberLocked(hid,mid);String r=relationship(q.relationship());if("HEAD".equals(r)&&!"HEAD".equals(m.getRelationship()))conflict("设置户主必须使用户主变更接口");if("HEAD".equals(m.getRelationship())&&!"HEAD".equals(r))conflict("当前户主关系必须通过户主变更接口调整");if(mapper.updateRelationship(mid,r,q.version())==0)conflict("成员版本冲突");log("HOUSEHOLD_MEMBER_UPDATE",null,req);return member(hid,mid);}
@Transactional public void leave(Long hid,Long mid,MemberLeaveRequest q,HttpServletRequest req){activeLocked(hid);HouseholdMember m=memberLocked(hid,mid);if("HEAD".equals(m.getRelationship()))conflict("户主不能直接离户，请先变更户主");if(mapper.leaveMember(mid,q.leaveDate(),q.version())==0)conflict("成员版本冲突");log("HOUSEHOLD_MEMBER_LEAVE",null,req);}
@Transactional public HouseholdView changeHead(Long hid,ChangeHeadRequest q,HttpServletRequest req){Household h=activeLocked(hid);eligible(q.newHeadPersonId());HouseholdMember next=mapper.activeMemberByPerson(q.newHeadPersonId()).filter(x->hid.equals(x.getHouseholdId())).orElseThrow(()->conflictEx("新户主必须是当前家庭户有效成员"));HouseholdMember old=mapper.activeHead(hid).orElse(null);if(old!=null&&old.getPersonId().equals(q.newHeadPersonId()))conflict("该人员已经是户主");if(old!=null&&mapper.updateRelationship(old.getMemberId(),"OTHER",old.getVersion())==0)conflict("原户主关系版本冲突");if(mapper.updateRelationship(next.getMemberId(),"HEAD",next.getVersion())==0)conflict("新户主关系版本冲突");if(mapper.changeHead(hid,q.newHeadPersonId(),q.version())==0)conflict("家庭户版本冲突");log("HOUSEHOLD_HEAD_CHANGE","reason="+q.reason(),req);return detail(hid);}
private Household activeLocked(Long id){Household h=mapper.lock(id).orElseThrow(()->nf("家庭户不存在"));scopeWrite(h.getRegionCode());if(!"ACTIVE".equals(h.getStatus()))conflict("家庭户不是有效状态");return h;} private HouseholdMember memberLocked(Long h,Long m){return mapper.lockMember(m).filter(x->h.equals(x.getHouseholdId())&&"ACTIVE".equals(x.getStatus())).orElseThrow(()->nf("有效家庭成员不存在"));}
private Person eligible(Long id){Person p=mapper.lockPerson(id).orElseThrow(()->nf("人员不存在"));if("已注销".equals(p.getStatus())||"CANCELLED".equals(p.getCurrentStatusCode())||"DECEASED".equals(p.getCurrentStatusCode()))conflict("已注销人员不能维护家庭关系");return p;} private void ensureFree(Long id){if(mapper.activeMemberByPerson(id).isPresent())conflict("人员已属于其他有效家庭户");}
private Household requireScoped(Long id){return mapper.findScoped(id,DataScopeCriteria.current()).orElseThrow(()->new BusinessException(HttpStatus.FORBIDDEN,"家庭户不存在或超出数据范围"));} private HouseholdView view(Household h,List<HouseholdMemberView> m){return HouseholdView.from(h,m,masking.address(h.getAddress()));} private List<HouseholdMemberView> memberViews(List<HouseholdMember> x){return x.stream().map(this::memberView).toList();} private HouseholdMemberView memberView(HouseholdMember m){return HouseholdMemberView.from(m,masking.identity(m.getIdCard()),masking.phone(m.getPhone()));}
private void scopeWrite(String r){var u=CurrentUserContext.requireUser();if(u.dataScope()==DataScope.ALL)return;if(u.dataScope()==DataScope.SELF||u.regionCode()==null||r==null||!r.startsWith(u.regionCode().substring(0,Math.min(2,u.regionCode().length()))))throw new BusinessException(HttpStatus.FORBIDDEN,"超出家庭户数据范围");} private void validateRequestedRegion(String r,DataScopeCriteria s){if(r!=null&&s.dataScope()!=DataScope.ALL)scopeWrite(r);}
private String relationship(String r){String x=r.trim().toUpperCase();if(!RELATIONS.contains(x))bad("不支持的成员关系");return x;} private String order(Pageable p){if(p.getSort().isUnsorted())return "h.household_id DESC";var o=p.getSort().iterator().next();String c=switch(o.getProperty()){case "householdNo"->"h.household_no";case "establishDate"->"h.establish_date";case "status"->"h.status";default->"h.household_id";};return c+(o.isAscending()?" ASC":" DESC");} private String t(String s){return s==null||s.isBlank()?null:s.trim();}
private void log(String type,String detail,HttpServletRequest req){audit.recordTransactional(CurrentUserContext.requireUser().userId(),type,"HOUSEHOLD",detail==null?type:detail,req);}
private static void bad(String m){throw new BusinessException(HttpStatus.BAD_REQUEST,m);}private static void conflict(String m){throw conflictEx(m);}private static BusinessException conflictEx(String m){return new BusinessException(HttpStatus.CONFLICT,m);}private static BusinessException nf(String m){return new BusinessException(HttpStatus.NOT_FOUND,m);}
}
