package com.wjx871.population.household;
import com.wjx871.population.common.ApiResponse; import jakarta.servlet.http.HttpServletRequest; import jakarta.validation.Valid; import java.util.List; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.*; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/households") @RequiredArgsConstructor public class HouseholdController {private final HouseholdService service;
@GetMapping @PreAuthorize("hasAuthority('household:view')") public ApiResponse<Page<HouseholdView>> search(@RequestParam(required=false)String householdNo,@RequestParam(required=false)String headPersonName,@RequestParam(required=false)String address,@RequestParam(required=false)String regionCode,@RequestParam(required=false)String householdType,@RequestParam(required=false)String status,Pageable pageable){return ApiResponse.ok(service.search(householdNo,headPersonName,address,regionCode,householdType,status,pageable));}
@GetMapping("/{id}") @PreAuthorize("hasAuthority('household:view')") public ApiResponse<HouseholdView> detail(@PathVariable Long id){return ApiResponse.ok(service.detail(id));}
@PostMapping @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAuthority('household:edit')") public ApiResponse<HouseholdView> create(@Valid@RequestBody HouseholdCreateRequest q,HttpServletRequest r){return ApiResponse.created(service.create(q,r));}
@PutMapping("/{id}") @PreAuthorize("hasAuthority('household:edit')") public ApiResponse<HouseholdView> update(@PathVariable Long id,@Valid@RequestBody HouseholdUpdateRequest q,HttpServletRequest r){return ApiResponse.ok(service.update(id,q,r));}
@GetMapping("/{id}/members") @PreAuthorize("hasAuthority('household:view')") public ApiResponse<List<HouseholdMemberView>> members(@PathVariable Long id){return ApiResponse.ok(service.members(id));}
@GetMapping("/{id}/members/{memberId}") @PreAuthorize("hasAuthority('household:view')") public ApiResponse<HouseholdMemberView> member(@PathVariable Long id,@PathVariable Long memberId){return ApiResponse.ok(service.member(id,memberId));}
@PostMapping("/{id}/members") @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAuthority('household:edit')") public ApiResponse<HouseholdMemberView> add(@PathVariable Long id,@Valid@RequestBody MemberAddRequest q,HttpServletRequest r){return ApiResponse.created(service.add(id,q,r));}
@PutMapping("/{id}/members/{memberId}") @PreAuthorize("hasAuthority('household:edit')") public ApiResponse<HouseholdMemberView> updateMember(@PathVariable Long id,@PathVariable Long memberId,@Valid@RequestBody MemberUpdateRequest q,HttpServletRequest r){return ApiResponse.ok(service.updateMember(id,memberId,q,r));}
@PostMapping("/{id}/members/{memberId}/leave") @PreAuthorize("hasAuthority('household:edit')") public ApiResponse<Void> leave(@PathVariable Long id,@PathVariable Long memberId,@Valid@RequestBody MemberLeaveRequest q,HttpServletRequest r){service.leave(id,memberId,q,r);return ApiResponse.ok(null);}
@PostMapping("/{id}/change-head") @PreAuthorize("hasAuthority('household:edit')") public ApiResponse<HouseholdView> changeHead(@PathVariable Long id,@Valid@RequestBody ChangeHeadRequest q,HttpServletRequest r){return ApiResponse.ok(service.changeHead(id,q,r));}}
