package com.wjx871.population.household;
import static org.assertj.core.api.Assertions.assertThat; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*; import com.fasterxml.jackson.databind.*; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.MediaType; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.test.web.servlet.MockMvc;
@SpringBootTest @AutoConfigureMockMvc class Phase08HouseholdMasterDataIntegrationTest {@Autowired MockMvc mvc;@Autowired JdbcTemplate jdbc;@Autowired ObjectMapper json;
@BeforeEach void setup(){jdbc.update("DELETE FROM residence_archive");jdbc.update("DELETE FROM cancellation_record");jdbc.update("DELETE FROM migration_in");jdbc.update("DELETE FROM migration_out");jdbc.update("DELETE FROM residence");jdbc.update("DELETE FROM household_member");jdbc.update("DELETE FROM sys_approval_log");jdbc.update("DELETE FROM sys_approval_request");jdbc.update("DELETE FROM application_material");jdbc.update("DELETE FROM business_application");jdbc.update("DELETE FROM operation_log");jdbc.update("DELETE FROM household WHERE household_id>=801");jdbc.update("DELETE FROM person WHERE person_id>=801");jdbc.update("INSERT INTO person(person_id,name,gender,id_card,birth_date,phone,current_address,status,current_status_code) VALUES(801,'户主甲','男','110105194912310011',DATE '1949-12-31','13800138000','北京市东城区一号','正常','REGISTERED'),(802,'成员乙','女','11010519491231002X',DATE '1949-12-31','13900139000','北京市东城区二号','正常','REGISTERED'),(803,'外户丙','男','110105198001010015',DATE '1980-01-01',NULL,NULL,'正常','REGISTERED'),(804,'注销丁','男','110105198001010031',DATE '1980-01-01',NULL,NULL,'已注销','CANCELLED')");jdbc.update("INSERT INTO household(household_id,household_no,head_person_id,address,region_code,household_type,establish_date,status,version) VALUES(801,'P08-801',801,'北京市东城区一号','110101','FAMILY',DATE '2020-01-01','ACTIVE',0),(802,'P08-802',803,'上海市示例路','310000','FAMILY',DATE '2020-01-01','ACTIVE',0)");jdbc.update("INSERT INTO household_member(member_id,household_id,person_id,relationship,join_date,status,version) VALUES(801,801,801,'HEAD',DATE '2020-01-01','ACTIVE',0),(802,802,803,'HEAD',DATE '2020-01-01','ACTIVE',0)");}
@Test void viewerAllScopeListIsPagedAndMasked()throws Exception{mvc.perform(get("/api/households").header("Authorization",bearer(token("viewer"))).param("householdNo","P08").param("size","10")).andExpect(status().isOk()).andExpect(jsonPath("$.data.totalElements").value(2)).andExpect(jsonPath("$.data.content[0].householdNo").value("P08-802")).andExpect(jsonPath("$.data.content[0].address").value(org.hamcrest.Matchers.containsString("隐藏")));}
@Test void allScopeCanSeeBothRegions()throws Exception{mvc.perform(get("/api/households").header("Authorization",bearer(token("admin"))).param("householdNo","P08")).andExpect(status().isOk()).andExpect(jsonPath("$.data.totalElements").value(2));}
@Test void detailAndMembersMaskIdentityAndPhone()throws Exception{mvc.perform(get("/api/households/801").header("Authorization",bearer(token("viewer")))).andExpect(status().isOk()).andExpect(jsonPath("$.data.members[0].idCard").value("1101**********0011")).andExpect(jsonPath("$.data.members[0].phone").value("138****8000"));}
@Test void createWithHeadIsAtomic()throws Exception{String b=mvc.perform(post("/api/households").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"householdNo\":\"P08-NEW\",\"address\":\"北京市新址\",\"regionCode\":\"110101\",\"householdType\":\"FAMILY\",\"establishDate\":\"2026-01-01\",\"headPersonId\":802}")).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();long id=json.readTree(b).path("data").path("householdId").asLong();assertThat(count("household","household_id",id)).isOne();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM household_member WHERE household_id=? AND relationship='HEAD' AND status='ACTIVE'",Integer.class,id)).isOne();}
@Test void duplicateNumberConflicts()throws Exception{mvc.perform(post("/api/households").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"householdNo\":\"P08-801\",\"address\":\"北京市新址\",\"regionCode\":\"110101\",\"householdType\":\"FAMILY\",\"establishDate\":\"2026-01-01\"}")).andExpect(status().isConflict());}
@Test void crossRegionWriteForbidden()throws Exception{mvc.perform(post("/api/households").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"householdNo\":\"P08-X\",\"address\":\"上海\",\"regionCode\":\"310000\",\"householdType\":\"FAMILY\",\"establishDate\":\"2026-01-01\"}")).andExpect(status().isForbidden());}
@Test void updateUsesVersionAndCannotCancel()throws Exception{mvc.perform(put("/api/households/801").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"address\":\"北京市新地址\",\"regionCode\":\"110101\",\"householdType\":\"FAMILY\",\"establishDate\":\"2020-01-01\",\"status\":\"ACTIVE\",\"version\":0}")).andExpect(status().isOk());mvc.perform(put("/api/households/801").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"address\":\"x\",\"regionCode\":\"110101\",\"householdType\":\"FAMILY\",\"establishDate\":\"2020-01-01\",\"status\":\"CANCELLED\",\"version\":1}")).andExpect(status().isConflict());}
@Test void addMemberDoesNotCreateResidenceOrMigration()throws Exception{mvc.perform(post("/api/households/801/members").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"personId\":802,\"relationship\":\"CHILD\",\"joinDate\":\"2026-01-01\"}")).andExpect(status().isCreated());assertThat(count("residence","person_id",802)).isZero();assertThat(count("migration_in","person_id",802)).isZero();}
@Test void duplicateActiveMemberConflicts()throws Exception{mvc.perform(post("/api/households/801/members").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"personId\":803,\"relationship\":\"OTHER\",\"joinDate\":\"2026-01-01\"}")).andExpect(status().isConflict());}
@Test void cancelledPersonCannotJoin()throws Exception{mvc.perform(post("/api/households/801/members").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"personId\":804,\"relationship\":\"OTHER\",\"joinDate\":\"2026-01-01\"}")).andExpect(status().isConflict());}
@Test void ordinaryMemberCanLeaveButHeadCannot()throws Exception{add802();long mid=jdbc.queryForObject("SELECT member_id FROM household_member WHERE household_id=801 AND person_id=802",Long.class);mvc.perform(post("/api/households/801/members/"+mid+"/leave").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"leaveDate\":\"2026-02-01\",\"version\":0}")).andExpect(status().isOk());assertThat(jdbc.queryForObject("SELECT status FROM household_member WHERE member_id=?",String.class,mid)).isEqualTo("MOVED_OUT");mvc.perform(post("/api/households/801/members/801/leave").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"leaveDate\":\"2026-02-01\",\"version\":0}")).andExpect(status().isConflict());}
@Test void memberWithCurrentResidenceMustUseMigrationOrCancellation()throws Exception{add802();long mid=jdbc.queryForObject("SELECT member_id FROM household_member WHERE household_id=801 AND person_id=802",Long.class);jdbc.update("INSERT INTO residence(residence_id,person_id,household_id,registered_address,region_code,register_type_code,register_date,start_date,status,created_by,version) VALUES(802,802,801,'北京市东城区一号','110101','INITIAL',DATE '2020-01-01',DATE '2020-01-01','ACTIVE',1,0)");mvc.perform(post("/api/households/801/members/"+mid+"/leave").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"leaveDate\":\"2026-02-01\",\"version\":0}")).andExpect(status().isConflict());assertThat(jdbc.queryForObject("SELECT status FROM household_member WHERE member_id=?",String.class,mid)).isEqualTo("ACTIVE");assertThat(count("residence","person_id",802)).isOne();}
@Test void headChangeKeepsSingleHeadAndHouseholdConsistent()throws Exception{add802();mvc.perform(post("/api/households/801/change-head").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"newHeadPersonId\":802,\"reason\":\"家庭决定\",\"version\":0}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.headPersonId").value(802));assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM household_member WHERE household_id=801 AND status='ACTIVE' AND relationship='HEAD'",Integer.class)).isOne();assertThat(jdbc.queryForObject("SELECT head_person_id FROM household WHERE household_id=801",Long.class)).isEqualTo(802);}
@Test void nonMemberCannotBecomeHead()throws Exception{mvc.perform(post("/api/households/801/change-head").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"newHeadPersonId\":802,\"reason\":\"错误操作\",\"version\":0}")).andExpect(status().isConflict());}
@Test void staleHeadVersionRollsBackRelationships()throws Exception{add802();mvc.perform(post("/api/households/801/change-head").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"newHeadPersonId\":802,\"reason\":\"并发\",\"version\":9}")).andExpect(status().isConflict());assertThat(jdbc.queryForObject("SELECT person_id FROM household_member WHERE household_id=801 AND relationship='HEAD' AND status='ACTIVE'",Long.class)).isEqualTo(801);}
@Test void writesCreateAuditLog()throws Exception{add802();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM operation_log WHERE operation_type='HOUSEHOLD_MEMBER_ADD'",Integer.class)).isOne();}
private void add802()throws Exception{mvc.perform(post("/api/households/801/members").header("Authorization",bearer(token("household"))).contentType(MediaType.APPLICATION_JSON).content("{\"personId\":802,\"relationship\":\"CHILD\",\"joinDate\":\"2026-01-01\"}")).andExpect(status().isCreated());}
private String token(String user)throws Exception{String b=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"username\":\""+user+"\",\"password\":\"123456\"}")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();return json.readTree(b).path("data").path("token").asText();}private String bearer(String x){return "Bearer "+x;}private int count(String t,String c,long id){return jdbc.queryForObject("SELECT COUNT(*) FROM "+t+" WHERE "+c+"=?",Integer.class,id);}}
