package com.wjx871.population.application;

public enum BusinessType {
    PERSON_CANCELLATION, HOUSEHOLD_CANCELLATION, MIGRATION_IN, MIGRATION_OUT,
    FLOATING_REGISTRATION, RESIDENCE_PERMIT_FIRST_ISSUE, RESIDENCE_PERMIT_ENDORSEMENT,
    RESIDENCE_PERMIT_CANCELLATION, KEY_POPULATION_REGISTER, KEY_POPULATION_RELEASE, SENSITIVE_DATA_EXPORT
}
