package com.wjx871.population.application;

public enum BusinessType {
    PERSON_CANCELLATION, HOUSEHOLD_CANCELLATION, MIGRATION_IN, MIGRATION_OUT,
    KEY_POPULATION_REGISTER, KEY_POPULATION_RELEASE, SENSITIVE_DATA_EXPORT
}
